# P15 第二模型：CP→OR 可訓練雙塔模型

這個 notebook 將第二模型改成接近主模型流程，而不是只做簡化的 retrieval baseline。

流程如下：

1. 先以 `compatibility_train.txt` 訓練 CP binary compatibility prediction model。
2. 以 `compatibility_valid.txt` 選擇最佳 CP checkpoint。
3. 在 `compatibility_test.txt` 計算 CP AUC，並以 `fill_in_blank_test.json` 計算 CP FITB Accuracy。
4. 將 CP model 的 item encoder 與 outfit text encoder 遷移到 OR retrieval model。
5. 以 FITB ranking 訓練 OR model，並在 test split 上計算 OR/CIR Recall@K。

兩個文字條件會分開訓練、分開儲存：

- `original_text`：原始 `url_name + title`
- `context_aware_description`：本研究生成之情境感知描述

輸出根目錄維持不變：

```text
/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/
```

In [1]:
from pathlib import Path
import json
import pickle
import csv
import math
import random
import time
from collections import defaultdict
from typing import Dict, List, Tuple, Optional

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

try:
    from tqdm.auto import tqdm
except ModuleNotFoundError:
    def tqdm(iterable=None, **kwargs):
        return iterable if iterable is not None else (lambda x: x)

try:
    from sklearn.metrics import roc_auc_score as sklearn_roc_auc_score
except Exception:
    sklearn_roc_auc_score = None

# ------------------------------------------------------------
# 路徑設定
# ------------------------------------------------------------
PROJECT_ROOT = Path('/home/ester/valid_description')
POLYVORE_DIR = PROJECT_ROOT / 'polyvore_data' / 'polyvore_outfits'
DISJOINT_DIR = POLYVORE_DIR / 'disjoint'
FASHIONCLIP_DIR = PROJECT_ROOT / 'fashionclip_data'
JOURNAL_DIR = PROJECT_ROOT / 'experiment data' / 'journal_figures_tables_20260629'

RUN_ROOT = JOURNAL_DIR / 'second_model_runs' / 'fashionclip_two_tower_fitb_or'
MODEL_ROOT = RUN_ROOT / 'models'
RESULT_ROOT = RUN_ROOT / 'results'

for directory in [RUN_ROOT, MODEL_ROOT, RESULT_ROOT]:
    directory.mkdir(parents=True, exist_ok=True)

print('第二模型輸出根目錄：')
print(RUN_ROOT)

第二模型輸出根目錄：
/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or

In [2]:
# ------------------------------------------------------------
# 實驗設定
# ------------------------------------------------------------

# 新流程建議先跑 seed 1，確認 CP AUC / FITB / OR Recall 都正常後，再改回 [1, 2, 3, 4, 5]。
SEEDS = [1, 2, 3, 4, 5]

TEXT_VARIANTS = {
    'original_text': 'encoded_outfitUrlTitle_en_fashionClip.pkl',
    'context_aware_description': 'encoded_NewoutfitUrlTitle_en_fashionClip.pkl',
}

MAX_ITEM_LEN = 16
ITEM_DIM = 1024       # FashionCLIP image 512 + item text 512
TEXT_DIM = 512        # outfit-level FashionCLIP text embedding
CATEGORY_DIM = 512    # category text embedding

# 與 Hybrid Attention 主模型對齊：最多訓練 100 epochs，不使用 early stopping。
# CP 與 OR 都以 validation FITB accuracy 更新最佳 checkpoint。
CP_EPOCHS = 100
OR_EPOCHS = 100

BATCH_SIZE = 256
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4
DROPOUT = 0.15
HIDDEN_DIM = 512
EMBED_DIM = 256
NUM_WORKERS = 0

MIN_CANDIDATES_PER_FG = 3000
K_LIST = [1, 3, 5, 10, 30, 50]

# True 會覆蓋同一路徑下舊的 checkpoint / log / result。
FORCE_RETRAIN = True

# 除錯用：正式實驗請維持 None。
TRAIN_LIMIT = None
VALID_LIMIT = None
TEST_LIMIT = None

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
PIN_MEMORY = DEVICE == 'cuda'

print('使用裝置：', DEVICE)
print('訓練 seeds：', SEEDS)
print('文字條件：', list(TEXT_VARIANTS.keys()))

使用裝置： cuda
訓練 seeds： [1, 2, 3, 4, 5]
文字條件： ['original_text', 'context_aware_description']

In [3]:
# ------------------------------------------------------------
# 基本工具
# ------------------------------------------------------------
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def load_json(path: Path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def load_pickle(path: Path):
    with open(path, 'rb') as f:
        return pickle.load(f)


def as_key(x) -> str:
    return str(x)


def vector_to_float32(x) -> np.ndarray:
    return np.asarray(x, dtype=np.float32)


def write_csv(path: Path, rows: List[dict], fieldnames: Optional[List[str]] = None):
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        fieldnames = sorted({key for row in rows for key in row.keys()}) if rows else []
    with open(path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)
    print(f'[寫入] {path}')


def append_csv(path: Path, row: dict, fieldnames: List[str]):
    path.parent.mkdir(parents=True, exist_ok=True)
    file_exists = path.exists()
    with open(path, 'a', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if not file_exists:
            writer.writeheader()
        writer.writerow(row)


def mean_std_text(values: List[float], digits: int = 4) -> str:
    arr = np.asarray(values, dtype=np.float64)
    if len(arr) == 0:
        return ''
    if len(arr) == 1:
        return f'{arr.mean():.{digits}f} ± 0.0000'
    return f'{arr.mean():.{digits}f} ± {arr.std(ddof=1):.{digits}f}'


def binary_auc(labels, scores) -> float:
    labels = np.asarray(labels, dtype=np.int64)
    scores = np.asarray(scores, dtype=np.float64)
    if sklearn_roc_auc_score is not None:
        return float(sklearn_roc_auc_score(labels, scores))

    order = np.argsort(scores)
    ranks = np.empty_like(order, dtype=np.float64)
    ranks[order] = np.arange(1, len(scores) + 1)
    pos = labels == 1
    n_pos = pos.sum()
    n_neg = len(labels) - n_pos
    if n_pos == 0 or n_neg == 0:
        return float('nan')
    rank_sum_pos = ranks[pos].sum()
    auc = (rank_sum_pos - n_pos * (n_pos + 1) / 2) / (n_pos * n_neg)
    return float(auc)

In [4]:
# ------------------------------------------------------------
# 載入資料與特徵
# ------------------------------------------------------------
required_paths = [
    FASHIONCLIP_DIR / 'img_feats_fashionClip.pkl',
    FASHIONCLIP_DIR / 'encoded_title_description_distiluse-base-multilingual-cased-v2.pkl',
    FASHIONCLIP_DIR / 'encoded_category_distiluse-base-multilingual-cased-v2.pkl',
    FASHIONCLIP_DIR / TEXT_VARIANTS['original_text'],
    FASHIONCLIP_DIR / TEXT_VARIANTS['context_aware_description'],
    POLYVORE_DIR / 'polyvore_item_metadata.json',
    DISJOINT_DIR / 'train.json',
    DISJOINT_DIR / 'valid.json',
    DISJOINT_DIR / 'test.json',
    DISJOINT_DIR / 'compatibility_train.txt',
    DISJOINT_DIR / 'compatibility_valid.txt',
    DISJOINT_DIR / 'compatibility_test.txt',
    DISJOINT_DIR / 'fill_in_blank_train.json',
    DISJOINT_DIR / 'fill_in_blank_valid.json',
    DISJOINT_DIR / 'fill_in_blank_test.json',
]
missing_paths = [str(p) for p in required_paths if not p.exists()]
if missing_paths:
    raise FileNotFoundError('找不到必要檔案：\n' + '\n'.join(missing_paths))

img_feats = load_pickle(FASHIONCLIP_DIR / 'img_feats_fashionClip.pkl')
item_text_feats = load_pickle(FASHIONCLIP_DIR / 'encoded_title_description_distiluse-base-multilingual-cased-v2.pkl')
category_feats = load_pickle(FASHIONCLIP_DIR / 'encoded_category_distiluse-base-multilingual-cased-v2.pkl')
metadata = load_json(POLYVORE_DIR / 'polyvore_item_metadata.json')

split_outfits = {
    'train': load_json(DISJOINT_DIR / 'train.json'),
    'valid': load_json(DISJOINT_DIR / 'valid.json'),
    'test': load_json(DISJOINT_DIR / 'test.json'),
}
fitb_raw = {
    'train': load_json(DISJOINT_DIR / 'fill_in_blank_train.json'),
    'valid': load_json(DISJOINT_DIR / 'fill_in_blank_valid.json'),
    'test': load_json(DISJOINT_DIR / 'fill_in_blank_test.json'),
}

print('PO-D outfit 數量：')
for split in ['train', 'valid', 'test']:
    print(f'  {split}: outfits={len(split_outfits[split]):,}, FITB questions={len(fitb_raw[split]):,}')
print(f'item image features: {len(img_feats):,}')
print(f'item text features: {len(item_text_feats):,}')
print(f'category features: {len(category_feats):,}')

PO-D outfit 數量：
  train: outfits=16,995, FITB questions=16,995
  valid: outfits=3,000, FITB questions=3,000
  test: outfits=15,145, FITB questions=15,145
item image features: 251,008
item text features: 251,008
category features: 251,008

In [5]:
# ------------------------------------------------------------
# 題目解析
# ------------------------------------------------------------
def build_ref_to_item(outfits: List[dict]) -> Dict[str, str]:
    ref_to_item = {}
    for outfit in outfits:
        set_id = as_key(outfit['set_id'])
        for item in outfit['items']:
            ref_to_item[f'{set_id}_{item["index"]}'] = as_key(item['item_id'])
    return ref_to_item


ref_to_item_by_split = {split: build_ref_to_item(outfits) for split, outfits in split_outfits.items()}


def parse_compatibility_examples(split: str, limit: Optional[int] = None) -> List[dict]:
    path = DISJOINT_DIR / f'compatibility_{split}.txt'
    ref_to_item = ref_to_item_by_split[split]
    examples = []
    skipped = 0
    with open(path, 'r', encoding='utf-8') as f:
        for line_idx, line in enumerate(f):
            parts = line.strip().split()
            if len(parts) < 2:
                skipped += 1
                continue
            label = int(parts[0])
            refs = parts[1:]
            set_id = as_key(refs[0].split('_')[0])
            try:
                item_ids = [ref_to_item[ref] for ref in refs]
            except KeyError:
                skipped += 1
                continue
            examples.append({
                'question_index': line_idx,
                'set_id': set_id,
                'item_ids': item_ids,
                'label': label,
            })
            if limit is not None and len(examples) >= limit:
                break
    print(f'compatibility {split}: parsed={len(examples):,}, skipped={skipped:,}')
    return examples


def parse_fitb_examples(split: str, limit: Optional[int] = None) -> List[dict]:
    ref_to_item = ref_to_item_by_split[split]
    examples = []
    skipped = 0
    for q_idx, row in enumerate(fitb_raw[split]):
        question_refs = row['question']
        answer_refs = row['answers']
        if not question_refs or not answer_refs:
            skipped += 1
            continue
        set_id = as_key(question_refs[0].split('_')[0])
        try:
            partial_ids = [ref_to_item[ref] for ref in question_refs]
            answer_ids = [ref_to_item[ref] for ref in answer_refs]
        except KeyError:
            skipped += 1
            continue
        correct_indices = [i for i, ref in enumerate(answer_refs) if as_key(ref.split('_')[0]) == set_id]
        if len(correct_indices) != 1:
            skipped += 1
            continue
        correct_idx = correct_indices[0]
        target_item_id = answer_ids[correct_idx]
        if target_item_id not in metadata:
            skipped += 1
            continue
        examples.append({
            'question_index': q_idx,
            'set_id': set_id,
            'blank_position': int(row.get('blank_position', -1)),
            'partial_item_ids': partial_ids,
            'answer_item_ids': answer_ids,
            'correct_index': correct_idx,
            'target_item_id': target_item_id,
            'target_fg': as_key(metadata[target_item_id]['category_id']),
            'target_semantic_category': as_key(metadata[target_item_id].get('semantic_category', '')),
        })
        if limit is not None and len(examples) >= limit:
            break
    print(f'FITB {split}: parsed={len(examples):,}, skipped={skipped:,}')
    return examples


compat_examples_by_split = {
    'train': parse_compatibility_examples('train', TRAIN_LIMIT),
    'valid': parse_compatibility_examples('valid', VALID_LIMIT),
    'test': parse_compatibility_examples('test', TEST_LIMIT),
}
fitb_examples_by_split = {
    'train': parse_fitb_examples('train', TRAIN_LIMIT),
    'valid': parse_fitb_examples('valid', VALID_LIMIT),
    'test': parse_fitb_examples('test', TEST_LIMIT),
}

compatibility train: parsed=33,990, skipped=0
compatibility valid: parsed=6,000, skipped=0
compatibility test: parsed=30,290, skipped=0
FITB train: parsed=16,995, skipped=0
FITB valid: parsed=3,000, skipped=0
FITB test: parsed=15,145, skipped=0

In [6]:
# ------------------------------------------------------------
# Feature 組合與 Dataset
# ------------------------------------------------------------
_item_vec_cache: Dict[str, np.ndarray] = {}


def get_item_vec(item_id: str) -> np.ndarray:
    item_id = as_key(item_id)
    if item_id not in _item_vec_cache:
        img = vector_to_float32(img_feats[item_id])
        txt = vector_to_float32(item_text_feats[item_id])
        _item_vec_cache[item_id] = np.concatenate([img, txt]).astype(np.float32)
    return _item_vec_cache[item_id]


def get_category_vec(item_id: str) -> np.ndarray:
    return vector_to_float32(category_feats[as_key(item_id)])


def pad_items(item_ids: List[str]) -> Tuple[np.ndarray, np.ndarray]:
    arr = np.zeros((MAX_ITEM_LEN, ITEM_DIM), dtype=np.float32)
    mask = np.zeros((MAX_ITEM_LEN,), dtype=np.float32)
    keep = item_ids[:MAX_ITEM_LEN]
    for i, item_id in enumerate(keep):
        arr[i] = get_item_vec(item_id)
        mask[i] = 1.0
    return arr, mask


class CPCompatibilityDataset(Dataset):
    def __init__(self, examples: List[dict], outfit_feats: Dict[str, np.ndarray]):
        self.examples = [ex for ex in examples if ex['set_id'] in outfit_feats]
        self.outfit_feats = outfit_feats

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, index: int):
        ex = self.examples[index]
        items, mask = pad_items(ex['item_ids'])
        outfit_text = vector_to_float32(self.outfit_feats[ex['set_id']])
        return {
            'items': torch.from_numpy(items),
            'mask': torch.from_numpy(mask),
            'outfit_text': torch.from_numpy(outfit_text),
            'label': torch.tensor(float(ex['label']), dtype=torch.float32),
        }


class ORFITBDataset(Dataset):
    def __init__(self, examples: List[dict], outfit_feats: Dict[str, np.ndarray]):
        self.examples = [ex for ex in examples if ex['set_id'] in outfit_feats]
        self.outfit_feats = outfit_feats

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, index: int):
        ex = self.examples[index]
        partial_items, partial_mask = pad_items(ex['partial_item_ids'])
        candidates = np.stack([get_item_vec(item_id) for item_id in ex['answer_item_ids']], axis=0).astype(np.float32)
        outfit_text = vector_to_float32(self.outfit_feats[ex['set_id']])
        category = get_category_vec(ex['target_item_id'])
        return {
            'partial_items': torch.from_numpy(partial_items),
            'partial_mask': torch.from_numpy(partial_mask),
            'outfit_text': torch.from_numpy(outfit_text),
            'category': torch.from_numpy(category),
            'candidates': torch.from_numpy(candidates),
            'label': torch.tensor(int(ex['correct_index']), dtype=torch.long),
        }


def describe_variant_coverage(variant_key: str, outfit_feats: Dict[str, np.ndarray]):
    print(f'\n[{variant_key}] outfit text embedding 筆數：{len(outfit_feats):,}')
    for split, examples in compat_examples_by_split.items():
        missing = sum(1 for ex in examples if ex['set_id'] not in outfit_feats)
        print(f'  CP {split}: usable={len(examples)-missing:,}, missing={missing:,}')
    for split, examples in fitb_examples_by_split.items():
        missing = sum(1 for ex in examples if ex['set_id'] not in outfit_feats)
        print(f'  FITB {split}: usable={len(examples)-missing:,}, missing={missing:,}')

In [7]:
# ------------------------------------------------------------
# 候選池建立：OR/CIR Recall@K
# ------------------------------------------------------------
def build_fg_to_unique_items(outfits: List[dict]) -> Dict[str, List[str]]:
    fg_to_items = defaultdict(list)
    seen_by_fg = defaultdict(set)
    for outfit in outfits:
        for item in outfit['items']:
            item_id = as_key(item['item_id'])
            if item_id not in metadata:
                continue
            fg = as_key(metadata[item_id]['category_id'])
            if item_id not in seen_by_fg[fg]:
                seen_by_fg[fg].add(item_id)
                fg_to_items[fg].append(item_id)
    return dict(fg_to_items)


def build_or_candidate_pools(min_candidates: int = 3000) -> Dict[str, List[str]]:
    test_fg = build_fg_to_unique_items(split_outfits['test'])
    train_fg = build_fg_to_unique_items(split_outfits['train'])
    pools = {}
    for fg, test_items in test_fg.items():
        seen = set()
        pool = []
        for item_id in test_items:
            if item_id not in seen:
                seen.add(item_id)
                pool.append(item_id)
                if len(pool) >= min_candidates:
                    break
        if len(pool) < min_candidates:
            for item_id in train_fg.get(fg, []):
                if item_id not in seen:
                    seen.add(item_id)
                    pool.append(item_id)
                    if len(pool) >= min_candidates:
                        break
        if len(pool) >= min_candidates:
            pools[fg] = pool[:min_candidates]
    print(f'OR/CIR 可評估子類別數：{len(pools):,} / test 子類別數：{len(test_fg):,}')
    return pools


candidate_pools = build_or_candidate_pools(MIN_CANDIDATES_PER_FG)
evaluable_test = [ex for ex in fitb_examples_by_split['test'] if ex['target_fg'] in candidate_pools]
print(f'測試集 FITB 題目：{len(fitb_examples_by_split["test"]):,}')
print(f'OR/CIR Recall 可評估 query-target pairs：{len(evaluable_test):,}')

OR/CIR 可評估子類別數：19 / test 子類別數：152
測試集 FITB 題目：15,145
OR/CIR Recall 可評估 query-target pairs：9,311

In [8]:
# ------------------------------------------------------------
# 模型定義
# ------------------------------------------------------------
class MLPEncoder(nn.Module):
    def __init__(self, input_dim: int, hidden_dim: int, embed_dim: int, dropout: float):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, embed_dim),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


def masked_mean(x: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
    mask = mask.unsqueeze(-1)
    denom = mask.sum(dim=1).clamp_min(1.0)
    return (x * mask).sum(dim=1) / denom


class CPCompatibilityModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.item_encoder = MLPEncoder(ITEM_DIM, HIDDEN_DIM, EMBED_DIM, DROPOUT)
        self.outfit_text_encoder = MLPEncoder(TEXT_DIM, HIDDEN_DIM, EMBED_DIM, DROPOUT)
        self.classifier = nn.Sequential(
            nn.Linear(EMBED_DIM * 2, HIDDEN_DIM),
            nn.GELU(),
            nn.Dropout(DROPOUT),
            nn.Linear(HIDDEN_DIM, 1),
        )

    def encode_outfit(self, items: torch.Tensor, mask: torch.Tensor, outfit_text: torch.Tensor) -> torch.Tensor:
        item_z = self.item_encoder(items)
        outfit_z = masked_mean(item_z, mask)
        text_z = self.outfit_text_encoder(outfit_text)
        return torch.cat([outfit_z, text_z], dim=-1)

    def forward(self, items: torch.Tensor, mask: torch.Tensor, outfit_text: torch.Tensor) -> torch.Tensor:
        z = self.encode_outfit(items, mask, outfit_text)
        return self.classifier(z).squeeze(-1)


class ORRetrievalModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.item_encoder = MLPEncoder(ITEM_DIM, HIDDEN_DIM, EMBED_DIM, DROPOUT)
        self.outfit_text_encoder = MLPEncoder(TEXT_DIM, HIDDEN_DIM, EMBED_DIM, DROPOUT)
        self.category_encoder = MLPEncoder(CATEGORY_DIM, HIDDEN_DIM, EMBED_DIM, DROPOUT)
        self.query_net = nn.Sequential(
            nn.Linear(EMBED_DIM * 3, HIDDEN_DIM),
            nn.LayerNorm(HIDDEN_DIM),
            nn.GELU(),
            nn.Dropout(DROPOUT),
            nn.Linear(HIDDEN_DIM, EMBED_DIM),
        )
        self.logit_scale = nn.Parameter(torch.tensor(math.log(10.0), dtype=torch.float32))

    def encode_query(self, partial_items: torch.Tensor, partial_mask: torch.Tensor, outfit_text: torch.Tensor, category: torch.Tensor) -> torch.Tensor:
        partial_item_z = self.item_encoder(partial_items)
        partial_z = masked_mean(partial_item_z, partial_mask)
        text_z = self.outfit_text_encoder(outfit_text)
        category_z = self.category_encoder(category)
        query = self.query_net(torch.cat([partial_z, text_z, category_z], dim=-1))
        return F.normalize(query, dim=-1)

    def encode_candidate(self, candidates: torch.Tensor) -> torch.Tensor:
        return F.normalize(self.item_encoder(candidates), dim=-1)

    def forward(self, partial_items: torch.Tensor, partial_mask: torch.Tensor, outfit_text: torch.Tensor, category: torch.Tensor, candidates: torch.Tensor) -> torch.Tensor:
        query = self.encode_query(partial_items, partial_mask, outfit_text, category)
        cand = self.encode_candidate(candidates)
        scale = self.logit_scale.exp().clamp(max=100.0)
        return torch.einsum('bd,bkd->bk', query, cand) * scale


def make_loader(dataset: Dataset, batch_size: int, shuffle: bool, seed: int) -> DataLoader:
    generator = torch.Generator()
    generator.manual_seed(seed)
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        generator=generator if shuffle else None,
    )

In [9]:
# ------------------------------------------------------------
# CP 訓練與評估
# ------------------------------------------------------------
def evaluate_cp_auc(model: CPCompatibilityModel, loader: DataLoader) -> float:
    model.eval()
    labels = []
    scores = []
    with torch.no_grad():
        for batch in loader:
            items = batch['items'].to(DEVICE).float()
            mask = batch['mask'].to(DEVICE).float()
            outfit_text = batch['outfit_text'].to(DEVICE).float()
            label = batch['label'].detach().cpu().numpy()
            logit = model(items, mask, outfit_text).detach().cpu().numpy()
            labels.extend(label.tolist())
            scores.extend(logit.tolist())
    return binary_auc(labels, scores)


def evaluate_cp_fitb(model: CPCompatibilityModel, examples: List[dict], outfit_feats: Dict[str, np.ndarray]) -> float:
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for ex in tqdm(examples, desc='CP FITB'):
            if ex['set_id'] not in outfit_feats:
                continue
            batch_items = []
            batch_mask = []
            for answer_id in ex['answer_item_ids']:
                items, mask = pad_items(ex['partial_item_ids'] + [answer_id])
                batch_items.append(items)
                batch_mask.append(mask)
            items_t = torch.from_numpy(np.stack(batch_items)).to(DEVICE).float()
            mask_t = torch.from_numpy(np.stack(batch_mask)).to(DEVICE).float()
            outfit_text = vector_to_float32(outfit_feats[ex['set_id']])
            outfit_text_t = torch.from_numpy(np.stack([outfit_text] * len(batch_items))).to(DEVICE).float()
            scores = model(items_t, mask_t, outfit_text_t)
            pred = int(torch.argmax(scores).item())
            correct += int(pred == ex['correct_index'])
            total += 1
    return correct / total if total else 0.0


def train_cp_one_seed(variant_key: str, outfit_feats: Dict[str, np.ndarray], seed: int) -> Tuple[Path, CPCompatibilityModel, dict]:
    set_seed(seed)
    model_dir = MODEL_ROOT / variant_key / f'seed_{seed}'
    model_dir.mkdir(parents=True, exist_ok=True)
    ckpt_path = model_dir / 'cp_best_model.pt'
    log_path = model_dir / 'cp_train_log.csv'

    if ckpt_path.exists() and not FORCE_RETRAIN:
        checkpoint = torch.load(ckpt_path, map_location=DEVICE)
        model = CPCompatibilityModel().to(DEVICE)
        model.load_state_dict(checkpoint['model_state_dict'])
        model.eval()
        return ckpt_path, model, checkpoint

    if log_path.exists():
        log_path.unlink()

    train_dataset = CPCompatibilityDataset(compat_examples_by_split['train'], outfit_feats)
    valid_dataset = CPCompatibilityDataset(compat_examples_by_split['valid'], outfit_feats)
    train_loader = make_loader(train_dataset, BATCH_SIZE, shuffle=True, seed=seed)
    valid_loader = make_loader(valid_dataset, BATCH_SIZE, shuffle=False, seed=seed)

    model = CPCompatibilityModel().to(DEVICE)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=2)

    best_fitb = -1.0
    best_epoch = -1
    log_fields = ['variant', 'seed', 'stage', 'epoch', 'train_loss', 'valid_auc', 'valid_fitb_acc', 'lr', 'seconds']
    start_all = time.time()

    print(f'\n[CP 訓練] variant={variant_key}, seed={seed}, train={len(train_dataset):,}, valid={len(valid_dataset):,}')
    for epoch in range(1, CP_EPOCHS + 1):
        model.train()
        loss_sum = 0.0
        total = 0
        epoch_start = time.time()
        for batch in tqdm(train_loader, desc=f'CP train {variant_key} seed={seed} epoch={epoch}'):
            items = batch['items'].to(DEVICE).float()
            mask = batch['mask'].to(DEVICE).float()
            outfit_text = batch['outfit_text'].to(DEVICE).float()
            label = batch['label'].to(DEVICE).float()

            optimizer.zero_grad(set_to_none=True)
            logit = model(items, mask, outfit_text)
            loss = F.binary_cross_entropy_with_logits(logit, label)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            batch_n = int(label.numel())
            loss_sum += float(loss.item()) * batch_n
            total += batch_n

        train_loss = loss_sum / total if total else 0.0
        valid_auc = evaluate_cp_auc(model, valid_loader)
        valid_fitb = evaluate_cp_fitb(model, fitb_examples_by_split['valid'], outfit_feats)
        scheduler.step(valid_fitb)
        lr_now = optimizer.param_groups[0]['lr']
        seconds = time.time() - epoch_start

        append_csv(log_path, {
            'variant': variant_key, 'seed': seed, 'stage': 'CP', 'epoch': epoch,
            'train_loss': f'{train_loss:.6f}', 'valid_auc': f'{valid_auc:.6f}',
            'valid_fitb_acc': f'{valid_fitb:.6f}',
            'lr': f'{lr_now:.8f}', 'seconds': f'{seconds:.2f}',
        }, log_fields)
        print(f'CP epoch={epoch:02d} loss={train_loss:.4f} valid_AUC={valid_auc:.4f} valid_FITB={valid_fitb:.4f} lr={lr_now:.2e}')

        if valid_fitb > best_fitb:
            best_fitb = valid_fitb
            best_epoch = epoch
            torch.save({
                'variant': variant_key,
                'seed': seed,
                'stage': 'CP',
                'epoch': epoch,
                'best_valid_fitb_acc': best_fitb,
                'valid_auc_at_best_fitb': valid_auc,
                'model_state_dict': model.state_dict(),
                'selection_rule': 'best checkpoint selected by validation FITB accuracy',
            }, ckpt_path)

    checkpoint = torch.load(ckpt_path, map_location=DEVICE)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()
    checkpoint['total_training_seconds'] = time.time() - start_all
    checkpoint['best_epoch'] = best_epoch
    return ckpt_path, model, checkpoint

In [10]:
# ------------------------------------------------------------
# OR 訓練與評估
# ------------------------------------------------------------
def evaluate_or_fitb(model: ORRetrievalModel, loader: DataLoader) -> float:
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for batch in loader:
            partial_items = batch['partial_items'].to(DEVICE).float()
            partial_mask = batch['partial_mask'].to(DEVICE).float()
            outfit_text = batch['outfit_text'].to(DEVICE).float()
            category = batch['category'].to(DEVICE).float()
            candidates = batch['candidates'].to(DEVICE).float()
            label = batch['label'].to(DEVICE)
            scores = model(partial_items, partial_mask, outfit_text, category, candidates)
            pred = torch.argmax(scores, dim=1)
            correct += int((pred == label).sum().item())
            total += int(label.numel())
    return correct / total if total else 0.0


def train_or_one_seed(variant_key: str, outfit_feats: Dict[str, np.ndarray], seed: int, cp_model: CPCompatibilityModel) -> Tuple[Path, ORRetrievalModel, dict]:
    set_seed(seed)
    model_dir = MODEL_ROOT / variant_key / f'seed_{seed}'
    model_dir.mkdir(parents=True, exist_ok=True)
    ckpt_path = model_dir / 'best_model.pt'
    log_path = model_dir / 'or_train_log.csv'

    if ckpt_path.exists() and not FORCE_RETRAIN:
        checkpoint = torch.load(ckpt_path, map_location=DEVICE)
        model = ORRetrievalModel().to(DEVICE)
        model.load_state_dict(checkpoint['model_state_dict'])
        model.eval()
        return ckpt_path, model, checkpoint

    if log_path.exists():
        log_path.unlink()

    train_dataset = ORFITBDataset(fitb_examples_by_split['train'], outfit_feats)
    valid_dataset = ORFITBDataset(fitb_examples_by_split['valid'], outfit_feats)
    train_loader = make_loader(train_dataset, BATCH_SIZE, shuffle=True, seed=seed)
    valid_loader = make_loader(valid_dataset, BATCH_SIZE, shuffle=False, seed=seed)

    model = ORRetrievalModel().to(DEVICE)
    model.item_encoder.load_state_dict(cp_model.item_encoder.state_dict())
    model.outfit_text_encoder.load_state_dict(cp_model.outfit_text_encoder.state_dict())

    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=2)

    best_fitb = -1.0
    best_epoch = -1
    log_fields = ['variant', 'seed', 'stage', 'epoch', 'train_loss', 'valid_fitb_acc', 'lr', 'seconds']
    start_all = time.time()

    print(f'\n[OR 訓練] variant={variant_key}, seed={seed}, train={len(train_dataset):,}, valid={len(valid_dataset):,}')
    for epoch in range(1, OR_EPOCHS + 1):
        model.train()
        loss_sum = 0.0
        total = 0
        epoch_start = time.time()
        for batch in tqdm(train_loader, desc=f'OR train {variant_key} seed={seed} epoch={epoch}'):
            partial_items = batch['partial_items'].to(DEVICE).float()
            partial_mask = batch['partial_mask'].to(DEVICE).float()
            outfit_text = batch['outfit_text'].to(DEVICE).float()
            category = batch['category'].to(DEVICE).float()
            candidates = batch['candidates'].to(DEVICE).float()
            label = batch['label'].to(DEVICE)

            optimizer.zero_grad(set_to_none=True)
            scores = model(partial_items, partial_mask, outfit_text, category, candidates)
            loss = F.cross_entropy(scores, label)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            batch_n = int(label.numel())
            loss_sum += float(loss.item()) * batch_n
            total += batch_n

        train_loss = loss_sum / total if total else 0.0
        valid_fitb = evaluate_or_fitb(model, valid_loader)
        scheduler.step(valid_fitb)
        lr_now = optimizer.param_groups[0]['lr']
        seconds = time.time() - epoch_start

        append_csv(log_path, {
            'variant': variant_key, 'seed': seed, 'stage': 'OR', 'epoch': epoch,
            'train_loss': f'{train_loss:.6f}', 'valid_fitb_acc': f'{valid_fitb:.6f}',
            'lr': f'{lr_now:.8f}', 'seconds': f'{seconds:.2f}',
        }, log_fields)
        print(f'OR epoch={epoch:02d} loss={train_loss:.4f} valid_FITB={valid_fitb:.4f} lr={lr_now:.2e}')

        if valid_fitb > best_fitb:
            best_fitb = valid_fitb
            best_epoch = epoch
            torch.save({
                'variant': variant_key,
                'seed': seed,
                'stage': 'OR',
                'epoch': epoch,
                'best_valid_fitb_acc': best_fitb,
                'model_state_dict': model.state_dict(),
                'selection_rule': 'best checkpoint selected by validation FITB accuracy',
                'transfer_note': 'item_encoder and outfit_text_encoder initialized from CP model',
            }, ckpt_path)

    checkpoint = torch.load(ckpt_path, map_location=DEVICE)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()
    checkpoint['total_training_seconds'] = time.time() - start_all
    checkpoint['best_epoch'] = best_epoch
    return ckpt_path, model, checkpoint

In [11]:
# ------------------------------------------------------------
# OR/CIR Recall@K 測試
# ------------------------------------------------------------
def encode_candidates(model: ORRetrievalModel, item_ids: List[str], batch_size: int = 1024) -> torch.Tensor:
    encoded_batches = []
    model.eval()
    with torch.no_grad():
        for start in range(0, len(item_ids), batch_size):
            batch_ids = item_ids[start:start + batch_size]
            raw = np.stack([get_item_vec(item_id) for item_id in batch_ids], axis=0).astype(np.float32)
            raw_t = torch.from_numpy(raw).to(DEVICE).float()
            encoded_batches.append(model.encode_candidate(raw_t))
    return torch.cat(encoded_batches, dim=0)


def encode_one_query(model: ORRetrievalModel, ex: dict, outfit_feats: Dict[str, np.ndarray]) -> torch.Tensor:
    partial_items, partial_mask = pad_items(ex['partial_item_ids'])
    outfit_text = vector_to_float32(outfit_feats[ex['set_id']])
    category = get_category_vec(ex['target_item_id'])
    with torch.no_grad():
        return model.encode_query(
            torch.from_numpy(partial_items).unsqueeze(0).to(DEVICE).float(),
            torch.from_numpy(partial_mask).unsqueeze(0).to(DEVICE).float(),
            torch.from_numpy(outfit_text).unsqueeze(0).to(DEVICE).float(),
            torch.from_numpy(category).unsqueeze(0).to(DEVICE).float(),
        ).squeeze(0)


def evaluate_or_recall(model: ORRetrievalModel, outfit_feats: Dict[str, np.ndarray], variant_key: str, seed: int) -> Tuple[dict, List[dict]]:
    model.eval()
    pool_emb_cache = {}
    pool_id_cache = {}
    for fg, ids in tqdm(candidate_pools.items(), desc=f'encode candidate pools [{variant_key} seed={seed}]'):
        pool_id_cache[fg] = list(ids)
        pool_emb_cache[fg] = encode_candidates(model, ids)

    target_emb_cache: Dict[str, torch.Tensor] = {}
    rows = []
    hits = {k: 0 for k in K_LIST}
    ranks = []
    skipped = 0

    for ex in tqdm(fitb_examples_by_split['test'], desc=f'OR/CIR recall [{variant_key} seed={seed}]'):
        if ex['set_id'] not in outfit_feats:
            skipped += 1
            continue
        fg = ex['target_fg']
        target_item_id = ex['target_item_id']
        if fg not in candidate_pools:
            skipped += 1
            continue

        ids = list(pool_id_cache[fg])
        cand_z = pool_emb_cache[fg]
        if target_item_id in ids:
            target_pos = ids.index(target_item_id)
        else:
            ids = ids[:-1] + [target_item_id]
            if target_item_id not in target_emb_cache:
                target_emb_cache[target_item_id] = encode_candidates(model, [target_item_id])
            cand_z = torch.cat([cand_z[:-1], target_emb_cache[target_item_id]], dim=0)
            target_pos = len(ids) - 1

        q_z = encode_one_query(model, ex, outfit_feats)
        scores = torch.matmul(cand_z, q_z)
        target_score = scores[target_pos]
        rank = int((scores > target_score).sum().item()) + 1
        ranks.append(rank)

        top_k = min(max(K_LIST), len(ids))
        _, top_idx = torch.topk(scores, k=top_k, largest=True)
        top_ids = [ids[int(i)] for i in top_idx.detach().cpu().tolist()]

        row = {
            'variant': variant_key,
            'seed': seed,
            'question_index': ex['question_index'],
            'set_id': ex['set_id'],
            'target_item_id': target_item_id,
            'target_fg': fg,
            'target_semantic_category': ex['target_semantic_category'],
            'rank': rank,
            'partial_item_ids': json.dumps(ex['partial_item_ids'], ensure_ascii=False),
            'answer_item_ids': json.dumps(ex['answer_item_ids'], ensure_ascii=False),
            'top10_ids': json.dumps(top_ids[:10], ensure_ascii=False),
        }
        for k in K_LIST:
            hit = int(rank <= k)
            hits[k] += hit
            row[f'recall@{k}'] = hit
        rows.append(row)

    n = len(rows)
    summary = {
        'variant': variant_key,
        'seed': seed,
        'test_fitb_questions': len(fitb_examples_by_split['test']),
        'or_recall_evaluable_pairs': n,
        'or_recall_skipped_questions': skipped,
        'mean_rank': float(np.mean(ranks)) if ranks else float('nan'),
        'median_rank': float(np.median(ranks)) if ranks else float('nan'),
    }
    for k in K_LIST:
        summary[f'recall@{k}'] = hits[k] / n if n else 0.0
    return summary, rows

In [12]:
# ------------------------------------------------------------
# 執行完整 CP→OR 流程
# ------------------------------------------------------------
def clean_seed_outputs(variant_key: str, seed: int):
    model_dir = MODEL_ROOT / variant_key / f'seed_{seed}'
    result_dir = RESULT_ROOT / variant_key / f'seed_{seed}'
    if FORCE_RETRAIN:
        for path in [
            model_dir / 'train_log.csv',
            model_dir / 'cp_train_log.csv',
            model_dir / 'or_train_log.csv',
            model_dir / 'config.json',
            model_dir / 'best_model.pt',
            model_dir / 'cp_best_model.pt',
            result_dir / 'seed_summary.csv',
            result_dir / 'or_recall_rowlevel.csv',
        ]:
            if path.exists():
                path.unlink()


all_seed_rows = []
all_or_rows = []

for variant_key, feature_file in TEXT_VARIANTS.items():
    outfit_feats = load_pickle(FASHIONCLIP_DIR / feature_file)
    describe_variant_coverage(variant_key, outfit_feats)

    for seed in SEEDS:
        clean_seed_outputs(variant_key, seed)
        model_dir = MODEL_ROOT / variant_key / f'seed_{seed}'
        result_dir = RESULT_ROOT / variant_key / f'seed_{seed}'
        model_dir.mkdir(parents=True, exist_ok=True)
        result_dir.mkdir(parents=True, exist_ok=True)

        cp_ckpt_path, cp_model, cp_checkpoint = train_cp_one_seed(variant_key, outfit_feats, seed)

        cp_test_dataset = CPCompatibilityDataset(compat_examples_by_split['test'], outfit_feats)
        cp_test_loader = make_loader(cp_test_dataset, BATCH_SIZE, shuffle=False, seed=seed)
        cp_test_auc = evaluate_cp_auc(cp_model, cp_test_loader)
        cp_test_fitb = evaluate_cp_fitb(cp_model, fitb_examples_by_split['test'], outfit_feats)

        or_ckpt_path, or_model, or_checkpoint = train_or_one_seed(variant_key, outfit_feats, seed, cp_model)

        or_test_dataset = ORFITBDataset(fitb_examples_by_split['test'], outfit_feats)
        or_test_loader = make_loader(or_test_dataset, BATCH_SIZE, shuffle=False, seed=seed)
        or_test_fitb = evaluate_or_fitb(or_model, or_test_loader)

        or_summary, or_rows = evaluate_or_recall(or_model, outfit_feats, variant_key, seed)
        seed_summary = {
            'variant': variant_key,
            'seed': seed,
            'cp_best_epoch': int(cp_checkpoint.get('epoch', cp_checkpoint.get('best_epoch', -1))),
            'cp_best_valid_fitb_acc': float(cp_checkpoint.get('best_valid_fitb_acc', float('nan'))),
            'cp_valid_auc_at_best_fitb': float(cp_checkpoint.get('valid_auc_at_best_fitb', float('nan'))),
            'cp_test_auc': float(cp_test_auc),
            'cp_test_fitb_acc': float(cp_test_fitb),
            'or_best_epoch': int(or_checkpoint.get('epoch', or_checkpoint.get('best_epoch', -1))),
            'or_best_valid_fitb_acc': float(or_checkpoint.get('best_valid_fitb_acc', float('nan'))),
            'or_test_fitb_acc': float(or_test_fitb),
            'cp_checkpoint': str(cp_ckpt_path),
            'or_checkpoint': str(or_ckpt_path),
        }
        seed_summary.update(or_summary)
        all_seed_rows.append(seed_summary)
        all_or_rows.extend(or_rows)

        write_csv(result_dir / 'seed_summary.csv', [seed_summary])
        write_csv(result_dir / 'or_recall_rowlevel.csv', or_rows)

        config = {
            'variant': variant_key,
            'seed': seed,
            'pipeline': 'CP binary compatibility pretraining -> OR retrieval fine-tuning',
            'checkpoint_selection': 'CP and OR checkpoints selected by validation FITB accuracy; train up to 100 epochs without early stopping',
            'cp_checkpoint': str(cp_ckpt_path),
            'or_checkpoint': str(or_ckpt_path),
            'text_feature_file': feature_file,
            'splits': {
                'train': 'PO-D train',
                'valid': 'PO-D valid',
                'test': 'PO-D test',
            },
            'seed_summary': seed_summary,
        }
        (model_dir / 'config.json').write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding='utf-8')

seed_summary_path = RESULT_ROOT / 'A30_second_model_two_tower_seed_summary.csv'
rowlevel_path = RESULT_ROOT / 'A31_second_model_two_tower_or_rowlevel.csv'
write_csv(seed_summary_path, all_seed_rows)
write_csv(rowlevel_path, all_or_rows)

print('\n[完成] CP→OR seed-level summary')
for row in all_seed_rows:
    print(json.dumps(row, ensure_ascii=False, indent=2))

[original_text] outfit text embedding 筆數：68,306
  CP train: usable=33,990, missing=0
  CP valid: usable=6,000, missing=0
  CP test: usable=30,290, missing=0
  FITB train: usable=16,995, missing=0
  FITB valid: usable=3,000, missing=0
  FITB test: usable=15,145, missing=0

[CP 訓練] variant=original_text, seed=1, train=33,990, valid=6,000

CP train original_text seed=1 epoch=1:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=01 loss=0.6526 valid_AUC=0.8040 valid_FITB=0.4137 lr=1.00e-03

CP train original_text seed=1 epoch=2:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=02 loss=0.5238 valid_AUC=0.8554 valid_FITB=0.4887 lr=1.00e-03

CP train original_text seed=1 epoch=3:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=03 loss=0.4612 valid_AUC=0.8678 valid_FITB=0.4940 lr=1.00e-03

CP train original_text seed=1 epoch=4:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=04 loss=0.4181 valid_AUC=0.8785 valid_FITB=0.5267 lr=1.00e-03

CP train original_text seed=1 epoch=5:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=05 loss=0.3762 valid_AUC=0.8884 valid_FITB=0.5480 lr=1.00e-03

CP train original_text seed=1 epoch=6:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=06 loss=0.3305 valid_AUC=0.8969 valid_FITB=0.5573 lr=1.00e-03

CP train original_text seed=1 epoch=7:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=07 loss=0.2989 valid_AUC=0.9043 valid_FITB=0.5700 lr=1.00e-03

CP train original_text seed=1 epoch=8:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=08 loss=0.2613 valid_AUC=0.9071 valid_FITB=0.5687 lr=1.00e-03

CP train original_text seed=1 epoch=9:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=09 loss=0.2255 valid_AUC=0.8981 valid_FITB=0.5713 lr=1.00e-03

CP train original_text seed=1 epoch=10:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=10 loss=0.1998 valid_AUC=0.9049 valid_FITB=0.5690 lr=1.00e-03

CP train original_text seed=1 epoch=11:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=11 loss=0.1711 valid_AUC=0.9104 valid_FITB=0.5700 lr=1.00e-03

CP train original_text seed=1 epoch=12:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=12 loss=0.1523 valid_AUC=0.8982 valid_FITB=0.5657 lr=5.00e-04

CP train original_text seed=1 epoch=13:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=13 loss=0.0960 valid_AUC=0.9130 valid_FITB=0.5807 lr=5.00e-04

CP train original_text seed=1 epoch=14:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=14 loss=0.0695 valid_AUC=0.9098 valid_FITB=0.5770 lr=5.00e-04

CP train original_text seed=1 epoch=15:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=15 loss=0.0595 valid_AUC=0.9091 valid_FITB=0.5760 lr=5.00e-04

CP train original_text seed=1 epoch=16:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=16 loss=0.0493 valid_AUC=0.9113 valid_FITB=0.5710 lr=2.50e-04

CP train original_text seed=1 epoch=17:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=17 loss=0.0308 valid_AUC=0.9113 valid_FITB=0.5777 lr=2.50e-04

CP train original_text seed=1 epoch=18:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=18 loss=0.0236 valid_AUC=0.9125 valid_FITB=0.5727 lr=2.50e-04

CP train original_text seed=1 epoch=19:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=19 loss=0.0205 valid_AUC=0.9116 valid_FITB=0.5790 lr=1.25e-04

CP train original_text seed=1 epoch=20:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=20 loss=0.0154 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.25e-04

CP train original_text seed=1 epoch=21:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=21 loss=0.0128 valid_AUC=0.9118 valid_FITB=0.5790 lr=1.25e-04

CP train original_text seed=1 epoch=22:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=22 loss=0.0127 valid_AUC=0.9127 valid_FITB=0.5787 lr=6.25e-05

CP train original_text seed=1 epoch=23:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=23 loss=0.0109 valid_AUC=0.9131 valid_FITB=0.5803 lr=6.25e-05

CP train original_text seed=1 epoch=24:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=24 loss=0.0103 valid_AUC=0.9130 valid_FITB=0.5767 lr=6.25e-05

CP train original_text seed=1 epoch=25:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=25 loss=0.0094 valid_AUC=0.9129 valid_FITB=0.5790 lr=3.13e-05

CP train original_text seed=1 epoch=26:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=26 loss=0.0091 valid_AUC=0.9129 valid_FITB=0.5780 lr=3.13e-05

CP train original_text seed=1 epoch=27:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=27 loss=0.0087 valid_AUC=0.9128 valid_FITB=0.5793 lr=3.13e-05

CP train original_text seed=1 epoch=28:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=28 loss=0.0078 valid_AUC=0.9130 valid_FITB=0.5807 lr=1.56e-05

CP train original_text seed=1 epoch=29:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=29 loss=0.0080 valid_AUC=0.9129 valid_FITB=0.5780 lr=1.56e-05

CP train original_text seed=1 epoch=30:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=30 loss=0.0077 valid_AUC=0.9128 valid_FITB=0.5800 lr=1.56e-05

CP train original_text seed=1 epoch=31:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=31 loss=0.0079 valid_AUC=0.9129 valid_FITB=0.5793 lr=7.81e-06

CP train original_text seed=1 epoch=32:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=32 loss=0.0078 valid_AUC=0.9128 valid_FITB=0.5787 lr=7.81e-06

CP train original_text seed=1 epoch=33:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=33 loss=0.0076 valid_AUC=0.9129 valid_FITB=0.5773 lr=7.81e-06

CP train original_text seed=1 epoch=34:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=34 loss=0.0073 valid_AUC=0.9128 valid_FITB=0.5773 lr=3.91e-06

CP train original_text seed=1 epoch=35:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=35 loss=0.0077 valid_AUC=0.9129 valid_FITB=0.5773 lr=3.91e-06

CP train original_text seed=1 epoch=36:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=36 loss=0.0067 valid_AUC=0.9129 valid_FITB=0.5777 lr=3.91e-06

CP train original_text seed=1 epoch=37:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=37 loss=0.0076 valid_AUC=0.9130 valid_FITB=0.5793 lr=1.95e-06

CP train original_text seed=1 epoch=38:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=38 loss=0.0072 valid_AUC=0.9130 valid_FITB=0.5783 lr=1.95e-06

CP train original_text seed=1 epoch=39:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=39 loss=0.0077 valid_AUC=0.9129 valid_FITB=0.5787 lr=1.95e-06

CP train original_text seed=1 epoch=40:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=40 loss=0.0075 valid_AUC=0.9130 valid_FITB=0.5770 lr=9.77e-07

CP train original_text seed=1 epoch=41:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=41 loss=0.0073 valid_AUC=0.9130 valid_FITB=0.5767 lr=9.77e-07

CP train original_text seed=1 epoch=42:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=42 loss=0.0076 valid_AUC=0.9129 valid_FITB=0.5770 lr=9.77e-07

CP train original_text seed=1 epoch=43:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=43 loss=0.0071 valid_AUC=0.9129 valid_FITB=0.5767 lr=4.88e-07

CP train original_text seed=1 epoch=44:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=44 loss=0.0075 valid_AUC=0.9129 valid_FITB=0.5770 lr=4.88e-07

CP train original_text seed=1 epoch=45:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=45 loss=0.0069 valid_AUC=0.9129 valid_FITB=0.5767 lr=4.88e-07

CP train original_text seed=1 epoch=46:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=46 loss=0.0072 valid_AUC=0.9129 valid_FITB=0.5763 lr=2.44e-07

CP train original_text seed=1 epoch=47:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=47 loss=0.0073 valid_AUC=0.9129 valid_FITB=0.5763 lr=2.44e-07

CP train original_text seed=1 epoch=48:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=48 loss=0.0069 valid_AUC=0.9129 valid_FITB=0.5760 lr=2.44e-07

CP train original_text seed=1 epoch=49:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=49 loss=0.0072 valid_AUC=0.9129 valid_FITB=0.5767 lr=1.22e-07

CP train original_text seed=1 epoch=50:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=50 loss=0.0070 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.22e-07

CP train original_text seed=1 epoch=51:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=51 loss=0.0072 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.22e-07

CP train original_text seed=1 epoch=52:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=52 loss=0.0073 valid_AUC=0.9129 valid_FITB=0.5763 lr=6.10e-08

CP train original_text seed=1 epoch=53:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=53 loss=0.0068 valid_AUC=0.9129 valid_FITB=0.5760 lr=6.10e-08

CP train original_text seed=1 epoch=54:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=54 loss=0.0069 valid_AUC=0.9129 valid_FITB=0.5763 lr=6.10e-08

CP train original_text seed=1 epoch=55:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=55 loss=0.0066 valid_AUC=0.9129 valid_FITB=0.5760 lr=3.05e-08

CP train original_text seed=1 epoch=56:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=56 loss=0.0073 valid_AUC=0.9129 valid_FITB=0.5763 lr=3.05e-08

CP train original_text seed=1 epoch=57:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=57 loss=0.0073 valid_AUC=0.9129 valid_FITB=0.5760 lr=3.05e-08

CP train original_text seed=1 epoch=58:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=58 loss=0.0070 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=59:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=59 loss=0.0078 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=60:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=60 loss=0.0069 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=61:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=61 loss=0.0066 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=62:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=62 loss=0.0069 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=63:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=63 loss=0.0069 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=64:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=64 loss=0.0074 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=65:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=65 loss=0.0071 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=66:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=66 loss=0.0068 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=67:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=67 loss=0.0071 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=68:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=68 loss=0.0069 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=69:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=69 loss=0.0071 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=70:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=70 loss=0.0073 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=71:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=71 loss=0.0068 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=72:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=72 loss=0.0070 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=73:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=73 loss=0.0073 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=74:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=74 loss=0.0066 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=75:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=75 loss=0.0066 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=76:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=76 loss=0.0076 valid_AUC=0.9129 valid_FITB=0.5760 lr=1.53e-08

CP train original_text seed=1 epoch=77:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=77 loss=0.0071 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=78:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=78 loss=0.0066 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=79:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=79 loss=0.0075 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=80:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=80 loss=0.0072 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=81:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=81 loss=0.0067 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=82:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=82 loss=0.0069 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=83:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=83 loss=0.0073 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=84:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=84 loss=0.0067 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=85:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=85 loss=0.0073 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=86:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=86 loss=0.0067 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=87:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=87 loss=0.0067 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=88:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=88 loss=0.0076 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=89:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=89 loss=0.0070 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=90:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=90 loss=0.0069 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=91:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=91 loss=0.0073 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=92:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=92 loss=0.0067 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=93:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=93 loss=0.0067 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=94:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=94 loss=0.0069 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=95:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=95 loss=0.0076 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=96:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=96 loss=0.0072 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=97:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=97 loss=0.0069 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=98:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=98 loss=0.0072 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=99:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=99 loss=0.0070 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP train original_text seed=1 epoch=100:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=100 loss=0.0067 valid_AUC=0.9129 valid_FITB=0.5763 lr=1.53e-08

CP FITB:   0%|          | 0/15145 [00:00<?, ?it/s]

[OR 訓練] variant=original_text, seed=1, train=16,995, valid=3,000

OR train original_text seed=1 epoch=1:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=01 loss=0.9556 valid_FITB=0.6157 lr=1.00e-03

OR train original_text seed=1 epoch=2:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=02 loss=0.8152 valid_FITB=0.6093 lr=1.00e-03

OR train original_text seed=1 epoch=3:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=03 loss=0.7144 valid_FITB=0.6087 lr=1.00e-03

OR train original_text seed=1 epoch=4:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=04 loss=0.6178 valid_FITB=0.6080 lr=5.00e-04

OR train original_text seed=1 epoch=5:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=05 loss=0.4613 valid_FITB=0.6030 lr=5.00e-04

OR train original_text seed=1 epoch=6:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=06 loss=0.3826 valid_FITB=0.5987 lr=5.00e-04

OR train original_text seed=1 epoch=7:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=07 loss=0.3155 valid_FITB=0.5953 lr=2.50e-04

OR train original_text seed=1 epoch=8:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=08 loss=0.2448 valid_FITB=0.5943 lr=2.50e-04

OR train original_text seed=1 epoch=9:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=09 loss=0.2099 valid_FITB=0.5967 lr=2.50e-04

OR train original_text seed=1 epoch=10:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=10 loss=0.1844 valid_FITB=0.5900 lr=1.25e-04

OR train original_text seed=1 epoch=11:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=11 loss=0.1598 valid_FITB=0.5887 lr=1.25e-04

OR train original_text seed=1 epoch=12:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=12 loss=0.1502 valid_FITB=0.5853 lr=1.25e-04

OR train original_text seed=1 epoch=13:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=13 loss=0.1389 valid_FITB=0.5903 lr=6.25e-05

OR train original_text seed=1 epoch=14:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=14 loss=0.1266 valid_FITB=0.5860 lr=6.25e-05

OR train original_text seed=1 epoch=15:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=15 loss=0.1256 valid_FITB=0.5870 lr=6.25e-05

OR train original_text seed=1 epoch=16:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=16 loss=0.1204 valid_FITB=0.5840 lr=3.13e-05

OR train original_text seed=1 epoch=17:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=17 loss=0.1143 valid_FITB=0.5830 lr=3.13e-05

OR train original_text seed=1 epoch=18:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=18 loss=0.1130 valid_FITB=0.5823 lr=3.13e-05

OR train original_text seed=1 epoch=19:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=19 loss=0.1118 valid_FITB=0.5857 lr=1.56e-05

OR train original_text seed=1 epoch=20:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=20 loss=0.1081 valid_FITB=0.5837 lr=1.56e-05

OR train original_text seed=1 epoch=21:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=21 loss=0.1085 valid_FITB=0.5820 lr=1.56e-05

OR train original_text seed=1 epoch=22:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=22 loss=0.1071 valid_FITB=0.5820 lr=7.81e-06

OR train original_text seed=1 epoch=23:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=23 loss=0.1050 valid_FITB=0.5827 lr=7.81e-06

OR train original_text seed=1 epoch=24:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=24 loss=0.1053 valid_FITB=0.5820 lr=7.81e-06

OR train original_text seed=1 epoch=25:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=25 loss=0.1036 valid_FITB=0.5840 lr=3.91e-06

OR train original_text seed=1 epoch=26:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=26 loss=0.1038 valid_FITB=0.5820 lr=3.91e-06

OR train original_text seed=1 epoch=27:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=27 loss=0.1028 valid_FITB=0.5813 lr=3.91e-06

OR train original_text seed=1 epoch=28:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=28 loss=0.1030 valid_FITB=0.5813 lr=1.95e-06

OR train original_text seed=1 epoch=29:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=29 loss=0.1023 valid_FITB=0.5820 lr=1.95e-06

OR train original_text seed=1 epoch=30:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=30 loss=0.1024 valid_FITB=0.5820 lr=1.95e-06

OR train original_text seed=1 epoch=31:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=31 loss=0.1013 valid_FITB=0.5817 lr=9.77e-07

OR train original_text seed=1 epoch=32:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=32 loss=0.1004 valid_FITB=0.5817 lr=9.77e-07

OR train original_text seed=1 epoch=33:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=33 loss=0.0999 valid_FITB=0.5810 lr=9.77e-07

OR train original_text seed=1 epoch=34:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=34 loss=0.1027 valid_FITB=0.5817 lr=4.88e-07

OR train original_text seed=1 epoch=35:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=35 loss=0.1015 valid_FITB=0.5810 lr=4.88e-07

OR train original_text seed=1 epoch=36:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=36 loss=0.1029 valid_FITB=0.5817 lr=4.88e-07

OR train original_text seed=1 epoch=37:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=37 loss=0.1032 valid_FITB=0.5817 lr=2.44e-07

OR train original_text seed=1 epoch=38:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=38 loss=0.1032 valid_FITB=0.5813 lr=2.44e-07

OR train original_text seed=1 epoch=39:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=39 loss=0.1017 valid_FITB=0.5813 lr=2.44e-07

OR train original_text seed=1 epoch=40:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=40 loss=0.1014 valid_FITB=0.5817 lr=1.22e-07

OR train original_text seed=1 epoch=41:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=41 loss=0.1011 valid_FITB=0.5813 lr=1.22e-07

OR train original_text seed=1 epoch=42:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=42 loss=0.1038 valid_FITB=0.5813 lr=1.22e-07

OR train original_text seed=1 epoch=43:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=43 loss=0.1018 valid_FITB=0.5813 lr=6.10e-08

OR train original_text seed=1 epoch=44:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=44 loss=0.1019 valid_FITB=0.5813 lr=6.10e-08

OR train original_text seed=1 epoch=45:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=45 loss=0.1039 valid_FITB=0.5813 lr=6.10e-08

OR train original_text seed=1 epoch=46:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=46 loss=0.1000 valid_FITB=0.5813 lr=3.05e-08

OR train original_text seed=1 epoch=47:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=47 loss=0.1023 valid_FITB=0.5813 lr=3.05e-08

OR train original_text seed=1 epoch=48:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=48 loss=0.1029 valid_FITB=0.5813 lr=3.05e-08

OR train original_text seed=1 epoch=49:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=49 loss=0.1024 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=50:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=50 loss=0.1013 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=51:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=51 loss=0.1019 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=52:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=52 loss=0.1040 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=53:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=53 loss=0.1022 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=54:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=54 loss=0.1020 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=55:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=55 loss=0.1008 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=56:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=56 loss=0.1031 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=57:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=57 loss=0.1032 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=58:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=58 loss=0.1014 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=59:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=59 loss=0.1022 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=60:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=60 loss=0.1014 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=61:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=61 loss=0.1021 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=62:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=62 loss=0.1030 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=63:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=63 loss=0.1032 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=64:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=64 loss=0.1008 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=65:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=65 loss=0.1024 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=66:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=66 loss=0.1006 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=67:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=67 loss=0.1017 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=68:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=68 loss=0.1016 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=69:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=69 loss=0.1015 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=70:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=70 loss=0.1036 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=71:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=71 loss=0.1000 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=72:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=72 loss=0.0996 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=73:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=73 loss=0.1009 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=74:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=74 loss=0.1031 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=75:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=75 loss=0.1034 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=76:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=76 loss=0.1028 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=77:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=77 loss=0.1008 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=78:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=78 loss=0.1013 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=79:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=79 loss=0.1008 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=80:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=80 loss=0.1036 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=81:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=81 loss=0.1003 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=82:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=82 loss=0.1035 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=83:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=83 loss=0.1011 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=84:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=84 loss=0.1013 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=85:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=85 loss=0.1000 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=86:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=86 loss=0.1031 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=87:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=87 loss=0.1036 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=88:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=88 loss=0.1020 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=89:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=89 loss=0.1009 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=90:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=90 loss=0.1020 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=91:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=91 loss=0.1023 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=92:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=92 loss=0.1012 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=93:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=93 loss=0.1017 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=94:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=94 loss=0.1014 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=95:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=95 loss=0.1035 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=96:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=96 loss=0.1031 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=97:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=97 loss=0.1006 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=98:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=98 loss=0.1026 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=99:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=99 loss=0.1027 valid_FITB=0.5813 lr=1.53e-08

OR train original_text seed=1 epoch=100:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=100 loss=0.1027 valid_FITB=0.5813 lr=1.53e-08

encode candidate pools [original_text seed=1]:   0%|          | 0/19 [00:00<?, ?it/s]

OR/CIR recall [original_text seed=1]:   0%|          | 0/15145 [00:00<?, ?it/s]

[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/original_text/seed_1/seed_summary.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/original_text/seed_1/or_recall_rowlevel.csv

[CP 訓練] variant=original_text, seed=2, train=33,990, valid=6,000

CP train original_text seed=2 epoch=1:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=01 loss=0.6540 valid_AUC=0.7818 valid_FITB=0.4480 lr=1.00e-03

CP train original_text seed=2 epoch=2:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=02 loss=0.5115 valid_AUC=0.8629 valid_FITB=0.4853 lr=1.00e-03

CP train original_text seed=2 epoch=3:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=03 loss=0.4383 valid_AUC=0.8766 valid_FITB=0.5050 lr=1.00e-03

CP train original_text seed=2 epoch=4:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=04 loss=0.3964 valid_AUC=0.8862 valid_FITB=0.5280 lr=1.00e-03

CP train original_text seed=2 epoch=5:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=05 loss=0.3544 valid_AUC=0.8942 valid_FITB=0.5417 lr=1.00e-03

CP train original_text seed=2 epoch=6:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=06 loss=0.3083 valid_AUC=0.9077 valid_FITB=0.5590 lr=1.00e-03

CP train original_text seed=2 epoch=7:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=07 loss=0.2728 valid_AUC=0.9046 valid_FITB=0.5570 lr=1.00e-03

CP train original_text seed=2 epoch=8:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=08 loss=0.2486 valid_AUC=0.9079 valid_FITB=0.5647 lr=1.00e-03

CP train original_text seed=2 epoch=9:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=09 loss=0.2156 valid_AUC=0.9097 valid_FITB=0.5643 lr=1.00e-03

CP train original_text seed=2 epoch=10:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=10 loss=0.1919 valid_AUC=0.9065 valid_FITB=0.5627 lr=1.00e-03

CP train original_text seed=2 epoch=11:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=11 loss=0.1634 valid_AUC=0.9083 valid_FITB=0.5630 lr=5.00e-04

CP train original_text seed=2 epoch=12:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=12 loss=0.1036 valid_AUC=0.9138 valid_FITB=0.5773 lr=5.00e-04

CP train original_text seed=2 epoch=13:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=13 loss=0.0751 valid_AUC=0.9118 valid_FITB=0.5663 lr=5.00e-04

CP train original_text seed=2 epoch=14:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=14 loss=0.0626 valid_AUC=0.9112 valid_FITB=0.5743 lr=5.00e-04

CP train original_text seed=2 epoch=15:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=15 loss=0.0550 valid_AUC=0.9105 valid_FITB=0.5700 lr=2.50e-04

CP train original_text seed=2 epoch=16:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=16 loss=0.0345 valid_AUC=0.9152 valid_FITB=0.5737 lr=2.50e-04

CP train original_text seed=2 epoch=17:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=17 loss=0.0271 valid_AUC=0.9137 valid_FITB=0.5733 lr=2.50e-04

CP train original_text seed=2 epoch=18:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=18 loss=0.0222 valid_AUC=0.9148 valid_FITB=0.5750 lr=1.25e-04

CP train original_text seed=2 epoch=19:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=19 loss=0.0166 valid_AUC=0.9145 valid_FITB=0.5753 lr=1.25e-04

CP train original_text seed=2 epoch=20:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=20 loss=0.0140 valid_AUC=0.9156 valid_FITB=0.5740 lr=1.25e-04

CP train original_text seed=2 epoch=21:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=21 loss=0.0130 valid_AUC=0.9148 valid_FITB=0.5707 lr=6.25e-05

CP train original_text seed=2 epoch=22:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=22 loss=0.0115 valid_AUC=0.9152 valid_FITB=0.5703 lr=6.25e-05

CP train original_text seed=2 epoch=23:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=23 loss=0.0104 valid_AUC=0.9150 valid_FITB=0.5727 lr=6.25e-05

CP train original_text seed=2 epoch=24:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=24 loss=0.0104 valid_AUC=0.9152 valid_FITB=0.5730 lr=3.13e-05

CP train original_text seed=2 epoch=25:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=25 loss=0.0095 valid_AUC=0.9153 valid_FITB=0.5723 lr=3.13e-05

CP train original_text seed=2 epoch=26:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=26 loss=0.0095 valid_AUC=0.9152 valid_FITB=0.5747 lr=3.13e-05

CP train original_text seed=2 epoch=27:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=27 loss=0.0092 valid_AUC=0.9152 valid_FITB=0.5730 lr=1.56e-05

CP train original_text seed=2 epoch=28:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=28 loss=0.0090 valid_AUC=0.9152 valid_FITB=0.5723 lr=1.56e-05

CP train original_text seed=2 epoch=29:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=29 loss=0.0082 valid_AUC=0.9151 valid_FITB=0.5743 lr=1.56e-05

CP train original_text seed=2 epoch=30:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=30 loss=0.0079 valid_AUC=0.9152 valid_FITB=0.5730 lr=7.81e-06

CP train original_text seed=2 epoch=31:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=31 loss=0.0082 valid_AUC=0.9152 valid_FITB=0.5730 lr=7.81e-06

CP train original_text seed=2 epoch=32:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=32 loss=0.0077 valid_AUC=0.9152 valid_FITB=0.5737 lr=7.81e-06

CP train original_text seed=2 epoch=33:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=33 loss=0.0078 valid_AUC=0.9153 valid_FITB=0.5750 lr=3.91e-06

CP train original_text seed=2 epoch=34:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=34 loss=0.0081 valid_AUC=0.9153 valid_FITB=0.5743 lr=3.91e-06

CP train original_text seed=2 epoch=35:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=35 loss=0.0077 valid_AUC=0.9153 valid_FITB=0.5733 lr=3.91e-06

CP train original_text seed=2 epoch=36:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=36 loss=0.0075 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.95e-06

CP train original_text seed=2 epoch=37:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=37 loss=0.0079 valid_AUC=0.9153 valid_FITB=0.5747 lr=1.95e-06

CP train original_text seed=2 epoch=38:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=38 loss=0.0073 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.95e-06

CP train original_text seed=2 epoch=39:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=39 loss=0.0070 valid_AUC=0.9153 valid_FITB=0.5740 lr=9.77e-07

CP train original_text seed=2 epoch=40:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=40 loss=0.0076 valid_AUC=0.9153 valid_FITB=0.5730 lr=9.77e-07

CP train original_text seed=2 epoch=41:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=41 loss=0.0073 valid_AUC=0.9153 valid_FITB=0.5737 lr=9.77e-07

CP train original_text seed=2 epoch=42:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=42 loss=0.0072 valid_AUC=0.9153 valid_FITB=0.5737 lr=4.88e-07

CP train original_text seed=2 epoch=43:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=43 loss=0.0075 valid_AUC=0.9153 valid_FITB=0.5737 lr=4.88e-07

CP train original_text seed=2 epoch=44:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=44 loss=0.0072 valid_AUC=0.9153 valid_FITB=0.5737 lr=4.88e-07

CP train original_text seed=2 epoch=45:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=45 loss=0.0075 valid_AUC=0.9153 valid_FITB=0.5737 lr=2.44e-07

CP train original_text seed=2 epoch=46:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=46 loss=0.0080 valid_AUC=0.9153 valid_FITB=0.5737 lr=2.44e-07

CP train original_text seed=2 epoch=47:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=47 loss=0.0078 valid_AUC=0.9153 valid_FITB=0.5737 lr=2.44e-07

CP train original_text seed=2 epoch=48:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=48 loss=0.0077 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.22e-07

CP train original_text seed=2 epoch=49:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=49 loss=0.0076 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.22e-07

CP train original_text seed=2 epoch=50:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=50 loss=0.0074 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.22e-07

CP train original_text seed=2 epoch=51:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=51 loss=0.0077 valid_AUC=0.9153 valid_FITB=0.5740 lr=6.10e-08

CP train original_text seed=2 epoch=52:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=52 loss=0.0077 valid_AUC=0.9153 valid_FITB=0.5740 lr=6.10e-08

CP train original_text seed=2 epoch=53:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=53 loss=0.0073 valid_AUC=0.9153 valid_FITB=0.5740 lr=6.10e-08

CP train original_text seed=2 epoch=54:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=54 loss=0.0077 valid_AUC=0.9153 valid_FITB=0.5740 lr=3.05e-08

CP train original_text seed=2 epoch=55:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=55 loss=0.0076 valid_AUC=0.9153 valid_FITB=0.5737 lr=3.05e-08

CP train original_text seed=2 epoch=56:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=56 loss=0.0076 valid_AUC=0.9153 valid_FITB=0.5737 lr=3.05e-08

CP train original_text seed=2 epoch=57:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=57 loss=0.0074 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=58:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=58 loss=0.0078 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=59:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=59 loss=0.0079 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=60:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=60 loss=0.0072 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=61:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=61 loss=0.0072 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=62:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=62 loss=0.0075 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=63:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=63 loss=0.0074 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=64:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=64 loss=0.0084 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=65:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=65 loss=0.0076 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=66:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=66 loss=0.0072 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=67:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=67 loss=0.0078 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=68:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=68 loss=0.0079 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=69:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=69 loss=0.0070 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=70:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=70 loss=0.0072 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=71:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=71 loss=0.0076 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=72:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=72 loss=0.0075 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=73:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=73 loss=0.0073 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=74:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=74 loss=0.0078 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=75:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=75 loss=0.0081 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=76:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=76 loss=0.0081 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=77:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=77 loss=0.0075 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=78:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=78 loss=0.0080 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=79:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=79 loss=0.0074 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=80:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=80 loss=0.0077 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=81:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=81 loss=0.0075 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=82:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=82 loss=0.0069 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=83:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=83 loss=0.0077 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=84:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=84 loss=0.0078 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=85:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=85 loss=0.0071 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=86:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=86 loss=0.0078 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=87:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=87 loss=0.0073 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=88:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=88 loss=0.0078 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=89:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=89 loss=0.0072 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=90:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=90 loss=0.0072 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=91:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=91 loss=0.0076 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=92:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=92 loss=0.0075 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=93:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=93 loss=0.0075 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=94:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=94 loss=0.0073 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=95:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=95 loss=0.0078 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=96:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=96 loss=0.0074 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=97:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=97 loss=0.0077 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=98:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=98 loss=0.0075 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=99:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=99 loss=0.0074 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP train original_text seed=2 epoch=100:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=100 loss=0.0078 valid_AUC=0.9153 valid_FITB=0.5737 lr=1.53e-08

CP FITB:   0%|          | 0/15145 [00:00<?, ?it/s]

[OR 訓練] variant=original_text, seed=2, train=16,995, valid=3,000

OR train original_text seed=2 epoch=1:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=01 loss=0.9624 valid_FITB=0.6097 lr=1.00e-03

OR train original_text seed=2 epoch=2:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=02 loss=0.8102 valid_FITB=0.6130 lr=1.00e-03

OR train original_text seed=2 epoch=3:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=03 loss=0.7136 valid_FITB=0.6120 lr=1.00e-03

OR train original_text seed=2 epoch=4:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=04 loss=0.6184 valid_FITB=0.6027 lr=1.00e-03

OR train original_text seed=2 epoch=5:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=05 loss=0.5110 valid_FITB=0.5957 lr=5.00e-04

OR train original_text seed=2 epoch=6:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=06 loss=0.3630 valid_FITB=0.5987 lr=5.00e-04

OR train original_text seed=2 epoch=7:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=07 loss=0.2929 valid_FITB=0.5950 lr=5.00e-04

OR train original_text seed=2 epoch=8:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=08 loss=0.2405 valid_FITB=0.5970 lr=2.50e-04

OR train original_text seed=2 epoch=9:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=09 loss=0.1819 valid_FITB=0.5927 lr=2.50e-04

OR train original_text seed=2 epoch=10:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=10 loss=0.1501 valid_FITB=0.5870 lr=2.50e-04

OR train original_text seed=2 epoch=11:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=11 loss=0.1351 valid_FITB=0.5873 lr=1.25e-04

OR train original_text seed=2 epoch=12:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=12 loss=0.1137 valid_FITB=0.5917 lr=1.25e-04

OR train original_text seed=2 epoch=13:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=13 loss=0.1077 valid_FITB=0.5910 lr=1.25e-04

OR train original_text seed=2 epoch=14:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=14 loss=0.1004 valid_FITB=0.5873 lr=6.25e-05

OR train original_text seed=2 epoch=15:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=15 loss=0.0936 valid_FITB=0.5897 lr=6.25e-05

OR train original_text seed=2 epoch=16:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=16 loss=0.0897 valid_FITB=0.5870 lr=6.25e-05

OR train original_text seed=2 epoch=17:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=17 loss=0.0860 valid_FITB=0.5893 lr=3.13e-05

OR train original_text seed=2 epoch=18:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=18 loss=0.0826 valid_FITB=0.5850 lr=3.13e-05

OR train original_text seed=2 epoch=19:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=19 loss=0.0822 valid_FITB=0.5883 lr=3.13e-05

OR train original_text seed=2 epoch=20:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=20 loss=0.0790 valid_FITB=0.5883 lr=1.56e-05

OR train original_text seed=2 epoch=21:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=21 loss=0.0774 valid_FITB=0.5880 lr=1.56e-05

OR train original_text seed=2 epoch=22:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=22 loss=0.0769 valid_FITB=0.5863 lr=1.56e-05

OR train original_text seed=2 epoch=23:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=23 loss=0.0770 valid_FITB=0.5863 lr=7.81e-06

OR train original_text seed=2 epoch=24:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=24 loss=0.0735 valid_FITB=0.5860 lr=7.81e-06

OR train original_text seed=2 epoch=25:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=25 loss=0.0747 valid_FITB=0.5863 lr=7.81e-06

OR train original_text seed=2 epoch=26:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=26 loss=0.0755 valid_FITB=0.5880 lr=3.91e-06

OR train original_text seed=2 epoch=27:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=27 loss=0.0752 valid_FITB=0.5870 lr=3.91e-06

OR train original_text seed=2 epoch=28:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=28 loss=0.0740 valid_FITB=0.5870 lr=3.91e-06

OR train original_text seed=2 epoch=29:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=29 loss=0.0753 valid_FITB=0.5873 lr=1.95e-06

OR train original_text seed=2 epoch=30:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=30 loss=0.0742 valid_FITB=0.5873 lr=1.95e-06

OR train original_text seed=2 epoch=31:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=31 loss=0.0734 valid_FITB=0.5870 lr=1.95e-06

OR train original_text seed=2 epoch=32:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=32 loss=0.0733 valid_FITB=0.5877 lr=9.77e-07

OR train original_text seed=2 epoch=33:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=33 loss=0.0736 valid_FITB=0.5873 lr=9.77e-07

OR train original_text seed=2 epoch=34:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=34 loss=0.0733 valid_FITB=0.5870 lr=9.77e-07

OR train original_text seed=2 epoch=35:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=35 loss=0.0731 valid_FITB=0.5870 lr=4.88e-07

OR train original_text seed=2 epoch=36:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=36 loss=0.0727 valid_FITB=0.5870 lr=4.88e-07

OR train original_text seed=2 epoch=37:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=37 loss=0.0746 valid_FITB=0.5870 lr=4.88e-07

OR train original_text seed=2 epoch=38:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=38 loss=0.0749 valid_FITB=0.5873 lr=2.44e-07

OR train original_text seed=2 epoch=39:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=39 loss=0.0740 valid_FITB=0.5877 lr=2.44e-07

OR train original_text seed=2 epoch=40:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=40 loss=0.0734 valid_FITB=0.5873 lr=2.44e-07

OR train original_text seed=2 epoch=41:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=41 loss=0.0749 valid_FITB=0.5870 lr=1.22e-07

OR train original_text seed=2 epoch=42:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=42 loss=0.0727 valid_FITB=0.5870 lr=1.22e-07

OR train original_text seed=2 epoch=43:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=43 loss=0.0737 valid_FITB=0.5870 lr=1.22e-07

OR train original_text seed=2 epoch=44:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=44 loss=0.0731 valid_FITB=0.5870 lr=6.10e-08

OR train original_text seed=2 epoch=45:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=45 loss=0.0725 valid_FITB=0.5870 lr=6.10e-08

OR train original_text seed=2 epoch=46:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=46 loss=0.0761 valid_FITB=0.5870 lr=6.10e-08

OR train original_text seed=2 epoch=47:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=47 loss=0.0738 valid_FITB=0.5870 lr=3.05e-08

OR train original_text seed=2 epoch=48:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=48 loss=0.0724 valid_FITB=0.5870 lr=3.05e-08

OR train original_text seed=2 epoch=49:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=49 loss=0.0741 valid_FITB=0.5870 lr=3.05e-08

OR train original_text seed=2 epoch=50:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=50 loss=0.0749 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=51:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=51 loss=0.0738 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=52:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=52 loss=0.0744 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=53:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=53 loss=0.0732 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=54:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=54 loss=0.0729 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=55:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=55 loss=0.0742 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=56:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=56 loss=0.0729 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=57:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=57 loss=0.0736 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=58:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=58 loss=0.0723 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=59:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=59 loss=0.0725 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=60:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=60 loss=0.0745 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=61:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=61 loss=0.0739 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=62:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=62 loss=0.0746 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=63:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=63 loss=0.0740 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=64:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=64 loss=0.0746 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=65:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=65 loss=0.0749 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=66:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=66 loss=0.0737 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=67:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=67 loss=0.0740 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=68:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=68 loss=0.0749 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=69:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=69 loss=0.0748 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=70:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=70 loss=0.0720 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=71:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=71 loss=0.0746 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=72:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=72 loss=0.0729 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=73:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=73 loss=0.0735 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=74:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=74 loss=0.0748 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=75:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=75 loss=0.0726 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=76:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=76 loss=0.0743 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=77:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=77 loss=0.0730 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=78:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=78 loss=0.0745 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=79:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=79 loss=0.0725 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=80:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=80 loss=0.0752 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=81:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=81 loss=0.0733 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=82:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=82 loss=0.0726 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=83:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=83 loss=0.0730 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=84:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=84 loss=0.0724 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=85:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=85 loss=0.0716 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=86:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=86 loss=0.0730 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=87:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=87 loss=0.0741 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=88:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=88 loss=0.0735 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=89:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=89 loss=0.0722 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=90:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=90 loss=0.0740 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=91:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=91 loss=0.0722 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=92:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=92 loss=0.0725 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=93:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=93 loss=0.0756 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=94:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=94 loss=0.0736 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=95:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=95 loss=0.0735 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=96:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=96 loss=0.0744 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=97:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=97 loss=0.0721 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=98:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=98 loss=0.0739 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=99:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=99 loss=0.0729 valid_FITB=0.5870 lr=1.53e-08

OR train original_text seed=2 epoch=100:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=100 loss=0.0732 valid_FITB=0.5870 lr=1.53e-08

encode candidate pools [original_text seed=2]:   0%|          | 0/19 [00:00<?, ?it/s]

OR/CIR recall [original_text seed=2]:   0%|          | 0/15145 [00:00<?, ?it/s]

[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/original_text/seed_2/seed_summary.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/original_text/seed_2/or_recall_rowlevel.csv

[CP 訓練] variant=original_text, seed=3, train=33,990, valid=6,000

CP train original_text seed=3 epoch=1:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=01 loss=0.6726 valid_AUC=0.7529 valid_FITB=0.3830 lr=1.00e-03

CP train original_text seed=3 epoch=2:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=02 loss=0.5351 valid_AUC=0.8461 valid_FITB=0.4780 lr=1.00e-03

CP train original_text seed=3 epoch=3:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=03 loss=0.4545 valid_AUC=0.8639 valid_FITB=0.5007 lr=1.00e-03

CP train original_text seed=3 epoch=4:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=04 loss=0.4053 valid_AUC=0.8844 valid_FITB=0.5217 lr=1.00e-03

CP train original_text seed=3 epoch=5:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=05 loss=0.3661 valid_AUC=0.8873 valid_FITB=0.5307 lr=1.00e-03

CP train original_text seed=3 epoch=6:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=06 loss=0.3245 valid_AUC=0.8914 valid_FITB=0.5420 lr=1.00e-03

CP train original_text seed=3 epoch=7:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=07 loss=0.2874 valid_AUC=0.8978 valid_FITB=0.5487 lr=1.00e-03

CP train original_text seed=3 epoch=8:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=08 loss=0.2582 valid_AUC=0.8964 valid_FITB=0.5500 lr=1.00e-03

CP train original_text seed=3 epoch=9:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=09 loss=0.2257 valid_AUC=0.9077 valid_FITB=0.5527 lr=1.00e-03

CP train original_text seed=3 epoch=10:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=10 loss=0.2029 valid_AUC=0.9027 valid_FITB=0.5510 lr=1.00e-03

CP train original_text seed=3 epoch=11:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=11 loss=0.1694 valid_AUC=0.8992 valid_FITB=0.5550 lr=1.00e-03

CP train original_text seed=3 epoch=12:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=12 loss=0.1516 valid_AUC=0.9023 valid_FITB=0.5620 lr=1.00e-03

CP train original_text seed=3 epoch=13:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=13 loss=0.1278 valid_AUC=0.9016 valid_FITB=0.5570 lr=1.00e-03

CP train original_text seed=3 epoch=14:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=14 loss=0.1189 valid_AUC=0.9023 valid_FITB=0.5667 lr=1.00e-03

CP train original_text seed=3 epoch=15:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=15 loss=0.1040 valid_AUC=0.9044 valid_FITB=0.5627 lr=1.00e-03

CP train original_text seed=3 epoch=16:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=16 loss=0.0877 valid_AUC=0.9073 valid_FITB=0.5650 lr=1.00e-03

CP train original_text seed=3 epoch=17:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=17 loss=0.0809 valid_AUC=0.9032 valid_FITB=0.5593 lr=5.00e-04

CP train original_text seed=3 epoch=18:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=18 loss=0.0456 valid_AUC=0.9104 valid_FITB=0.5627 lr=5.00e-04

CP train original_text seed=3 epoch=19:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=19 loss=0.0296 valid_AUC=0.9111 valid_FITB=0.5617 lr=5.00e-04

CP train original_text seed=3 epoch=20:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=20 loss=0.0242 valid_AUC=0.9112 valid_FITB=0.5700 lr=5.00e-04

CP train original_text seed=3 epoch=21:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=21 loss=0.0235 valid_AUC=0.9110 valid_FITB=0.5633 lr=5.00e-04

CP train original_text seed=3 epoch=22:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=22 loss=0.0228 valid_AUC=0.9095 valid_FITB=0.5657 lr=5.00e-04

CP train original_text seed=3 epoch=23:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=23 loss=0.0213 valid_AUC=0.9105 valid_FITB=0.5667 lr=2.50e-04

CP train original_text seed=3 epoch=24:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=24 loss=0.0131 valid_AUC=0.9125 valid_FITB=0.5680 lr=2.50e-04

CP train original_text seed=3 epoch=25:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=25 loss=0.0096 valid_AUC=0.9120 valid_FITB=0.5677 lr=2.50e-04

CP train original_text seed=3 epoch=26:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=26 loss=0.0072 valid_AUC=0.9133 valid_FITB=0.5640 lr=1.25e-04

CP train original_text seed=3 epoch=27:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=27 loss=0.0055 valid_AUC=0.9124 valid_FITB=0.5703 lr=1.25e-04

CP train original_text seed=3 epoch=28:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=28 loss=0.0055 valid_AUC=0.9132 valid_FITB=0.5730 lr=1.25e-04

CP train original_text seed=3 epoch=29:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=29 loss=0.0053 valid_AUC=0.9135 valid_FITB=0.5697 lr=1.25e-04

CP train original_text seed=3 epoch=30:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=30 loss=0.0047 valid_AUC=0.9122 valid_FITB=0.5730 lr=1.25e-04

CP train original_text seed=3 epoch=31:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=31 loss=0.0040 valid_AUC=0.9123 valid_FITB=0.5663 lr=6.25e-05

CP train original_text seed=3 epoch=32:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=32 loss=0.0040 valid_AUC=0.9133 valid_FITB=0.5707 lr=6.25e-05

CP train original_text seed=3 epoch=33:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=33 loss=0.0038 valid_AUC=0.9134 valid_FITB=0.5710 lr=6.25e-05

CP train original_text seed=3 epoch=34:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=34 loss=0.0035 valid_AUC=0.9131 valid_FITB=0.5713 lr=3.13e-05

CP train original_text seed=3 epoch=35:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=35 loss=0.0036 valid_AUC=0.9134 valid_FITB=0.5713 lr=3.13e-05

CP train original_text seed=3 epoch=36:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=36 loss=0.0030 valid_AUC=0.9134 valid_FITB=0.5697 lr=3.13e-05

CP train original_text seed=3 epoch=37:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=37 loss=0.0030 valid_AUC=0.9135 valid_FITB=0.5707 lr=1.56e-05

CP train original_text seed=3 epoch=38:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=38 loss=0.0029 valid_AUC=0.9134 valid_FITB=0.5707 lr=1.56e-05

CP train original_text seed=3 epoch=39:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=39 loss=0.0034 valid_AUC=0.9133 valid_FITB=0.5720 lr=1.56e-05

CP train original_text seed=3 epoch=40:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=40 loss=0.0029 valid_AUC=0.9133 valid_FITB=0.5713 lr=7.81e-06

CP train original_text seed=3 epoch=41:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=41 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5713 lr=7.81e-06

CP train original_text seed=3 epoch=42:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=42 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5703 lr=7.81e-06

CP train original_text seed=3 epoch=43:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=43 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5727 lr=3.91e-06

CP train original_text seed=3 epoch=44:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=44 loss=0.0025 valid_AUC=0.9134 valid_FITB=0.5717 lr=3.91e-06

CP train original_text seed=3 epoch=45:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=45 loss=0.0025 valid_AUC=0.9133 valid_FITB=0.5713 lr=3.91e-06

CP train original_text seed=3 epoch=46:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=46 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5720 lr=1.95e-06

CP train original_text seed=3 epoch=47:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=47 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.95e-06

CP train original_text seed=3 epoch=48:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=48 loss=0.0025 valid_AUC=0.9133 valid_FITB=0.5707 lr=1.95e-06

CP train original_text seed=3 epoch=49:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=49 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5710 lr=9.77e-07

CP train original_text seed=3 epoch=50:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=50 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5707 lr=9.77e-07

CP train original_text seed=3 epoch=51:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=51 loss=0.0029 valid_AUC=0.9133 valid_FITB=0.5707 lr=9.77e-07

CP train original_text seed=3 epoch=52:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=52 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5710 lr=4.88e-07

CP train original_text seed=3 epoch=53:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=53 loss=0.0026 valid_AUC=0.9133 valid_FITB=0.5710 lr=4.88e-07

CP train original_text seed=3 epoch=54:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=54 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5710 lr=4.88e-07

CP train original_text seed=3 epoch=55:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=55 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5713 lr=2.44e-07

CP train original_text seed=3 epoch=56:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=56 loss=0.0029 valid_AUC=0.9133 valid_FITB=0.5710 lr=2.44e-07

CP train original_text seed=3 epoch=57:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=57 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5710 lr=2.44e-07

CP train original_text seed=3 epoch=58:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=58 loss=0.0030 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.22e-07

CP train original_text seed=3 epoch=59:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=59 loss=0.0026 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.22e-07

CP train original_text seed=3 epoch=60:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=60 loss=0.0030 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.22e-07

CP train original_text seed=3 epoch=61:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=61 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5710 lr=6.10e-08

CP train original_text seed=3 epoch=62:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=62 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5710 lr=6.10e-08

CP train original_text seed=3 epoch=63:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=63 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5710 lr=6.10e-08

CP train original_text seed=3 epoch=64:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=64 loss=0.0026 valid_AUC=0.9133 valid_FITB=0.5710 lr=3.05e-08

CP train original_text seed=3 epoch=65:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=65 loss=0.0026 valid_AUC=0.9133 valid_FITB=0.5710 lr=3.05e-08

CP train original_text seed=3 epoch=66:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=66 loss=0.0025 valid_AUC=0.9133 valid_FITB=0.5710 lr=3.05e-08

CP train original_text seed=3 epoch=67:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=67 loss=0.0032 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=68:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=68 loss=0.0025 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=69:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=69 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=70:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=70 loss=0.0029 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=71:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=71 loss=0.0025 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=72:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=72 loss=0.0024 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=73:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=73 loss=0.0031 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=74:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=74 loss=0.0025 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=75:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=75 loss=0.0026 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=76:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=76 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=77:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=77 loss=0.0029 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=78:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=78 loss=0.0022 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=79:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=79 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=80:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=80 loss=0.0026 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=81:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=81 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=82:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=82 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=83:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=83 loss=0.0026 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=84:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=84 loss=0.0029 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=85:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=85 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=86:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=86 loss=0.0022 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=87:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=87 loss=0.0031 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=88:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=88 loss=0.0026 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=89:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=89 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=90:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=90 loss=0.0025 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=91:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=91 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=92:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=92 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=93:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=93 loss=0.0025 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=94:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=94 loss=0.0026 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=95:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=95 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=96:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=96 loss=0.0028 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=97:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=97 loss=0.0022 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=98:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=98 loss=0.0025 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=99:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=99 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP train original_text seed=3 epoch=100:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=100 loss=0.0027 valid_AUC=0.9133 valid_FITB=0.5710 lr=1.53e-08

CP FITB:   0%|          | 0/15145 [00:00<?, ?it/s]

[OR 訓練] variant=original_text, seed=3, train=16,995, valid=3,000

OR train original_text seed=3 epoch=1:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=01 loss=0.9444 valid_FITB=0.6050 lr=1.00e-03

OR train original_text seed=3 epoch=2:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=02 loss=0.7961 valid_FITB=0.6073 lr=1.00e-03

OR train original_text seed=3 epoch=3:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=03 loss=0.6929 valid_FITB=0.6070 lr=1.00e-03

OR train original_text seed=3 epoch=4:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=04 loss=0.5906 valid_FITB=0.6027 lr=1.00e-03

OR train original_text seed=3 epoch=5:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=05 loss=0.4911 valid_FITB=0.5890 lr=5.00e-04

OR train original_text seed=3 epoch=6:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=06 loss=0.3502 valid_FITB=0.5917 lr=5.00e-04

OR train original_text seed=3 epoch=7:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=07 loss=0.2725 valid_FITB=0.5867 lr=5.00e-04

OR train original_text seed=3 epoch=8:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=08 loss=0.2279 valid_FITB=0.5900 lr=2.50e-04

OR train original_text seed=3 epoch=9:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=09 loss=0.1715 valid_FITB=0.5893 lr=2.50e-04

OR train original_text seed=3 epoch=10:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=10 loss=0.1528 valid_FITB=0.5847 lr=2.50e-04

OR train original_text seed=3 epoch=11:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=11 loss=0.1326 valid_FITB=0.5777 lr=1.25e-04

OR train original_text seed=3 epoch=12:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=12 loss=0.1150 valid_FITB=0.5790 lr=1.25e-04

OR train original_text seed=3 epoch=13:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=13 loss=0.1061 valid_FITB=0.5820 lr=1.25e-04

OR train original_text seed=3 epoch=14:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=14 loss=0.0993 valid_FITB=0.5807 lr=6.25e-05

OR train original_text seed=3 epoch=15:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=15 loss=0.0914 valid_FITB=0.5837 lr=6.25e-05

OR train original_text seed=3 epoch=16:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=16 loss=0.0894 valid_FITB=0.5797 lr=6.25e-05

OR train original_text seed=3 epoch=17:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=17 loss=0.0863 valid_FITB=0.5783 lr=3.13e-05

OR train original_text seed=3 epoch=18:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=18 loss=0.0843 valid_FITB=0.5820 lr=3.13e-05

OR train original_text seed=3 epoch=19:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=19 loss=0.0802 valid_FITB=0.5800 lr=3.13e-05

OR train original_text seed=3 epoch=20:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=20 loss=0.0801 valid_FITB=0.5793 lr=1.56e-05

OR train original_text seed=3 epoch=21:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=21 loss=0.0794 valid_FITB=0.5783 lr=1.56e-05

OR train original_text seed=3 epoch=22:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=22 loss=0.0761 valid_FITB=0.5787 lr=1.56e-05

OR train original_text seed=3 epoch=23:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=23 loss=0.0780 valid_FITB=0.5780 lr=7.81e-06

OR train original_text seed=3 epoch=24:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=24 loss=0.0745 valid_FITB=0.5777 lr=7.81e-06

OR train original_text seed=3 epoch=25:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=25 loss=0.0742 valid_FITB=0.5770 lr=7.81e-06

OR train original_text seed=3 epoch=26:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=26 loss=0.0764 valid_FITB=0.5770 lr=3.91e-06

OR train original_text seed=3 epoch=27:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=27 loss=0.0755 valid_FITB=0.5770 lr=3.91e-06

OR train original_text seed=3 epoch=28:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=28 loss=0.0753 valid_FITB=0.5770 lr=3.91e-06

OR train original_text seed=3 epoch=29:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=29 loss=0.0738 valid_FITB=0.5770 lr=1.95e-06

OR train original_text seed=3 epoch=30:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=30 loss=0.0752 valid_FITB=0.5767 lr=1.95e-06

OR train original_text seed=3 epoch=31:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=31 loss=0.0722 valid_FITB=0.5773 lr=1.95e-06

OR train original_text seed=3 epoch=32:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=32 loss=0.0752 valid_FITB=0.5773 lr=9.77e-07

OR train original_text seed=3 epoch=33:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=33 loss=0.0752 valid_FITB=0.5773 lr=9.77e-07

OR train original_text seed=3 epoch=34:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=34 loss=0.0748 valid_FITB=0.5767 lr=9.77e-07

OR train original_text seed=3 epoch=35:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=35 loss=0.0751 valid_FITB=0.5770 lr=4.88e-07

OR train original_text seed=3 epoch=36:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=36 loss=0.0745 valid_FITB=0.5770 lr=4.88e-07

OR train original_text seed=3 epoch=37:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=37 loss=0.0757 valid_FITB=0.5770 lr=4.88e-07

OR train original_text seed=3 epoch=38:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=38 loss=0.0727 valid_FITB=0.5767 lr=2.44e-07

OR train original_text seed=3 epoch=39:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=39 loss=0.0752 valid_FITB=0.5770 lr=2.44e-07

OR train original_text seed=3 epoch=40:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=40 loss=0.0731 valid_FITB=0.5770 lr=2.44e-07

OR train original_text seed=3 epoch=41:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=41 loss=0.0744 valid_FITB=0.5770 lr=1.22e-07

OR train original_text seed=3 epoch=42:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=42 loss=0.0744 valid_FITB=0.5770 lr=1.22e-07

OR train original_text seed=3 epoch=43:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=43 loss=0.0726 valid_FITB=0.5770 lr=1.22e-07

OR train original_text seed=3 epoch=44:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=44 loss=0.0732 valid_FITB=0.5770 lr=6.10e-08

OR train original_text seed=3 epoch=45:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=45 loss=0.0729 valid_FITB=0.5770 lr=6.10e-08

OR train original_text seed=3 epoch=46:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=46 loss=0.0725 valid_FITB=0.5770 lr=6.10e-08

OR train original_text seed=3 epoch=47:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=47 loss=0.0726 valid_FITB=0.5770 lr=3.05e-08

OR train original_text seed=3 epoch=48:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=48 loss=0.0746 valid_FITB=0.5770 lr=3.05e-08

OR train original_text seed=3 epoch=49:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=49 loss=0.0744 valid_FITB=0.5770 lr=3.05e-08

OR train original_text seed=3 epoch=50:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=50 loss=0.0734 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=51:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=51 loss=0.0737 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=52:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=52 loss=0.0737 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=53:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=53 loss=0.0750 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=54:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=54 loss=0.0735 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=55:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=55 loss=0.0739 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=56:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=56 loss=0.0736 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=57:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=57 loss=0.0732 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=58:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=58 loss=0.0751 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=59:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=59 loss=0.0745 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=60:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=60 loss=0.0741 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=61:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=61 loss=0.0745 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=62:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=62 loss=0.0733 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=63:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=63 loss=0.0747 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=64:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=64 loss=0.0731 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=65:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=65 loss=0.0753 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=66:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=66 loss=0.0755 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=67:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=67 loss=0.0744 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=68:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=68 loss=0.0732 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=69:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=69 loss=0.0746 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=70:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=70 loss=0.0729 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=71:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=71 loss=0.0735 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=72:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=72 loss=0.0753 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=73:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=73 loss=0.0742 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=74:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=74 loss=0.0736 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=75:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=75 loss=0.0750 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=76:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=76 loss=0.0728 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=77:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=77 loss=0.0737 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=78:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=78 loss=0.0723 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=79:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=79 loss=0.0744 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=80:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=80 loss=0.0750 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=81:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=81 loss=0.0750 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=82:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=82 loss=0.0747 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=83:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=83 loss=0.0738 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=84:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=84 loss=0.0755 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=85:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=85 loss=0.0730 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=86:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=86 loss=0.0747 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=87:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=87 loss=0.0745 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=88:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=88 loss=0.0728 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=89:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=89 loss=0.0734 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=90:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=90 loss=0.0725 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=91:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=91 loss=0.0741 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=92:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=92 loss=0.0750 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=93:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=93 loss=0.0748 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=94:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=94 loss=0.0740 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=95:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=95 loss=0.0748 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=96:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=96 loss=0.0737 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=97:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=97 loss=0.0752 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=98:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=98 loss=0.0730 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=99:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=99 loss=0.0732 valid_FITB=0.5770 lr=1.53e-08

OR train original_text seed=3 epoch=100:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=100 loss=0.0733 valid_FITB=0.5770 lr=1.53e-08

encode candidate pools [original_text seed=3]:   0%|          | 0/19 [00:00<?, ?it/s]

OR/CIR recall [original_text seed=3]:   0%|          | 0/15145 [00:00<?, ?it/s]

[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/original_text/seed_3/seed_summary.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/original_text/seed_3/or_recall_rowlevel.csv

[CP 訓練] variant=original_text, seed=4, train=33,990, valid=6,000

CP train original_text seed=4 epoch=1:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=01 loss=0.6406 valid_AUC=0.7893 valid_FITB=0.4220 lr=1.00e-03

CP train original_text seed=4 epoch=2:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=02 loss=0.5146 valid_AUC=0.8326 valid_FITB=0.4703 lr=1.00e-03

CP train original_text seed=4 epoch=3:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=03 loss=0.4515 valid_AUC=0.8729 valid_FITB=0.5127 lr=1.00e-03

CP train original_text seed=4 epoch=4:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=04 loss=0.3989 valid_AUC=0.8915 valid_FITB=0.5423 lr=1.00e-03

CP train original_text seed=4 epoch=5:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=05 loss=0.3511 valid_AUC=0.8954 valid_FITB=0.5623 lr=1.00e-03

CP train original_text seed=4 epoch=6:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=06 loss=0.3055 valid_AUC=0.9047 valid_FITB=0.5653 lr=1.00e-03

CP train original_text seed=4 epoch=7:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=07 loss=0.2766 valid_AUC=0.9061 valid_FITB=0.5643 lr=1.00e-03

CP train original_text seed=4 epoch=8:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=08 loss=0.2525 valid_AUC=0.9081 valid_FITB=0.5687 lr=1.00e-03

CP train original_text seed=4 epoch=9:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=09 loss=0.2164 valid_AUC=0.9069 valid_FITB=0.5653 lr=1.00e-03

CP train original_text seed=4 epoch=10:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=10 loss=0.1920 valid_AUC=0.9045 valid_FITB=0.5660 lr=1.00e-03

CP train original_text seed=4 epoch=11:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=11 loss=0.1700 valid_AUC=0.9084 valid_FITB=0.5703 lr=1.00e-03

CP train original_text seed=4 epoch=12:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=12 loss=0.1473 valid_AUC=0.9070 valid_FITB=0.5603 lr=1.00e-03

CP train original_text seed=4 epoch=13:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=13 loss=0.1299 valid_AUC=0.9073 valid_FITB=0.5663 lr=1.00e-03

CP train original_text seed=4 epoch=14:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=14 loss=0.1144 valid_AUC=0.9062 valid_FITB=0.5700 lr=5.00e-04

CP train original_text seed=4 epoch=15:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=15 loss=0.0644 valid_AUC=0.9129 valid_FITB=0.5667 lr=5.00e-04

CP train original_text seed=4 epoch=16:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=16 loss=0.0427 valid_AUC=0.9137 valid_FITB=0.5697 lr=5.00e-04

CP train original_text seed=4 epoch=17:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=17 loss=0.0379 valid_AUC=0.9122 valid_FITB=0.5677 lr=2.50e-04

CP train original_text seed=4 epoch=18:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=18 loss=0.0244 valid_AUC=0.9134 valid_FITB=0.5697 lr=2.50e-04

CP train original_text seed=4 epoch=19:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=19 loss=0.0172 valid_AUC=0.9131 valid_FITB=0.5613 lr=2.50e-04

CP train original_text seed=4 epoch=20:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=20 loss=0.0165 valid_AUC=0.9143 valid_FITB=0.5670 lr=1.25e-04

CP train original_text seed=4 epoch=21:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=21 loss=0.0121 valid_AUC=0.9149 valid_FITB=0.5653 lr=1.25e-04

CP train original_text seed=4 epoch=22:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=22 loss=0.0118 valid_AUC=0.9143 valid_FITB=0.5633 lr=1.25e-04

CP train original_text seed=4 epoch=23:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=23 loss=0.0099 valid_AUC=0.9148 valid_FITB=0.5653 lr=6.25e-05

CP train original_text seed=4 epoch=24:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=24 loss=0.0095 valid_AUC=0.9149 valid_FITB=0.5643 lr=6.25e-05

CP train original_text seed=4 epoch=25:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=25 loss=0.0077 valid_AUC=0.9149 valid_FITB=0.5647 lr=6.25e-05

CP train original_text seed=4 epoch=26:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=26 loss=0.0082 valid_AUC=0.9146 valid_FITB=0.5660 lr=3.13e-05

CP train original_text seed=4 epoch=27:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=27 loss=0.0072 valid_AUC=0.9151 valid_FITB=0.5673 lr=3.13e-05

CP train original_text seed=4 epoch=28:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=28 loss=0.0071 valid_AUC=0.9149 valid_FITB=0.5637 lr=3.13e-05

CP train original_text seed=4 epoch=29:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=29 loss=0.0069 valid_AUC=0.9152 valid_FITB=0.5630 lr=1.56e-05

CP train original_text seed=4 epoch=30:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=30 loss=0.0062 valid_AUC=0.9151 valid_FITB=0.5643 lr=1.56e-05

CP train original_text seed=4 epoch=31:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=31 loss=0.0061 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.56e-05

CP train original_text seed=4 epoch=32:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=32 loss=0.0057 valid_AUC=0.9151 valid_FITB=0.5667 lr=7.81e-06

CP train original_text seed=4 epoch=33:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=33 loss=0.0062 valid_AUC=0.9152 valid_FITB=0.5653 lr=7.81e-06

CP train original_text seed=4 epoch=34:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=34 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5647 lr=7.81e-06

CP train original_text seed=4 epoch=35:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=35 loss=0.0059 valid_AUC=0.9151 valid_FITB=0.5657 lr=3.91e-06

CP train original_text seed=4 epoch=36:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=36 loss=0.0061 valid_AUC=0.9152 valid_FITB=0.5663 lr=3.91e-06

CP train original_text seed=4 epoch=37:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=37 loss=0.0059 valid_AUC=0.9152 valid_FITB=0.5663 lr=3.91e-06

CP train original_text seed=4 epoch=38:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=38 loss=0.0058 valid_AUC=0.9151 valid_FITB=0.5660 lr=1.95e-06

CP train original_text seed=4 epoch=39:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=39 loss=0.0058 valid_AUC=0.9151 valid_FITB=0.5663 lr=1.95e-06

CP train original_text seed=4 epoch=40:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=40 loss=0.0057 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.95e-06

CP train original_text seed=4 epoch=41:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=41 loss=0.0054 valid_AUC=0.9152 valid_FITB=0.5660 lr=9.77e-07

CP train original_text seed=4 epoch=42:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=42 loss=0.0062 valid_AUC=0.9151 valid_FITB=0.5660 lr=9.77e-07

CP train original_text seed=4 epoch=43:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=43 loss=0.0052 valid_AUC=0.9152 valid_FITB=0.5653 lr=9.77e-07

CP train original_text seed=4 epoch=44:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=44 loss=0.0061 valid_AUC=0.9152 valid_FITB=0.5660 lr=4.88e-07

CP train original_text seed=4 epoch=45:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=45 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5670 lr=4.88e-07

CP train original_text seed=4 epoch=46:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=46 loss=0.0056 valid_AUC=0.9152 valid_FITB=0.5670 lr=4.88e-07

CP train original_text seed=4 epoch=47:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=47 loss=0.0056 valid_AUC=0.9152 valid_FITB=0.5667 lr=2.44e-07

CP train original_text seed=4 epoch=48:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=48 loss=0.0056 valid_AUC=0.9152 valid_FITB=0.5660 lr=2.44e-07

CP train original_text seed=4 epoch=49:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=49 loss=0.0061 valid_AUC=0.9152 valid_FITB=0.5663 lr=2.44e-07

CP train original_text seed=4 epoch=50:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=50 loss=0.0057 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.22e-07

CP train original_text seed=4 epoch=51:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=51 loss=0.0056 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.22e-07

CP train original_text seed=4 epoch=52:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=52 loss=0.0055 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.22e-07

CP train original_text seed=4 epoch=53:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=53 loss=0.0056 valid_AUC=0.9152 valid_FITB=0.5657 lr=6.10e-08

CP train original_text seed=4 epoch=54:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=54 loss=0.0050 valid_AUC=0.9152 valid_FITB=0.5657 lr=6.10e-08

CP train original_text seed=4 epoch=55:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=55 loss=0.0054 valid_AUC=0.9152 valid_FITB=0.5657 lr=6.10e-08

CP train original_text seed=4 epoch=56:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=56 loss=0.0057 valid_AUC=0.9152 valid_FITB=0.5657 lr=3.05e-08

CP train original_text seed=4 epoch=57:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=57 loss=0.0054 valid_AUC=0.9152 valid_FITB=0.5657 lr=3.05e-08

CP train original_text seed=4 epoch=58:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=58 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5657 lr=3.05e-08

CP train original_text seed=4 epoch=59:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=59 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=60:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=60 loss=0.0054 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=61:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=61 loss=0.0060 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=62:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=62 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=63:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=63 loss=0.0053 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=64:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=64 loss=0.0055 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=65:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=65 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=66:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=66 loss=0.0059 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=67:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=67 loss=0.0059 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=68:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=68 loss=0.0056 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=69:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=69 loss=0.0059 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=70:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=70 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=71:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=71 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=72:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=72 loss=0.0061 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=73:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=73 loss=0.0057 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=74:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=74 loss=0.0064 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=75:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=75 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=76:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=76 loss=0.0057 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=77:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=77 loss=0.0051 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=78:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=78 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=79:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=79 loss=0.0056 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=80:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=80 loss=0.0049 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=81:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=81 loss=0.0056 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=82:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=82 loss=0.0054 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=83:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=83 loss=0.0062 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=84:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=84 loss=0.0057 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=85:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=85 loss=0.0056 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=86:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=86 loss=0.0054 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=87:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=87 loss=0.0056 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=88:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=88 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=89:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=89 loss=0.0059 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=90:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=90 loss=0.0054 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=91:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=91 loss=0.0061 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=92:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=92 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=93:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=93 loss=0.0058 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=94:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=94 loss=0.0051 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=95:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=95 loss=0.0059 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=96:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=96 loss=0.0060 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=97:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=97 loss=0.0057 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=98:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=98 loss=0.0055 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=99:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=99 loss=0.0057 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP train original_text seed=4 epoch=100:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=100 loss=0.0060 valid_AUC=0.9152 valid_FITB=0.5657 lr=1.53e-08

CP FITB:   0%|          | 0/15145 [00:00<?, ?it/s]

[OR 訓練] variant=original_text, seed=4, train=16,995, valid=3,000

OR train original_text seed=4 epoch=1:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=01 loss=0.9659 valid_FITB=0.6103 lr=1.00e-03

OR train original_text seed=4 epoch=2:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=02 loss=0.8260 valid_FITB=0.6060 lr=1.00e-03

OR train original_text seed=4 epoch=3:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=03 loss=0.7207 valid_FITB=0.6120 lr=1.00e-03

OR train original_text seed=4 epoch=4:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=04 loss=0.6288 valid_FITB=0.6037 lr=1.00e-03

OR train original_text seed=4 epoch=5:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=05 loss=0.5294 valid_FITB=0.5953 lr=1.00e-03

OR train original_text seed=4 epoch=6:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=06 loss=0.4291 valid_FITB=0.5937 lr=5.00e-04

OR train original_text seed=4 epoch=7:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=07 loss=0.2954 valid_FITB=0.5913 lr=5.00e-04

OR train original_text seed=4 epoch=8:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=08 loss=0.2249 valid_FITB=0.5943 lr=5.00e-04

OR train original_text seed=4 epoch=9:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=09 loss=0.1865 valid_FITB=0.5883 lr=2.50e-04

OR train original_text seed=4 epoch=10:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=10 loss=0.1407 valid_FITB=0.5940 lr=2.50e-04

OR train original_text seed=4 epoch=11:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=11 loss=0.1192 valid_FITB=0.5913 lr=2.50e-04

OR train original_text seed=4 epoch=12:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=12 loss=0.1079 valid_FITB=0.5903 lr=1.25e-04

OR train original_text seed=4 epoch=13:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=13 loss=0.0932 valid_FITB=0.5917 lr=1.25e-04

OR train original_text seed=4 epoch=14:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=14 loss=0.0837 valid_FITB=0.5897 lr=1.25e-04

OR train original_text seed=4 epoch=15:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=15 loss=0.0797 valid_FITB=0.5890 lr=6.25e-05

OR train original_text seed=4 epoch=16:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=16 loss=0.0720 valid_FITB=0.5867 lr=6.25e-05

OR train original_text seed=4 epoch=17:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=17 loss=0.0713 valid_FITB=0.5860 lr=6.25e-05

OR train original_text seed=4 epoch=18:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=18 loss=0.0680 valid_FITB=0.5880 lr=3.13e-05

OR train original_text seed=4 epoch=19:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=19 loss=0.0659 valid_FITB=0.5853 lr=3.13e-05

OR train original_text seed=4 epoch=20:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=20 loss=0.0645 valid_FITB=0.5880 lr=3.13e-05

OR train original_text seed=4 epoch=21:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=21 loss=0.0635 valid_FITB=0.5867 lr=1.56e-05

OR train original_text seed=4 epoch=22:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=22 loss=0.0623 valid_FITB=0.5863 lr=1.56e-05

OR train original_text seed=4 epoch=23:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=23 loss=0.0618 valid_FITB=0.5863 lr=1.56e-05

OR train original_text seed=4 epoch=24:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=24 loss=0.0620 valid_FITB=0.5867 lr=7.81e-06

OR train original_text seed=4 epoch=25:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=25 loss=0.0601 valid_FITB=0.5870 lr=7.81e-06

OR train original_text seed=4 epoch=26:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=26 loss=0.0609 valid_FITB=0.5870 lr=7.81e-06

OR train original_text seed=4 epoch=27:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=27 loss=0.0585 valid_FITB=0.5880 lr=3.91e-06

OR train original_text seed=4 epoch=28:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=28 loss=0.0604 valid_FITB=0.5873 lr=3.91e-06

OR train original_text seed=4 epoch=29:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=29 loss=0.0595 valid_FITB=0.5877 lr=3.91e-06

OR train original_text seed=4 epoch=30:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=30 loss=0.0584 valid_FITB=0.5877 lr=1.95e-06

OR train original_text seed=4 epoch=31:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=31 loss=0.0571 valid_FITB=0.5877 lr=1.95e-06

OR train original_text seed=4 epoch=32:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=32 loss=0.0594 valid_FITB=0.5873 lr=1.95e-06

OR train original_text seed=4 epoch=33:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=33 loss=0.0581 valid_FITB=0.5880 lr=9.77e-07

OR train original_text seed=4 epoch=34:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=34 loss=0.0607 valid_FITB=0.5877 lr=9.77e-07

OR train original_text seed=4 epoch=35:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=35 loss=0.0588 valid_FITB=0.5880 lr=9.77e-07

OR train original_text seed=4 epoch=36:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=36 loss=0.0582 valid_FITB=0.5890 lr=4.88e-07

OR train original_text seed=4 epoch=37:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=37 loss=0.0576 valid_FITB=0.5890 lr=4.88e-07

OR train original_text seed=4 epoch=38:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=38 loss=0.0582 valid_FITB=0.5890 lr=4.88e-07

OR train original_text seed=4 epoch=39:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=39 loss=0.0595 valid_FITB=0.5890 lr=2.44e-07

OR train original_text seed=4 epoch=40:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=40 loss=0.0581 valid_FITB=0.5890 lr=2.44e-07

OR train original_text seed=4 epoch=41:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=41 loss=0.0575 valid_FITB=0.5890 lr=2.44e-07

OR train original_text seed=4 epoch=42:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=42 loss=0.0579 valid_FITB=0.5890 lr=1.22e-07

OR train original_text seed=4 epoch=43:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=43 loss=0.0598 valid_FITB=0.5890 lr=1.22e-07

OR train original_text seed=4 epoch=44:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=44 loss=0.0576 valid_FITB=0.5890 lr=1.22e-07

OR train original_text seed=4 epoch=45:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=45 loss=0.0575 valid_FITB=0.5890 lr=6.10e-08

OR train original_text seed=4 epoch=46:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=46 loss=0.0584 valid_FITB=0.5893 lr=6.10e-08

OR train original_text seed=4 epoch=47:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=47 loss=0.0585 valid_FITB=0.5893 lr=6.10e-08

OR train original_text seed=4 epoch=48:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=48 loss=0.0566 valid_FITB=0.5893 lr=3.05e-08

OR train original_text seed=4 epoch=49:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=49 loss=0.0590 valid_FITB=0.5893 lr=3.05e-08

OR train original_text seed=4 epoch=50:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=50 loss=0.0584 valid_FITB=0.5893 lr=3.05e-08

OR train original_text seed=4 epoch=51:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=51 loss=0.0582 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=52:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=52 loss=0.0585 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=53:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=53 loss=0.0587 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=54:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=54 loss=0.0588 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=55:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=55 loss=0.0596 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=56:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=56 loss=0.0585 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=57:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=57 loss=0.0574 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=58:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=58 loss=0.0596 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=59:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=59 loss=0.0582 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=60:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=60 loss=0.0577 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=61:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=61 loss=0.0587 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=62:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=62 loss=0.0590 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=63:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=63 loss=0.0583 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=64:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=64 loss=0.0589 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=65:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=65 loss=0.0591 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=66:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=66 loss=0.0594 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=67:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=67 loss=0.0577 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=68:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=68 loss=0.0576 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=69:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=69 loss=0.0583 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=70:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=70 loss=0.0592 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=71:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=71 loss=0.0574 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=72:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=72 loss=0.0571 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=73:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=73 loss=0.0585 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=74:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=74 loss=0.0583 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=75:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=75 loss=0.0594 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=76:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=76 loss=0.0602 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=77:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=77 loss=0.0580 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=78:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=78 loss=0.0588 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=79:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=79 loss=0.0600 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=80:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=80 loss=0.0584 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=81:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=81 loss=0.0579 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=82:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=82 loss=0.0578 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=83:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=83 loss=0.0592 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=84:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=84 loss=0.0591 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=85:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=85 loss=0.0575 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=86:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=86 loss=0.0579 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=87:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=87 loss=0.0590 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=88:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=88 loss=0.0598 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=89:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=89 loss=0.0582 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=90:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=90 loss=0.0591 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=91:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=91 loss=0.0599 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=92:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=92 loss=0.0610 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=93:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=93 loss=0.0588 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=94:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=94 loss=0.0596 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=95:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=95 loss=0.0570 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=96:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=96 loss=0.0571 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=97:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=97 loss=0.0578 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=98:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=98 loss=0.0584 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=99:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=99 loss=0.0597 valid_FITB=0.5893 lr=1.53e-08

OR train original_text seed=4 epoch=100:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=100 loss=0.0578 valid_FITB=0.5893 lr=1.53e-08

encode candidate pools [original_text seed=4]:   0%|          | 0/19 [00:00<?, ?it/s]

OR/CIR recall [original_text seed=4]:   0%|          | 0/15145 [00:00<?, ?it/s]

[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/original_text/seed_4/seed_summary.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/original_text/seed_4/or_recall_rowlevel.csv

[CP 訓練] variant=original_text, seed=5, train=33,990, valid=6,000

CP train original_text seed=5 epoch=1:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=01 loss=0.6606 valid_AUC=0.7605 valid_FITB=0.4033 lr=1.00e-03

CP train original_text seed=5 epoch=2:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=02 loss=0.5236 valid_AUC=0.8347 valid_FITB=0.4837 lr=1.00e-03

CP train original_text seed=5 epoch=3:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=03 loss=0.4413 valid_AUC=0.8793 valid_FITB=0.5397 lr=1.00e-03

CP train original_text seed=5 epoch=4:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=04 loss=0.3845 valid_AUC=0.9022 valid_FITB=0.5560 lr=1.00e-03

CP train original_text seed=5 epoch=5:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=05 loss=0.3411 valid_AUC=0.9101 valid_FITB=0.5733 lr=1.00e-03

CP train original_text seed=5 epoch=6:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=06 loss=0.2996 valid_AUC=0.9121 valid_FITB=0.5770 lr=1.00e-03

CP train original_text seed=5 epoch=7:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=07 loss=0.2658 valid_AUC=0.9105 valid_FITB=0.5810 lr=1.00e-03

CP train original_text seed=5 epoch=8:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=08 loss=0.2344 valid_AUC=0.9125 valid_FITB=0.5810 lr=1.00e-03

CP train original_text seed=5 epoch=9:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=09 loss=0.2109 valid_AUC=0.9188 valid_FITB=0.5770 lr=1.00e-03

CP train original_text seed=5 epoch=10:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=10 loss=0.1782 valid_AUC=0.9066 valid_FITB=0.5740 lr=5.00e-04

CP train original_text seed=5 epoch=11:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=11 loss=0.1146 valid_AUC=0.9188 valid_FITB=0.5887 lr=5.00e-04

CP train original_text seed=5 epoch=12:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=12 loss=0.0875 valid_AUC=0.9173 valid_FITB=0.5867 lr=5.00e-04

CP train original_text seed=5 epoch=13:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=13 loss=0.0725 valid_AUC=0.9149 valid_FITB=0.5833 lr=5.00e-04

CP train original_text seed=5 epoch=14:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=14 loss=0.0622 valid_AUC=0.9151 valid_FITB=0.5780 lr=2.50e-04

CP train original_text seed=5 epoch=15:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=15 loss=0.0388 valid_AUC=0.9179 valid_FITB=0.5790 lr=2.50e-04

CP train original_text seed=5 epoch=16:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=16 loss=0.0298 valid_AUC=0.9189 valid_FITB=0.5757 lr=2.50e-04

CP train original_text seed=5 epoch=17:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=17 loss=0.0247 valid_AUC=0.9185 valid_FITB=0.5797 lr=1.25e-04

CP train original_text seed=5 epoch=18:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=18 loss=0.0189 valid_AUC=0.9177 valid_FITB=0.5777 lr=1.25e-04

CP train original_text seed=5 epoch=19:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=19 loss=0.0162 valid_AUC=0.9191 valid_FITB=0.5777 lr=1.25e-04

CP train original_text seed=5 epoch=20:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=20 loss=0.0149 valid_AUC=0.9186 valid_FITB=0.5803 lr=6.25e-05

CP train original_text seed=5 epoch=21:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=21 loss=0.0117 valid_AUC=0.9192 valid_FITB=0.5830 lr=6.25e-05

CP train original_text seed=5 epoch=22:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=22 loss=0.0123 valid_AUC=0.9187 valid_FITB=0.5830 lr=6.25e-05

CP train original_text seed=5 epoch=23:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=23 loss=0.0113 valid_AUC=0.9186 valid_FITB=0.5847 lr=3.13e-05

CP train original_text seed=5 epoch=24:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=24 loss=0.0108 valid_AUC=0.9189 valid_FITB=0.5797 lr=3.13e-05

CP train original_text seed=5 epoch=25:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=25 loss=0.0103 valid_AUC=0.9190 valid_FITB=0.5810 lr=3.13e-05

CP train original_text seed=5 epoch=26:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=26 loss=0.0096 valid_AUC=0.9186 valid_FITB=0.5800 lr=1.56e-05

CP train original_text seed=5 epoch=27:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=27 loss=0.0088 valid_AUC=0.9189 valid_FITB=0.5793 lr=1.56e-05

CP train original_text seed=5 epoch=28:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=28 loss=0.0090 valid_AUC=0.9190 valid_FITB=0.5810 lr=1.56e-05

CP train original_text seed=5 epoch=29:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=29 loss=0.0090 valid_AUC=0.9192 valid_FITB=0.5813 lr=7.81e-06

CP train original_text seed=5 epoch=30:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=30 loss=0.0088 valid_AUC=0.9191 valid_FITB=0.5797 lr=7.81e-06

CP train original_text seed=5 epoch=31:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=31 loss=0.0081 valid_AUC=0.9191 valid_FITB=0.5797 lr=7.81e-06

CP train original_text seed=5 epoch=32:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=32 loss=0.0085 valid_AUC=0.9191 valid_FITB=0.5797 lr=3.91e-06

CP train original_text seed=5 epoch=33:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=33 loss=0.0084 valid_AUC=0.9190 valid_FITB=0.5813 lr=3.91e-06

CP train original_text seed=5 epoch=34:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=34 loss=0.0084 valid_AUC=0.9191 valid_FITB=0.5813 lr=3.91e-06

CP train original_text seed=5 epoch=35:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=35 loss=0.0089 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.95e-06

CP train original_text seed=5 epoch=36:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=36 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.95e-06

CP train original_text seed=5 epoch=37:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=37 loss=0.0091 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.95e-06

CP train original_text seed=5 epoch=38:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=38 loss=0.0089 valid_AUC=0.9191 valid_FITB=0.5807 lr=9.77e-07

CP train original_text seed=5 epoch=39:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=39 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5797 lr=9.77e-07

CP train original_text seed=5 epoch=40:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=40 loss=0.0086 valid_AUC=0.9191 valid_FITB=0.5797 lr=9.77e-07

CP train original_text seed=5 epoch=41:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=41 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5803 lr=4.88e-07

CP train original_text seed=5 epoch=42:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=42 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5793 lr=4.88e-07

CP train original_text seed=5 epoch=43:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=43 loss=0.0081 valid_AUC=0.9191 valid_FITB=0.5800 lr=4.88e-07

CP train original_text seed=5 epoch=44:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=44 loss=0.0085 valid_AUC=0.9191 valid_FITB=0.5797 lr=2.44e-07

CP train original_text seed=5 epoch=45:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=45 loss=0.0080 valid_AUC=0.9191 valid_FITB=0.5803 lr=2.44e-07

CP train original_text seed=5 epoch=46:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=46 loss=0.0084 valid_AUC=0.9191 valid_FITB=0.5800 lr=2.44e-07

CP train original_text seed=5 epoch=47:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=47 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5800 lr=1.22e-07

CP train original_text seed=5 epoch=48:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=48 loss=0.0079 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.22e-07

CP train original_text seed=5 epoch=49:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=49 loss=0.0082 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.22e-07

CP train original_text seed=5 epoch=50:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=50 loss=0.0080 valid_AUC=0.9191 valid_FITB=0.5803 lr=6.10e-08

CP train original_text seed=5 epoch=51:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=51 loss=0.0078 valid_AUC=0.9191 valid_FITB=0.5803 lr=6.10e-08

CP train original_text seed=5 epoch=52:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=52 loss=0.0077 valid_AUC=0.9191 valid_FITB=0.5807 lr=6.10e-08

CP train original_text seed=5 epoch=53:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=53 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5810 lr=3.05e-08

CP train original_text seed=5 epoch=54:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=54 loss=0.0087 valid_AUC=0.9191 valid_FITB=0.5810 lr=3.05e-08

CP train original_text seed=5 epoch=55:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=55 loss=0.0089 valid_AUC=0.9191 valid_FITB=0.5810 lr=3.05e-08

CP train original_text seed=5 epoch=56:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=56 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=57:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=57 loss=0.0087 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=58:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=58 loss=0.0078 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=59:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=59 loss=0.0088 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=60:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=60 loss=0.0081 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=61:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=61 loss=0.0081 valid_AUC=0.9191 valid_FITB=0.5810 lr=1.53e-08

CP train original_text seed=5 epoch=62:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=62 loss=0.0079 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=63:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=63 loss=0.0084 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=64:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=64 loss=0.0081 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=65:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=65 loss=0.0082 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=66:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=66 loss=0.0084 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=67:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=67 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=68:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=68 loss=0.0085 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=69:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=69 loss=0.0082 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=70:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=70 loss=0.0079 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=71:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=71 loss=0.0082 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=72:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=72 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=73:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=73 loss=0.0086 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=74:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=74 loss=0.0085 valid_AUC=0.9191 valid_FITB=0.5807 lr=1.53e-08

CP train original_text seed=5 epoch=75:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=75 loss=0.0084 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=76:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=76 loss=0.0081 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=77:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=77 loss=0.0080 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=78:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=78 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=79:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=79 loss=0.0080 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=80:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=80 loss=0.0077 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=81:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=81 loss=0.0082 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=82:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=82 loss=0.0086 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=83:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=83 loss=0.0082 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=84:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=84 loss=0.0087 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=85:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=85 loss=0.0080 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=86:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=86 loss=0.0081 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=87:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=87 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=88:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=88 loss=0.0086 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=89:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=89 loss=0.0082 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=90:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=90 loss=0.0085 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=91:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=91 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=92:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=92 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=93:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=93 loss=0.0081 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=94:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=94 loss=0.0085 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=95:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=95 loss=0.0082 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=96:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=96 loss=0.0085 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=97:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=97 loss=0.0078 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=98:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=98 loss=0.0083 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=99:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=99 loss=0.0080 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP train original_text seed=5 epoch=100:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=100 loss=0.0077 valid_AUC=0.9191 valid_FITB=0.5803 lr=1.53e-08

CP FITB:   0%|          | 0/15145 [00:00<?, ?it/s]

[OR 訓練] variant=original_text, seed=5, train=16,995, valid=3,000

OR train original_text seed=5 epoch=1:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=01 loss=0.9421 valid_FITB=0.6200 lr=1.00e-03

OR train original_text seed=5 epoch=2:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=02 loss=0.7975 valid_FITB=0.6150 lr=1.00e-03

OR train original_text seed=5 epoch=3:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=03 loss=0.7090 valid_FITB=0.6120 lr=1.00e-03

OR train original_text seed=5 epoch=4:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=04 loss=0.5987 valid_FITB=0.6043 lr=5.00e-04

OR train original_text seed=5 epoch=5:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=05 loss=0.4469 valid_FITB=0.6083 lr=5.00e-04

OR train original_text seed=5 epoch=6:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=06 loss=0.3676 valid_FITB=0.5933 lr=5.00e-04

OR train original_text seed=5 epoch=7:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=07 loss=0.3040 valid_FITB=0.5957 lr=2.50e-04

OR train original_text seed=5 epoch=8:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=08 loss=0.2309 valid_FITB=0.6017 lr=2.50e-04

OR train original_text seed=5 epoch=9:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=09 loss=0.1963 valid_FITB=0.6003 lr=2.50e-04

OR train original_text seed=5 epoch=10:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=10 loss=0.1741 valid_FITB=0.5910 lr=1.25e-04

OR train original_text seed=5 epoch=11:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=11 loss=0.1494 valid_FITB=0.5960 lr=1.25e-04

OR train original_text seed=5 epoch=12:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=12 loss=0.1346 valid_FITB=0.5990 lr=1.25e-04

OR train original_text seed=5 epoch=13:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=13 loss=0.1255 valid_FITB=0.5960 lr=6.25e-05

OR train original_text seed=5 epoch=14:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=14 loss=0.1177 valid_FITB=0.5930 lr=6.25e-05

OR train original_text seed=5 epoch=15:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=15 loss=0.1116 valid_FITB=0.5920 lr=6.25e-05

OR train original_text seed=5 epoch=16:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=16 loss=0.1082 valid_FITB=0.5913 lr=3.13e-05

OR train original_text seed=5 epoch=17:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=17 loss=0.1027 valid_FITB=0.5920 lr=3.13e-05

OR train original_text seed=5 epoch=18:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=18 loss=0.1009 valid_FITB=0.5920 lr=3.13e-05

OR train original_text seed=5 epoch=19:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=19 loss=0.0990 valid_FITB=0.5927 lr=1.56e-05

OR train original_text seed=5 epoch=20:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=20 loss=0.0960 valid_FITB=0.5930 lr=1.56e-05

OR train original_text seed=5 epoch=21:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=21 loss=0.0964 valid_FITB=0.5923 lr=1.56e-05

OR train original_text seed=5 epoch=22:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=22 loss=0.0959 valid_FITB=0.5920 lr=7.81e-06

OR train original_text seed=5 epoch=23:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=23 loss=0.0926 valid_FITB=0.5923 lr=7.81e-06

OR train original_text seed=5 epoch=24:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=24 loss=0.0944 valid_FITB=0.5923 lr=7.81e-06

OR train original_text seed=5 epoch=25:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=25 loss=0.0938 valid_FITB=0.5923 lr=3.91e-06

OR train original_text seed=5 epoch=26:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=26 loss=0.0925 valid_FITB=0.5917 lr=3.91e-06

OR train original_text seed=5 epoch=27:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=27 loss=0.0935 valid_FITB=0.5913 lr=3.91e-06

OR train original_text seed=5 epoch=28:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=28 loss=0.0920 valid_FITB=0.5917 lr=1.95e-06

OR train original_text seed=5 epoch=29:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=29 loss=0.0921 valid_FITB=0.5913 lr=1.95e-06

OR train original_text seed=5 epoch=30:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=30 loss=0.0905 valid_FITB=0.5910 lr=1.95e-06

OR train original_text seed=5 epoch=31:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=31 loss=0.0923 valid_FITB=0.5917 lr=9.77e-07

OR train original_text seed=5 epoch=32:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=32 loss=0.0915 valid_FITB=0.5913 lr=9.77e-07

OR train original_text seed=5 epoch=33:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=33 loss=0.0915 valid_FITB=0.5913 lr=9.77e-07

OR train original_text seed=5 epoch=34:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=34 loss=0.0908 valid_FITB=0.5913 lr=4.88e-07

OR train original_text seed=5 epoch=35:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=35 loss=0.0933 valid_FITB=0.5910 lr=4.88e-07

OR train original_text seed=5 epoch=36:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=36 loss=0.0933 valid_FITB=0.5910 lr=4.88e-07

OR train original_text seed=5 epoch=37:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=37 loss=0.0923 valid_FITB=0.5913 lr=2.44e-07

OR train original_text seed=5 epoch=38:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=38 loss=0.0924 valid_FITB=0.5913 lr=2.44e-07

OR train original_text seed=5 epoch=39:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=39 loss=0.0916 valid_FITB=0.5917 lr=2.44e-07

OR train original_text seed=5 epoch=40:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=40 loss=0.0912 valid_FITB=0.5917 lr=1.22e-07

OR train original_text seed=5 epoch=41:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=41 loss=0.0907 valid_FITB=0.5917 lr=1.22e-07

OR train original_text seed=5 epoch=42:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=42 loss=0.0930 valid_FITB=0.5917 lr=1.22e-07

OR train original_text seed=5 epoch=43:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=43 loss=0.0910 valid_FITB=0.5917 lr=6.10e-08

OR train original_text seed=5 epoch=44:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=44 loss=0.0914 valid_FITB=0.5917 lr=6.10e-08

OR train original_text seed=5 epoch=45:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=45 loss=0.0940 valid_FITB=0.5917 lr=6.10e-08

OR train original_text seed=5 epoch=46:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=46 loss=0.0928 valid_FITB=0.5917 lr=3.05e-08

OR train original_text seed=5 epoch=47:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=47 loss=0.0900 valid_FITB=0.5917 lr=3.05e-08

OR train original_text seed=5 epoch=48:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=48 loss=0.0914 valid_FITB=0.5917 lr=3.05e-08

OR train original_text seed=5 epoch=49:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=49 loss=0.0920 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=50:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=50 loss=0.0920 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=51:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=51 loss=0.0909 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=52:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=52 loss=0.0917 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=53:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=53 loss=0.0906 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=54:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=54 loss=0.0924 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=55:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=55 loss=0.0927 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=56:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=56 loss=0.0921 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=57:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=57 loss=0.0919 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=58:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=58 loss=0.0925 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=59:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=59 loss=0.0915 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=60:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=60 loss=0.0917 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=61:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=61 loss=0.0922 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=62:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=62 loss=0.0918 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=63:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=63 loss=0.0937 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=64:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=64 loss=0.0915 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=65:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=65 loss=0.0919 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=66:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=66 loss=0.0924 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=67:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=67 loss=0.0906 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=68:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=68 loss=0.0915 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=69:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=69 loss=0.0908 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=70:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=70 loss=0.0901 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=71:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=71 loss=0.0887 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=72:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=72 loss=0.0921 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=73:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=73 loss=0.0933 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=74:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=74 loss=0.0909 valid_FITB=0.5917 lr=1.53e-08

OR train original_text seed=5 epoch=75:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=75 loss=0.0896 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=76:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=76 loss=0.0922 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=77:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=77 loss=0.0915 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=78:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=78 loss=0.0914 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=79:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=79 loss=0.0915 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=80:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=80 loss=0.0921 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=81:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=81 loss=0.0901 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=82:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=82 loss=0.0911 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=83:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=83 loss=0.0909 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=84:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=84 loss=0.0921 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=85:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=85 loss=0.0911 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=86:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=86 loss=0.0917 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=87:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=87 loss=0.0935 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=88:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=88 loss=0.0930 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=89:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=89 loss=0.0919 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=90:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=90 loss=0.0916 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=91:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=91 loss=0.0905 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=92:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=92 loss=0.0900 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=93:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=93 loss=0.0918 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=94:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=94 loss=0.0912 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=95:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=95 loss=0.0912 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=96:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=96 loss=0.0908 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=97:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=97 loss=0.0907 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=98:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=98 loss=0.0909 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=99:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=99 loss=0.0924 valid_FITB=0.5913 lr=1.53e-08

OR train original_text seed=5 epoch=100:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=100 loss=0.0916 valid_FITB=0.5913 lr=1.53e-08

encode candidate pools [original_text seed=5]:   0%|          | 0/19 [00:00<?, ?it/s]

OR/CIR recall [original_text seed=5]:   0%|          | 0/15145 [00:00<?, ?it/s]

[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/original_text/seed_5/seed_summary.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/original_text/seed_5/or_recall_rowlevel.csv

[context_aware_description] outfit text embedding 筆數：35,140
  CP train: usable=33,990, missing=0
  CP valid: usable=6,000, missing=0
  CP test: usable=30,290, missing=0
  FITB train: usable=16,995, missing=0
  FITB valid: usable=3,000, missing=0
  FITB test: usable=15,145, missing=0

[CP 訓練] variant=context_aware_description, seed=1, train=33,990, valid=6,000

CP train context_aware_description seed=1 epoch=1:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=01 loss=0.6073 valid_AUC=0.8505 valid_FITB=0.4277 lr=1.00e-03

CP train context_aware_description seed=1 epoch=2:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=02 loss=0.4524 valid_AUC=0.8837 valid_FITB=0.4673 lr=1.00e-03

CP train context_aware_description seed=1 epoch=3:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=03 loss=0.4040 valid_AUC=0.8930 valid_FITB=0.4783 lr=1.00e-03

CP train context_aware_description seed=1 epoch=4:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=04 loss=0.3624 valid_AUC=0.9023 valid_FITB=0.4980 lr=1.00e-03

CP train context_aware_description seed=1 epoch=5:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=05 loss=0.3256 valid_AUC=0.9163 valid_FITB=0.5237 lr=1.00e-03

CP train context_aware_description seed=1 epoch=6:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=06 loss=0.2854 valid_AUC=0.9198 valid_FITB=0.5360 lr=1.00e-03

CP train context_aware_description seed=1 epoch=7:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=07 loss=0.2599 valid_AUC=0.9209 valid_FITB=0.5293 lr=1.00e-03

CP train context_aware_description seed=1 epoch=8:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=08 loss=0.2248 valid_AUC=0.9245 valid_FITB=0.5403 lr=1.00e-03

CP train context_aware_description seed=1 epoch=9:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=09 loss=0.2002 valid_AUC=0.9310 valid_FITB=0.5510 lr=1.00e-03

CP train context_aware_description seed=1 epoch=10:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=10 loss=0.1737 valid_AUC=0.9299 valid_FITB=0.5500 lr=1.00e-03

CP train context_aware_description seed=1 epoch=11:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=11 loss=0.1516 valid_AUC=0.9319 valid_FITB=0.5537 lr=1.00e-03

CP train context_aware_description seed=1 epoch=12:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=12 loss=0.1325 valid_AUC=0.9268 valid_FITB=0.5560 lr=1.00e-03

CP train context_aware_description seed=1 epoch=13:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=13 loss=0.1149 valid_AUC=0.9299 valid_FITB=0.5470 lr=1.00e-03

CP train context_aware_description seed=1 epoch=14:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=14 loss=0.1025 valid_AUC=0.9365 valid_FITB=0.5593 lr=1.00e-03

CP train context_aware_description seed=1 epoch=15:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=15 loss=0.0898 valid_AUC=0.9333 valid_FITB=0.5493 lr=1.00e-03

CP train context_aware_description seed=1 epoch=16:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=16 loss=0.0861 valid_AUC=0.9353 valid_FITB=0.5630 lr=1.00e-03

CP train context_aware_description seed=1 epoch=17:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=17 loss=0.0736 valid_AUC=0.9367 valid_FITB=0.5620 lr=1.00e-03

CP train context_aware_description seed=1 epoch=18:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=18 loss=0.0709 valid_AUC=0.9340 valid_FITB=0.5597 lr=1.00e-03

CP train context_aware_description seed=1 epoch=19:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=19 loss=0.0637 valid_AUC=0.9331 valid_FITB=0.5603 lr=5.00e-04

CP train context_aware_description seed=1 epoch=20:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=20 loss=0.0312 valid_AUC=0.9400 valid_FITB=0.5617 lr=5.00e-04

CP train context_aware_description seed=1 epoch=21:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=21 loss=0.0194 valid_AUC=0.9415 valid_FITB=0.5677 lr=5.00e-04

CP train context_aware_description seed=1 epoch=22:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=22 loss=0.0165 valid_AUC=0.9418 valid_FITB=0.5673 lr=5.00e-04

CP train context_aware_description seed=1 epoch=23:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=23 loss=0.0159 valid_AUC=0.9408 valid_FITB=0.5673 lr=5.00e-04

CP train context_aware_description seed=1 epoch=24:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=24 loss=0.0144 valid_AUC=0.9406 valid_FITB=0.5657 lr=2.50e-04

CP train context_aware_description seed=1 epoch=25:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=25 loss=0.0095 valid_AUC=0.9419 valid_FITB=0.5647 lr=2.50e-04

CP train context_aware_description seed=1 epoch=26:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=26 loss=0.0072 valid_AUC=0.9420 valid_FITB=0.5613 lr=2.50e-04

CP train context_aware_description seed=1 epoch=27:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=27 loss=0.0072 valid_AUC=0.9406 valid_FITB=0.5610 lr=1.25e-04

CP train context_aware_description seed=1 epoch=28:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=28 loss=0.0051 valid_AUC=0.9415 valid_FITB=0.5673 lr=1.25e-04

CP train context_aware_description seed=1 epoch=29:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=29 loss=0.0043 valid_AUC=0.9415 valid_FITB=0.5637 lr=1.25e-04

CP train context_aware_description seed=1 epoch=30:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=30 loss=0.0041 valid_AUC=0.9423 valid_FITB=0.5630 lr=6.25e-05

CP train context_aware_description seed=1 epoch=31:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=31 loss=0.0039 valid_AUC=0.9420 valid_FITB=0.5677 lr=6.25e-05

CP train context_aware_description seed=1 epoch=32:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=32 loss=0.0037 valid_AUC=0.9415 valid_FITB=0.5673 lr=6.25e-05

CP train context_aware_description seed=1 epoch=33:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=33 loss=0.0036 valid_AUC=0.9419 valid_FITB=0.5630 lr=3.13e-05

CP train context_aware_description seed=1 epoch=34:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=34 loss=0.0033 valid_AUC=0.9420 valid_FITB=0.5653 lr=3.13e-05

CP train context_aware_description seed=1 epoch=35:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=35 loss=0.0028 valid_AUC=0.9418 valid_FITB=0.5647 lr=3.13e-05

CP train context_aware_description seed=1 epoch=36:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=36 loss=0.0030 valid_AUC=0.9419 valid_FITB=0.5667 lr=1.56e-05

CP train context_aware_description seed=1 epoch=37:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=37 loss=0.0025 valid_AUC=0.9420 valid_FITB=0.5653 lr=1.56e-05

CP train context_aware_description seed=1 epoch=38:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=38 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5637 lr=1.56e-05

CP train context_aware_description seed=1 epoch=39:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=39 loss=0.0029 valid_AUC=0.9421 valid_FITB=0.5650 lr=7.81e-06

CP train context_aware_description seed=1 epoch=40:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=40 loss=0.0024 valid_AUC=0.9421 valid_FITB=0.5650 lr=7.81e-06

CP train context_aware_description seed=1 epoch=41:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=41 loss=0.0026 valid_AUC=0.9421 valid_FITB=0.5653 lr=7.81e-06

CP train context_aware_description seed=1 epoch=42:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=42 loss=0.0025 valid_AUC=0.9420 valid_FITB=0.5650 lr=3.91e-06

CP train context_aware_description seed=1 epoch=43:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=43 loss=0.0025 valid_AUC=0.9420 valid_FITB=0.5633 lr=3.91e-06

CP train context_aware_description seed=1 epoch=44:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=44 loss=0.0026 valid_AUC=0.9420 valid_FITB=0.5660 lr=3.91e-06

CP train context_aware_description seed=1 epoch=45:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=45 loss=0.0027 valid_AUC=0.9421 valid_FITB=0.5643 lr=1.95e-06

CP train context_aware_description seed=1 epoch=46:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=46 loss=0.0025 valid_AUC=0.9420 valid_FITB=0.5650 lr=1.95e-06

CP train context_aware_description seed=1 epoch=47:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=47 loss=0.0031 valid_AUC=0.9420 valid_FITB=0.5640 lr=1.95e-06

CP train context_aware_description seed=1 epoch=48:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=48 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5643 lr=9.77e-07

CP train context_aware_description seed=1 epoch=49:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=49 loss=0.0027 valid_AUC=0.9420 valid_FITB=0.5640 lr=9.77e-07

CP train context_aware_description seed=1 epoch=50:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=50 loss=0.0025 valid_AUC=0.9420 valid_FITB=0.5640 lr=9.77e-07

CP train context_aware_description seed=1 epoch=51:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=51 loss=0.0026 valid_AUC=0.9420 valid_FITB=0.5643 lr=4.88e-07

CP train context_aware_description seed=1 epoch=52:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=52 loss=0.0026 valid_AUC=0.9420 valid_FITB=0.5643 lr=4.88e-07

CP train context_aware_description seed=1 epoch=53:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=53 loss=0.0028 valid_AUC=0.9420 valid_FITB=0.5643 lr=4.88e-07

CP train context_aware_description seed=1 epoch=54:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=54 loss=0.0024 valid_AUC=0.9420 valid_FITB=0.5643 lr=2.44e-07

CP train context_aware_description seed=1 epoch=55:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=55 loss=0.0027 valid_AUC=0.9420 valid_FITB=0.5643 lr=2.44e-07

CP train context_aware_description seed=1 epoch=56:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=56 loss=0.0030 valid_AUC=0.9420 valid_FITB=0.5643 lr=2.44e-07

CP train context_aware_description seed=1 epoch=57:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=57 loss=0.0024 valid_AUC=0.9420 valid_FITB=0.5643 lr=1.22e-07

CP train context_aware_description seed=1 epoch=58:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=58 loss=0.0027 valid_AUC=0.9421 valid_FITB=0.5643 lr=1.22e-07

CP train context_aware_description seed=1 epoch=59:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=59 loss=0.0024 valid_AUC=0.9421 valid_FITB=0.5643 lr=1.22e-07

CP train context_aware_description seed=1 epoch=60:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=60 loss=0.0026 valid_AUC=0.9421 valid_FITB=0.5643 lr=6.10e-08

CP train context_aware_description seed=1 epoch=61:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=61 loss=0.0026 valid_AUC=0.9421 valid_FITB=0.5643 lr=6.10e-08

CP train context_aware_description seed=1 epoch=62:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=62 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5643 lr=6.10e-08

CP train context_aware_description seed=1 epoch=63:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=63 loss=0.0022 valid_AUC=0.9421 valid_FITB=0.5640 lr=3.05e-08

CP train context_aware_description seed=1 epoch=64:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=64 loss=0.0024 valid_AUC=0.9421 valid_FITB=0.5640 lr=3.05e-08

CP train context_aware_description seed=1 epoch=65:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=65 loss=0.0026 valid_AUC=0.9421 valid_FITB=0.5640 lr=3.05e-08

CP train context_aware_description seed=1 epoch=66:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=66 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=67:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=67 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=68:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=68 loss=0.0023 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=69:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=69 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=70:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=70 loss=0.0027 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=71:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=71 loss=0.0026 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=72:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=72 loss=0.0022 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=73:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=73 loss=0.0023 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=74:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=74 loss=0.0027 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=75:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=75 loss=0.0023 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=76:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=76 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=77:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=77 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=78:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=78 loss=0.0024 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=79:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=79 loss=0.0027 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=80:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=80 loss=0.0027 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=81:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=81 loss=0.0026 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=82:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=82 loss=0.0026 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=83:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=83 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=84:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=84 loss=0.0026 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=85:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=85 loss=0.0026 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=86:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=86 loss=0.0023 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=87:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=87 loss=0.0027 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=88:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=88 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=89:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=89 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=90:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=90 loss=0.0026 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=91:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=91 loss=0.0026 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=92:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=92 loss=0.0024 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=93:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=93 loss=0.0023 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=94:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=94 loss=0.0027 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=95:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=95 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=96:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=96 loss=0.0024 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=97:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=97 loss=0.0022 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=98:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=98 loss=0.0028 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=99:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=99 loss=0.0022 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP train context_aware_description seed=1 epoch=100:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=100 loss=0.0025 valid_AUC=0.9421 valid_FITB=0.5640 lr=1.53e-08

CP FITB:   0%|          | 0/15145 [00:00<?, ?it/s]

[OR 訓練] variant=context_aware_description, seed=1, train=16,995, valid=3,000

OR train context_aware_description seed=1 epoch=1:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=01 loss=0.9311 valid_FITB=0.6203 lr=1.00e-03

OR train context_aware_description seed=1 epoch=2:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=02 loss=0.7777 valid_FITB=0.6203 lr=1.00e-03

OR train context_aware_description seed=1 epoch=3:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=03 loss=0.6798 valid_FITB=0.6300 lr=1.00e-03

OR train context_aware_description seed=1 epoch=4:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=04 loss=0.5894 valid_FITB=0.6337 lr=1.00e-03

OR train context_aware_description seed=1 epoch=5:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=05 loss=0.5022 valid_FITB=0.6377 lr=1.00e-03

OR train context_aware_description seed=1 epoch=6:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=06 loss=0.4143 valid_FITB=0.6237 lr=1.00e-03

OR train context_aware_description seed=1 epoch=7:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=07 loss=0.3378 valid_FITB=0.6170 lr=1.00e-03

OR train context_aware_description seed=1 epoch=8:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=08 loss=0.2644 valid_FITB=0.6153 lr=5.00e-04

OR train context_aware_description seed=1 epoch=9:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=09 loss=0.1741 valid_FITB=0.6250 lr=5.00e-04

OR train context_aware_description seed=1 epoch=10:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=10 loss=0.1319 valid_FITB=0.6220 lr=5.00e-04

OR train context_aware_description seed=1 epoch=11:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=11 loss=0.1093 valid_FITB=0.6143 lr=2.50e-04

OR train context_aware_description seed=1 epoch=12:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=12 loss=0.0852 valid_FITB=0.6170 lr=2.50e-04

OR train context_aware_description seed=1 epoch=13:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=13 loss=0.0713 valid_FITB=0.6250 lr=2.50e-04

OR train context_aware_description seed=1 epoch=14:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=14 loss=0.0648 valid_FITB=0.6180 lr=1.25e-04

OR train context_aware_description seed=1 epoch=15:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=15 loss=0.0558 valid_FITB=0.6200 lr=1.25e-04

OR train context_aware_description seed=1 epoch=16:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=16 loss=0.0524 valid_FITB=0.6157 lr=1.25e-04

OR train context_aware_description seed=1 epoch=17:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=17 loss=0.0518 valid_FITB=0.6137 lr=6.25e-05

OR train context_aware_description seed=1 epoch=18:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=18 loss=0.0460 valid_FITB=0.6153 lr=6.25e-05

OR train context_aware_description seed=1 epoch=19:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=19 loss=0.0444 valid_FITB=0.6140 lr=6.25e-05

OR train context_aware_description seed=1 epoch=20:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=20 loss=0.0438 valid_FITB=0.6157 lr=3.13e-05

OR train context_aware_description seed=1 epoch=21:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=21 loss=0.0430 valid_FITB=0.6160 lr=3.13e-05

OR train context_aware_description seed=1 epoch=22:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=22 loss=0.0426 valid_FITB=0.6160 lr=3.13e-05

OR train context_aware_description seed=1 epoch=23:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=23 loss=0.0415 valid_FITB=0.6163 lr=1.56e-05

OR train context_aware_description seed=1 epoch=24:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=24 loss=0.0403 valid_FITB=0.6167 lr=1.56e-05

OR train context_aware_description seed=1 epoch=25:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=25 loss=0.0407 valid_FITB=0.6157 lr=1.56e-05

OR train context_aware_description seed=1 epoch=26:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=26 loss=0.0391 valid_FITB=0.6173 lr=7.81e-06

OR train context_aware_description seed=1 epoch=27:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=27 loss=0.0393 valid_FITB=0.6163 lr=7.81e-06

OR train context_aware_description seed=1 epoch=28:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=28 loss=0.0392 valid_FITB=0.6153 lr=7.81e-06

OR train context_aware_description seed=1 epoch=29:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=29 loss=0.0389 valid_FITB=0.6167 lr=3.91e-06

OR train context_aware_description seed=1 epoch=30:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=30 loss=0.0384 valid_FITB=0.6177 lr=3.91e-06

OR train context_aware_description seed=1 epoch=31:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=31 loss=0.0396 valid_FITB=0.6160 lr=3.91e-06

OR train context_aware_description seed=1 epoch=32:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=32 loss=0.0380 valid_FITB=0.6170 lr=1.95e-06

OR train context_aware_description seed=1 epoch=33:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=33 loss=0.0384 valid_FITB=0.6157 lr=1.95e-06

OR train context_aware_description seed=1 epoch=34:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=34 loss=0.0378 valid_FITB=0.6160 lr=1.95e-06

OR train context_aware_description seed=1 epoch=35:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=35 loss=0.0386 valid_FITB=0.6160 lr=9.77e-07

OR train context_aware_description seed=1 epoch=36:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=36 loss=0.0378 valid_FITB=0.6150 lr=9.77e-07

OR train context_aware_description seed=1 epoch=37:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=37 loss=0.0376 valid_FITB=0.6157 lr=9.77e-07

OR train context_aware_description seed=1 epoch=38:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=38 loss=0.0388 valid_FITB=0.6153 lr=4.88e-07

OR train context_aware_description seed=1 epoch=39:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=39 loss=0.0394 valid_FITB=0.6153 lr=4.88e-07

OR train context_aware_description seed=1 epoch=40:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=40 loss=0.0394 valid_FITB=0.6157 lr=4.88e-07

OR train context_aware_description seed=1 epoch=41:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=41 loss=0.0377 valid_FITB=0.6153 lr=2.44e-07

OR train context_aware_description seed=1 epoch=42:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=42 loss=0.0380 valid_FITB=0.6157 lr=2.44e-07

OR train context_aware_description seed=1 epoch=43:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=43 loss=0.0379 valid_FITB=0.6157 lr=2.44e-07

OR train context_aware_description seed=1 epoch=44:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=44 loss=0.0389 valid_FITB=0.6153 lr=1.22e-07

OR train context_aware_description seed=1 epoch=45:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=45 loss=0.0383 valid_FITB=0.6153 lr=1.22e-07

OR train context_aware_description seed=1 epoch=46:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=46 loss=0.0380 valid_FITB=0.6153 lr=1.22e-07

OR train context_aware_description seed=1 epoch=47:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=47 loss=0.0386 valid_FITB=0.6153 lr=6.10e-08

OR train context_aware_description seed=1 epoch=48:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=48 loss=0.0380 valid_FITB=0.6153 lr=6.10e-08

OR train context_aware_description seed=1 epoch=49:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=49 loss=0.0380 valid_FITB=0.6153 lr=6.10e-08

OR train context_aware_description seed=1 epoch=50:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=50 loss=0.0392 valid_FITB=0.6153 lr=3.05e-08

OR train context_aware_description seed=1 epoch=51:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=51 loss=0.0383 valid_FITB=0.6153 lr=3.05e-08

OR train context_aware_description seed=1 epoch=52:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=52 loss=0.0387 valid_FITB=0.6153 lr=3.05e-08

OR train context_aware_description seed=1 epoch=53:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=53 loss=0.0376 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=54:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=54 loss=0.0378 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=55:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=55 loss=0.0384 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=56:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=56 loss=0.0378 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=57:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=57 loss=0.0383 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=58:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=58 loss=0.0382 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=59:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=59 loss=0.0387 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=60:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=60 loss=0.0387 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=61:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=61 loss=0.0378 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=62:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=62 loss=0.0370 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=63:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=63 loss=0.0380 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=64:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=64 loss=0.0384 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=65:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=65 loss=0.0387 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=66:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=66 loss=0.0386 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=67:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=67 loss=0.0390 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=68:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=68 loss=0.0392 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=69:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=69 loss=0.0384 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=70:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=70 loss=0.0389 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=71:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=71 loss=0.0391 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=72:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=72 loss=0.0384 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=73:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=73 loss=0.0374 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=74:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=74 loss=0.0386 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=75:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=75 loss=0.0375 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=76:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=76 loss=0.0380 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=77:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=77 loss=0.0380 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=78:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=78 loss=0.0368 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=79:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=79 loss=0.0390 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=80:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=80 loss=0.0391 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=81:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=81 loss=0.0389 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=82:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=82 loss=0.0378 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=83:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=83 loss=0.0375 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=84:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=84 loss=0.0386 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=85:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=85 loss=0.0383 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=86:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=86 loss=0.0383 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=87:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=87 loss=0.0386 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=88:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=88 loss=0.0378 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=89:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=89 loss=0.0400 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=90:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=90 loss=0.0400 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=91:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=91 loss=0.0389 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=92:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=92 loss=0.0386 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=93:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=93 loss=0.0397 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=94:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=94 loss=0.0372 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=95:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=95 loss=0.0388 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=96:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=96 loss=0.0386 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=97:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=97 loss=0.0380 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=98:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=98 loss=0.0378 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=99:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=99 loss=0.0384 valid_FITB=0.6153 lr=1.53e-08

OR train context_aware_description seed=1 epoch=100:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=100 loss=0.0392 valid_FITB=0.6153 lr=1.53e-08

encode candidate pools [context_aware_description seed=1]:   0%|          | 0/19 [00:00<?, ?it/s]

OR/CIR recall [context_aware_description seed=1]:   0%|          | 0/15145 [00:00<?, ?it/s]

[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/context_aware_description/seed_1/seed_summary.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/context_aware_description/seed_1/or_recall_rowlevel.csv

[CP 訓練] variant=context_aware_description, seed=2, train=33,990, valid=6,000

CP train context_aware_description seed=2 epoch=1:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=01 loss=0.6062 valid_AUC=0.8522 valid_FITB=0.4347 lr=1.00e-03

CP train context_aware_description seed=2 epoch=2:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=02 loss=0.4502 valid_AUC=0.8762 valid_FITB=0.4633 lr=1.00e-03

CP train context_aware_description seed=2 epoch=3:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=03 loss=0.4029 valid_AUC=0.9002 valid_FITB=0.4880 lr=1.00e-03

CP train context_aware_description seed=2 epoch=4:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=04 loss=0.3608 valid_AUC=0.9063 valid_FITB=0.5180 lr=1.00e-03

CP train context_aware_description seed=2 epoch=5:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=05 loss=0.3195 valid_AUC=0.9187 valid_FITB=0.5357 lr=1.00e-03

CP train context_aware_description seed=2 epoch=6:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=06 loss=0.2816 valid_AUC=0.9238 valid_FITB=0.5353 lr=1.00e-03

CP train context_aware_description seed=2 epoch=7:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=07 loss=0.2480 valid_AUC=0.9244 valid_FITB=0.5483 lr=1.00e-03

CP train context_aware_description seed=2 epoch=8:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=08 loss=0.2197 valid_AUC=0.9264 valid_FITB=0.5447 lr=1.00e-03

CP train context_aware_description seed=2 epoch=9:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=09 loss=0.1962 valid_AUC=0.9278 valid_FITB=0.5597 lr=1.00e-03

CP train context_aware_description seed=2 epoch=10:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=10 loss=0.1708 valid_AUC=0.9329 valid_FITB=0.5593 lr=1.00e-03

CP train context_aware_description seed=2 epoch=11:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=11 loss=0.1373 valid_AUC=0.9379 valid_FITB=0.5610 lr=1.00e-03

CP train context_aware_description seed=2 epoch=12:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=12 loss=0.1320 valid_AUC=0.9356 valid_FITB=0.5587 lr=1.00e-03

CP train context_aware_description seed=2 epoch=13:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=13 loss=0.1074 valid_AUC=0.9318 valid_FITB=0.5530 lr=1.00e-03

CP train context_aware_description seed=2 epoch=14:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=14 loss=0.1072 valid_AUC=0.9323 valid_FITB=0.5490 lr=5.00e-04

CP train context_aware_description seed=2 epoch=15:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=15 loss=0.0555 valid_AUC=0.9416 valid_FITB=0.5623 lr=5.00e-04

CP train context_aware_description seed=2 epoch=16:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=16 loss=0.0380 valid_AUC=0.9400 valid_FITB=0.5510 lr=5.00e-04

CP train context_aware_description seed=2 epoch=17:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=17 loss=0.0330 valid_AUC=0.9410 valid_FITB=0.5587 lr=5.00e-04

CP train context_aware_description seed=2 epoch=18:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=18 loss=0.0286 valid_AUC=0.9394 valid_FITB=0.5607 lr=2.50e-04

CP train context_aware_description seed=2 epoch=19:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=19 loss=0.0184 valid_AUC=0.9419 valid_FITB=0.5600 lr=2.50e-04

CP train context_aware_description seed=2 epoch=20:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=20 loss=0.0155 valid_AUC=0.9433 valid_FITB=0.5637 lr=2.50e-04

CP train context_aware_description seed=2 epoch=21:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=21 loss=0.0124 valid_AUC=0.9432 valid_FITB=0.5633 lr=2.50e-04

CP train context_aware_description seed=2 epoch=22:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=22 loss=0.0118 valid_AUC=0.9420 valid_FITB=0.5603 lr=2.50e-04

CP train context_aware_description seed=2 epoch=23:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=23 loss=0.0112 valid_AUC=0.9431 valid_FITB=0.5627 lr=1.25e-04

CP train context_aware_description seed=2 epoch=24:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=24 loss=0.0085 valid_AUC=0.9434 valid_FITB=0.5627 lr=1.25e-04

CP train context_aware_description seed=2 epoch=25:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=25 loss=0.0074 valid_AUC=0.9429 valid_FITB=0.5583 lr=1.25e-04

CP train context_aware_description seed=2 epoch=26:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=26 loss=0.0060 valid_AUC=0.9433 valid_FITB=0.5550 lr=6.25e-05

CP train context_aware_description seed=2 epoch=27:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=27 loss=0.0059 valid_AUC=0.9434 valid_FITB=0.5567 lr=6.25e-05

CP train context_aware_description seed=2 epoch=28:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=28 loss=0.0049 valid_AUC=0.9430 valid_FITB=0.5537 lr=6.25e-05

CP train context_aware_description seed=2 epoch=29:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=29 loss=0.0051 valid_AUC=0.9429 valid_FITB=0.5560 lr=3.13e-05

CP train context_aware_description seed=2 epoch=30:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=30 loss=0.0045 valid_AUC=0.9434 valid_FITB=0.5573 lr=3.13e-05

CP train context_aware_description seed=2 epoch=31:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=31 loss=0.0046 valid_AUC=0.9431 valid_FITB=0.5580 lr=3.13e-05

CP train context_aware_description seed=2 epoch=32:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=32 loss=0.0042 valid_AUC=0.9432 valid_FITB=0.5563 lr=1.56e-05

CP train context_aware_description seed=2 epoch=33:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=33 loss=0.0040 valid_AUC=0.9432 valid_FITB=0.5573 lr=1.56e-05

CP train context_aware_description seed=2 epoch=34:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=34 loss=0.0039 valid_AUC=0.9433 valid_FITB=0.5560 lr=1.56e-05

CP train context_aware_description seed=2 epoch=35:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=35 loss=0.0044 valid_AUC=0.9429 valid_FITB=0.5560 lr=7.81e-06

CP train context_aware_description seed=2 epoch=36:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=36 loss=0.0040 valid_AUC=0.9433 valid_FITB=0.5543 lr=7.81e-06

CP train context_aware_description seed=2 epoch=37:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=37 loss=0.0044 valid_AUC=0.9433 valid_FITB=0.5547 lr=7.81e-06

CP train context_aware_description seed=2 epoch=38:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=38 loss=0.0042 valid_AUC=0.9433 valid_FITB=0.5517 lr=3.91e-06

CP train context_aware_description seed=2 epoch=39:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=39 loss=0.0039 valid_AUC=0.9434 valid_FITB=0.5537 lr=3.91e-06

CP train context_aware_description seed=2 epoch=40:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=40 loss=0.0037 valid_AUC=0.9433 valid_FITB=0.5530 lr=3.91e-06

CP train context_aware_description seed=2 epoch=41:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=41 loss=0.0036 valid_AUC=0.9433 valid_FITB=0.5533 lr=1.95e-06

CP train context_aware_description seed=2 epoch=42:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=42 loss=0.0037 valid_AUC=0.9433 valid_FITB=0.5530 lr=1.95e-06

CP train context_aware_description seed=2 epoch=43:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=43 loss=0.0039 valid_AUC=0.9433 valid_FITB=0.5537 lr=1.95e-06

CP train context_aware_description seed=2 epoch=44:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=44 loss=0.0040 valid_AUC=0.9433 valid_FITB=0.5540 lr=9.77e-07

CP train context_aware_description seed=2 epoch=45:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=45 loss=0.0038 valid_AUC=0.9433 valid_FITB=0.5533 lr=9.77e-07

CP train context_aware_description seed=2 epoch=46:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=46 loss=0.0035 valid_AUC=0.9433 valid_FITB=0.5533 lr=9.77e-07

CP train context_aware_description seed=2 epoch=47:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=47 loss=0.0038 valid_AUC=0.9433 valid_FITB=0.5533 lr=4.88e-07

CP train context_aware_description seed=2 epoch=48:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=48 loss=0.0037 valid_AUC=0.9433 valid_FITB=0.5537 lr=4.88e-07

CP train context_aware_description seed=2 epoch=49:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=49 loss=0.0039 valid_AUC=0.9434 valid_FITB=0.5543 lr=4.88e-07

CP train context_aware_description seed=2 epoch=50:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=50 loss=0.0035 valid_AUC=0.9434 valid_FITB=0.5543 lr=2.44e-07

CP train context_aware_description seed=2 epoch=51:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=51 loss=0.0038 valid_AUC=0.9434 valid_FITB=0.5540 lr=2.44e-07

CP train context_aware_description seed=2 epoch=52:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=52 loss=0.0039 valid_AUC=0.9434 valid_FITB=0.5537 lr=2.44e-07

CP train context_aware_description seed=2 epoch=53:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=53 loss=0.0037 valid_AUC=0.9434 valid_FITB=0.5533 lr=1.22e-07

CP train context_aware_description seed=2 epoch=54:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=54 loss=0.0037 valid_AUC=0.9434 valid_FITB=0.5533 lr=1.22e-07

CP train context_aware_description seed=2 epoch=55:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=55 loss=0.0037 valid_AUC=0.9434 valid_FITB=0.5533 lr=1.22e-07

CP train context_aware_description seed=2 epoch=56:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=56 loss=0.0035 valid_AUC=0.9434 valid_FITB=0.5537 lr=6.10e-08

CP train context_aware_description seed=2 epoch=57:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=57 loss=0.0035 valid_AUC=0.9434 valid_FITB=0.5537 lr=6.10e-08

CP train context_aware_description seed=2 epoch=58:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=58 loss=0.0037 valid_AUC=0.9434 valid_FITB=0.5537 lr=6.10e-08

CP train context_aware_description seed=2 epoch=59:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=59 loss=0.0036 valid_AUC=0.9434 valid_FITB=0.5537 lr=3.05e-08

CP train context_aware_description seed=2 epoch=60:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=60 loss=0.0038 valid_AUC=0.9434 valid_FITB=0.5537 lr=3.05e-08

CP train context_aware_description seed=2 epoch=61:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=61 loss=0.0037 valid_AUC=0.9434 valid_FITB=0.5537 lr=3.05e-08

CP train context_aware_description seed=2 epoch=62:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=62 loss=0.0041 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=63:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=63 loss=0.0040 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=64:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=64 loss=0.0037 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=65:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=65 loss=0.0036 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=66:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=66 loss=0.0035 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=67:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=67 loss=0.0035 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=68:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=68 loss=0.0038 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=69:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=69 loss=0.0041 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=70:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=70 loss=0.0038 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=71:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=71 loss=0.0036 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=72:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=72 loss=0.0036 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=73:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=73 loss=0.0041 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=74:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=74 loss=0.0035 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=75:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=75 loss=0.0038 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=76:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=76 loss=0.0040 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=77:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=77 loss=0.0036 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=78:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=78 loss=0.0039 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=79:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=79 loss=0.0040 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=80:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=80 loss=0.0038 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=81:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=81 loss=0.0034 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=82:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=82 loss=0.0031 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=83:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=83 loss=0.0037 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=84:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=84 loss=0.0037 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=85:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=85 loss=0.0039 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=86:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=86 loss=0.0040 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=87:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=87 loss=0.0041 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=88:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=88 loss=0.0037 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=89:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=89 loss=0.0040 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=90:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=90 loss=0.0032 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=91:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=91 loss=0.0039 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=92:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=92 loss=0.0038 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=93:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=93 loss=0.0036 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=94:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=94 loss=0.0034 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=95:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=95 loss=0.0032 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=96:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=96 loss=0.0038 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=97:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=97 loss=0.0039 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=98:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=98 loss=0.0038 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=99:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=99 loss=0.0037 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=2 epoch=100:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=100 loss=0.0036 valid_AUC=0.9434 valid_FITB=0.5537 lr=1.53e-08

CP FITB:   0%|          | 0/15145 [00:00<?, ?it/s]

[OR 訓練] variant=context_aware_description, seed=2, train=16,995, valid=3,000

OR train context_aware_description seed=2 epoch=1:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=01 loss=0.9390 valid_FITB=0.6213 lr=1.00e-03

OR train context_aware_description seed=2 epoch=2:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=02 loss=0.7758 valid_FITB=0.6290 lr=1.00e-03

OR train context_aware_description seed=2 epoch=3:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=03 loss=0.6817 valid_FITB=0.6293 lr=1.00e-03

OR train context_aware_description seed=2 epoch=4:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=04 loss=0.5902 valid_FITB=0.6270 lr=1.00e-03

OR train context_aware_description seed=2 epoch=5:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=05 loss=0.4988 valid_FITB=0.6227 lr=1.00e-03

OR train context_aware_description seed=2 epoch=6:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=06 loss=0.4127 valid_FITB=0.6147 lr=5.00e-04

OR train context_aware_description seed=2 epoch=7:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=07 loss=0.2920 valid_FITB=0.6277 lr=5.00e-04

OR train context_aware_description seed=2 epoch=8:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=08 loss=0.2325 valid_FITB=0.6273 lr=5.00e-04

OR train context_aware_description seed=2 epoch=9:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=09 loss=0.1946 valid_FITB=0.6230 lr=2.50e-04

OR train context_aware_description seed=2 epoch=10:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=10 loss=0.1475 valid_FITB=0.6290 lr=2.50e-04

OR train context_aware_description seed=2 epoch=11:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=11 loss=0.1251 valid_FITB=0.6167 lr=2.50e-04

OR train context_aware_description seed=2 epoch=12:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=12 loss=0.1109 valid_FITB=0.6183 lr=1.25e-04

OR train context_aware_description seed=2 epoch=13:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=13 loss=0.0979 valid_FITB=0.6130 lr=1.25e-04

OR train context_aware_description seed=2 epoch=14:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=14 loss=0.0894 valid_FITB=0.6143 lr=1.25e-04

OR train context_aware_description seed=2 epoch=15:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=15 loss=0.0859 valid_FITB=0.6157 lr=6.25e-05

OR train context_aware_description seed=2 epoch=16:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=16 loss=0.0797 valid_FITB=0.6153 lr=6.25e-05

OR train context_aware_description seed=2 epoch=17:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=17 loss=0.0745 valid_FITB=0.6157 lr=6.25e-05

OR train context_aware_description seed=2 epoch=18:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=18 loss=0.0731 valid_FITB=0.6163 lr=3.13e-05

OR train context_aware_description seed=2 epoch=19:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=19 loss=0.0715 valid_FITB=0.6147 lr=3.13e-05

OR train context_aware_description seed=2 epoch=20:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=20 loss=0.0679 valid_FITB=0.6150 lr=3.13e-05

OR train context_aware_description seed=2 epoch=21:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=21 loss=0.0670 valid_FITB=0.6167 lr=1.56e-05

OR train context_aware_description seed=2 epoch=22:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=22 loss=0.0669 valid_FITB=0.6147 lr=1.56e-05

OR train context_aware_description seed=2 epoch=23:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=23 loss=0.0659 valid_FITB=0.6147 lr=1.56e-05

OR train context_aware_description seed=2 epoch=24:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=24 loss=0.0650 valid_FITB=0.6160 lr=7.81e-06

OR train context_aware_description seed=2 epoch=25:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=25 loss=0.0622 valid_FITB=0.6133 lr=7.81e-06

OR train context_aware_description seed=2 epoch=26:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=26 loss=0.0644 valid_FITB=0.6147 lr=7.81e-06

OR train context_aware_description seed=2 epoch=27:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=27 loss=0.0625 valid_FITB=0.6147 lr=3.91e-06

OR train context_aware_description seed=2 epoch=28:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=28 loss=0.0637 valid_FITB=0.6140 lr=3.91e-06

OR train context_aware_description seed=2 epoch=29:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=29 loss=0.0632 valid_FITB=0.6133 lr=3.91e-06

OR train context_aware_description seed=2 epoch=30:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=30 loss=0.0649 valid_FITB=0.6120 lr=1.95e-06

OR train context_aware_description seed=2 epoch=31:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=31 loss=0.0625 valid_FITB=0.6127 lr=1.95e-06

OR train context_aware_description seed=2 epoch=32:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=32 loss=0.0632 valid_FITB=0.6130 lr=1.95e-06

OR train context_aware_description seed=2 epoch=33:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=33 loss=0.0658 valid_FITB=0.6130 lr=9.77e-07

OR train context_aware_description seed=2 epoch=34:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=34 loss=0.0627 valid_FITB=0.6137 lr=9.77e-07

OR train context_aware_description seed=2 epoch=35:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=35 loss=0.0624 valid_FITB=0.6140 lr=9.77e-07

OR train context_aware_description seed=2 epoch=36:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=36 loss=0.0624 valid_FITB=0.6143 lr=4.88e-07

OR train context_aware_description seed=2 epoch=37:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=37 loss=0.0644 valid_FITB=0.6140 lr=4.88e-07

OR train context_aware_description seed=2 epoch=38:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=38 loss=0.0629 valid_FITB=0.6143 lr=4.88e-07

OR train context_aware_description seed=2 epoch=39:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=39 loss=0.0625 valid_FITB=0.6143 lr=2.44e-07

OR train context_aware_description seed=2 epoch=40:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=40 loss=0.0628 valid_FITB=0.6143 lr=2.44e-07

OR train context_aware_description seed=2 epoch=41:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=41 loss=0.0634 valid_FITB=0.6137 lr=2.44e-07

OR train context_aware_description seed=2 epoch=42:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=42 loss=0.0623 valid_FITB=0.6140 lr=1.22e-07

OR train context_aware_description seed=2 epoch=43:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=43 loss=0.0619 valid_FITB=0.6140 lr=1.22e-07

OR train context_aware_description seed=2 epoch=44:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=44 loss=0.0624 valid_FITB=0.6140 lr=1.22e-07

OR train context_aware_description seed=2 epoch=45:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=45 loss=0.0633 valid_FITB=0.6137 lr=6.10e-08

OR train context_aware_description seed=2 epoch=46:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=46 loss=0.0616 valid_FITB=0.6137 lr=6.10e-08

OR train context_aware_description seed=2 epoch=47:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=47 loss=0.0635 valid_FITB=0.6137 lr=6.10e-08

OR train context_aware_description seed=2 epoch=48:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=48 loss=0.0624 valid_FITB=0.6137 lr=3.05e-08

OR train context_aware_description seed=2 epoch=49:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=49 loss=0.0635 valid_FITB=0.6137 lr=3.05e-08

OR train context_aware_description seed=2 epoch=50:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=50 loss=0.0634 valid_FITB=0.6137 lr=3.05e-08

OR train context_aware_description seed=2 epoch=51:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=51 loss=0.0645 valid_FITB=0.6133 lr=1.53e-08

OR train context_aware_description seed=2 epoch=52:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=52 loss=0.0635 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=53:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=53 loss=0.0619 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=54:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=54 loss=0.0635 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=55:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=55 loss=0.0621 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=56:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=56 loss=0.0639 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=57:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=57 loss=0.0609 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=58:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=58 loss=0.0634 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=59:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=59 loss=0.0629 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=60:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=60 loss=0.0638 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=61:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=61 loss=0.0629 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=62:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=62 loss=0.0625 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=63:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=63 loss=0.0635 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=64:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=64 loss=0.0631 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=65:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=65 loss=0.0627 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=66:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=66 loss=0.0635 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=67:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=67 loss=0.0633 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=68:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=68 loss=0.0614 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=69:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=69 loss=0.0609 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=70:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=70 loss=0.0627 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=71:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=71 loss=0.0627 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=72:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=72 loss=0.0626 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=73:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=73 loss=0.0630 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=74:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=74 loss=0.0634 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=75:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=75 loss=0.0640 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=76:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=76 loss=0.0613 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=77:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=77 loss=0.0633 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=78:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=78 loss=0.0616 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=79:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=79 loss=0.0625 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=80:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=80 loss=0.0633 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=81:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=81 loss=0.0623 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=82:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=82 loss=0.0635 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=83:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=83 loss=0.0615 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=84:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=84 loss=0.0636 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=85:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=85 loss=0.0614 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=86:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=86 loss=0.0620 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=87:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=87 loss=0.0620 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=88:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=88 loss=0.0635 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=89:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=89 loss=0.0625 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=90:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=90 loss=0.0639 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=91:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=91 loss=0.0619 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=92:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=92 loss=0.0632 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=93:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=93 loss=0.0615 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=94:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=94 loss=0.0629 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=95:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=95 loss=0.0637 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=96:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=96 loss=0.0616 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=97:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=97 loss=0.0642 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=98:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=98 loss=0.0629 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=99:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=99 loss=0.0642 valid_FITB=0.6137 lr=1.53e-08

OR train context_aware_description seed=2 epoch=100:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=100 loss=0.0633 valid_FITB=0.6137 lr=1.53e-08

encode candidate pools [context_aware_description seed=2]:   0%|          | 0/19 [00:00<?, ?it/s]

OR/CIR recall [context_aware_description seed=2]:   0%|          | 0/15145 [00:00<?, ?it/s]

[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/context_aware_description/seed_2/seed_summary.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/context_aware_description/seed_2/or_recall_rowlevel.csv

[CP 訓練] variant=context_aware_description, seed=3, train=33,990, valid=6,000

CP train context_aware_description seed=3 epoch=1:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=01 loss=0.6198 valid_AUC=0.8362 valid_FITB=0.3913 lr=1.00e-03

CP train context_aware_description seed=3 epoch=2:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=02 loss=0.4688 valid_AUC=0.8625 valid_FITB=0.4367 lr=1.00e-03

CP train context_aware_description seed=3 epoch=3:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=03 loss=0.4118 valid_AUC=0.8898 valid_FITB=0.4677 lr=1.00e-03

CP train context_aware_description seed=3 epoch=4:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=04 loss=0.3747 valid_AUC=0.9014 valid_FITB=0.4900 lr=1.00e-03

CP train context_aware_description seed=3 epoch=5:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=05 loss=0.3379 valid_AUC=0.9069 valid_FITB=0.4927 lr=1.00e-03

CP train context_aware_description seed=3 epoch=6:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=06 loss=0.3021 valid_AUC=0.9104 valid_FITB=0.5020 lr=1.00e-03

CP train context_aware_description seed=3 epoch=7:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=07 loss=0.2700 valid_AUC=0.9233 valid_FITB=0.5150 lr=1.00e-03

CP train context_aware_description seed=3 epoch=8:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=08 loss=0.2453 valid_AUC=0.9160 valid_FITB=0.5107 lr=1.00e-03

CP train context_aware_description seed=3 epoch=9:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=09 loss=0.2109 valid_AUC=0.9233 valid_FITB=0.5303 lr=1.00e-03

CP train context_aware_description seed=3 epoch=10:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=10 loss=0.1911 valid_AUC=0.9284 valid_FITB=0.5373 lr=1.00e-03

CP train context_aware_description seed=3 epoch=11:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=11 loss=0.1567 valid_AUC=0.9260 valid_FITB=0.5380 lr=1.00e-03

CP train context_aware_description seed=3 epoch=12:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=12 loss=0.1385 valid_AUC=0.9273 valid_FITB=0.5237 lr=1.00e-03

CP train context_aware_description seed=3 epoch=13:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=13 loss=0.1244 valid_AUC=0.9313 valid_FITB=0.5390 lr=1.00e-03

CP train context_aware_description seed=3 epoch=14:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=14 loss=0.1116 valid_AUC=0.9305 valid_FITB=0.5320 lr=1.00e-03

CP train context_aware_description seed=3 epoch=15:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=15 loss=0.0978 valid_AUC=0.9339 valid_FITB=0.5460 lr=1.00e-03

CP train context_aware_description seed=3 epoch=16:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=16 loss=0.0884 valid_AUC=0.9316 valid_FITB=0.5463 lr=1.00e-03

CP train context_aware_description seed=3 epoch=17:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=17 loss=0.0830 valid_AUC=0.9331 valid_FITB=0.5343 lr=1.00e-03

CP train context_aware_description seed=3 epoch=18:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=18 loss=0.0748 valid_AUC=0.9333 valid_FITB=0.5437 lr=1.00e-03

CP train context_aware_description seed=3 epoch=19:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=19 loss=0.0662 valid_AUC=0.9294 valid_FITB=0.5447 lr=5.00e-04

CP train context_aware_description seed=3 epoch=20:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=20 loss=0.0334 valid_AUC=0.9376 valid_FITB=0.5403 lr=5.00e-04

CP train context_aware_description seed=3 epoch=21:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=21 loss=0.0232 valid_AUC=0.9370 valid_FITB=0.5470 lr=5.00e-04

CP train context_aware_description seed=3 epoch=22:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=22 loss=0.0177 valid_AUC=0.9368 valid_FITB=0.5367 lr=5.00e-04

CP train context_aware_description seed=3 epoch=23:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=23 loss=0.0165 valid_AUC=0.9368 valid_FITB=0.5427 lr=5.00e-04

CP train context_aware_description seed=3 epoch=24:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=24 loss=0.0185 valid_AUC=0.9363 valid_FITB=0.5420 lr=2.50e-04

CP train context_aware_description seed=3 epoch=25:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=25 loss=0.0101 valid_AUC=0.9397 valid_FITB=0.5443 lr=2.50e-04

CP train context_aware_description seed=3 epoch=26:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=26 loss=0.0084 valid_AUC=0.9388 valid_FITB=0.5433 lr=2.50e-04

CP train context_aware_description seed=3 epoch=27:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=27 loss=0.0068 valid_AUC=0.9375 valid_FITB=0.5427 lr=1.25e-04

CP train context_aware_description seed=3 epoch=28:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=28 loss=0.0055 valid_AUC=0.9392 valid_FITB=0.5430 lr=1.25e-04

CP train context_aware_description seed=3 epoch=29:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=29 loss=0.0043 valid_AUC=0.9389 valid_FITB=0.5423 lr=1.25e-04

CP train context_aware_description seed=3 epoch=30:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=30 loss=0.0046 valid_AUC=0.9392 valid_FITB=0.5367 lr=6.25e-05

CP train context_aware_description seed=3 epoch=31:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=31 loss=0.0042 valid_AUC=0.9393 valid_FITB=0.5393 lr=6.25e-05

CP train context_aware_description seed=3 epoch=32:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=32 loss=0.0042 valid_AUC=0.9394 valid_FITB=0.5447 lr=6.25e-05

CP train context_aware_description seed=3 epoch=33:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=33 loss=0.0034 valid_AUC=0.9394 valid_FITB=0.5413 lr=3.13e-05

CP train context_aware_description seed=3 epoch=34:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=34 loss=0.0035 valid_AUC=0.9396 valid_FITB=0.5440 lr=3.13e-05

CP train context_aware_description seed=3 epoch=35:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=35 loss=0.0033 valid_AUC=0.9395 valid_FITB=0.5433 lr=3.13e-05

CP train context_aware_description seed=3 epoch=36:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=36 loss=0.0030 valid_AUC=0.9394 valid_FITB=0.5410 lr=1.56e-05

CP train context_aware_description seed=3 epoch=37:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=37 loss=0.0033 valid_AUC=0.9394 valid_FITB=0.5410 lr=1.56e-05

CP train context_aware_description seed=3 epoch=38:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=38 loss=0.0029 valid_AUC=0.9394 valid_FITB=0.5393 lr=1.56e-05

CP train context_aware_description seed=3 epoch=39:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=39 loss=0.0029 valid_AUC=0.9395 valid_FITB=0.5400 lr=7.81e-06

CP train context_aware_description seed=3 epoch=40:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=40 loss=0.0030 valid_AUC=0.9395 valid_FITB=0.5403 lr=7.81e-06

CP train context_aware_description seed=3 epoch=41:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=41 loss=0.0029 valid_AUC=0.9395 valid_FITB=0.5387 lr=7.81e-06

CP train context_aware_description seed=3 epoch=42:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=42 loss=0.0033 valid_AUC=0.9395 valid_FITB=0.5410 lr=3.91e-06

CP train context_aware_description seed=3 epoch=43:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=43 loss=0.0031 valid_AUC=0.9395 valid_FITB=0.5403 lr=3.91e-06

CP train context_aware_description seed=3 epoch=44:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=44 loss=0.0027 valid_AUC=0.9395 valid_FITB=0.5407 lr=3.91e-06

CP train context_aware_description seed=3 epoch=45:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=45 loss=0.0031 valid_AUC=0.9396 valid_FITB=0.5417 lr=1.95e-06

CP train context_aware_description seed=3 epoch=46:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=46 loss=0.0026 valid_AUC=0.9396 valid_FITB=0.5407 lr=1.95e-06

CP train context_aware_description seed=3 epoch=47:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=47 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.95e-06

CP train context_aware_description seed=3 epoch=48:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=48 loss=0.0029 valid_AUC=0.9396 valid_FITB=0.5413 lr=9.77e-07

CP train context_aware_description seed=3 epoch=49:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=49 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5413 lr=9.77e-07

CP train context_aware_description seed=3 epoch=50:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=50 loss=0.0025 valid_AUC=0.9396 valid_FITB=0.5413 lr=9.77e-07

CP train context_aware_description seed=3 epoch=51:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=51 loss=0.0029 valid_AUC=0.9396 valid_FITB=0.5413 lr=4.88e-07

CP train context_aware_description seed=3 epoch=52:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=52 loss=0.0032 valid_AUC=0.9396 valid_FITB=0.5413 lr=4.88e-07

CP train context_aware_description seed=3 epoch=53:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=53 loss=0.0027 valid_AUC=0.9396 valid_FITB=0.5413 lr=4.88e-07

CP train context_aware_description seed=3 epoch=54:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=54 loss=0.0027 valid_AUC=0.9396 valid_FITB=0.5417 lr=2.44e-07

CP train context_aware_description seed=3 epoch=55:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=55 loss=0.0030 valid_AUC=0.9396 valid_FITB=0.5413 lr=2.44e-07

CP train context_aware_description seed=3 epoch=56:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=56 loss=0.0032 valid_AUC=0.9396 valid_FITB=0.5413 lr=2.44e-07

CP train context_aware_description seed=3 epoch=57:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=57 loss=0.0030 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.22e-07

CP train context_aware_description seed=3 epoch=58:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=58 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.22e-07

CP train context_aware_description seed=3 epoch=59:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=59 loss=0.0027 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.22e-07

CP train context_aware_description seed=3 epoch=60:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=60 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5410 lr=6.10e-08

CP train context_aware_description seed=3 epoch=61:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=61 loss=0.0025 valid_AUC=0.9396 valid_FITB=0.5410 lr=6.10e-08

CP train context_aware_description seed=3 epoch=62:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=62 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5413 lr=6.10e-08

CP train context_aware_description seed=3 epoch=63:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=63 loss=0.0025 valid_AUC=0.9396 valid_FITB=0.5410 lr=3.05e-08

CP train context_aware_description seed=3 epoch=64:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=64 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5413 lr=3.05e-08

CP train context_aware_description seed=3 epoch=65:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=65 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5410 lr=3.05e-08

CP train context_aware_description seed=3 epoch=66:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=66 loss=0.0031 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=67:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=67 loss=0.0026 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=68:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=68 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=69:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=69 loss=0.0032 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=70:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=70 loss=0.0026 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=71:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=71 loss=0.0025 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=72:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=72 loss=0.0026 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=73:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=73 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=74:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=74 loss=0.0026 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=75:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=75 loss=0.0029 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=76:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=76 loss=0.0026 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=77:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=77 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=78:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=78 loss=0.0027 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=79:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=79 loss=0.0031 valid_AUC=0.9396 valid_FITB=0.5413 lr=1.53e-08

CP train context_aware_description seed=3 epoch=80:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=80 loss=0.0026 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=81:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=81 loss=0.0027 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=82:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=82 loss=0.0027 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=83:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=83 loss=0.0027 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=84:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=84 loss=0.0026 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=85:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=85 loss=0.0026 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=86:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=86 loss=0.0032 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=87:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=87 loss=0.0032 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=88:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=88 loss=0.0026 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=89:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=89 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=90:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=90 loss=0.0029 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=91:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=91 loss=0.0026 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=92:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=92 loss=0.0029 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=93:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=93 loss=0.0031 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=94:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=94 loss=0.0032 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=95:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=95 loss=0.0027 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=96:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=96 loss=0.0032 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=97:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=97 loss=0.0028 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=98:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=98 loss=0.0027 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=99:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=99 loss=0.0025 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP train context_aware_description seed=3 epoch=100:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=100 loss=0.0027 valid_AUC=0.9396 valid_FITB=0.5410 lr=1.53e-08

CP FITB:   0%|          | 0/15145 [00:00<?, ?it/s]

[OR 訓練] variant=context_aware_description, seed=3, train=16,995, valid=3,000

OR train context_aware_description seed=3 epoch=1:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=01 loss=0.9529 valid_FITB=0.6137 lr=1.00e-03

OR train context_aware_description seed=3 epoch=2:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=02 loss=0.7906 valid_FITB=0.6257 lr=1.00e-03

OR train context_aware_description seed=3 epoch=3:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=03 loss=0.6913 valid_FITB=0.6280 lr=1.00e-03

OR train context_aware_description seed=3 epoch=4:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=04 loss=0.6070 valid_FITB=0.6320 lr=1.00e-03

OR train context_aware_description seed=3 epoch=5:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=05 loss=0.5127 valid_FITB=0.6357 lr=1.00e-03

OR train context_aware_description seed=3 epoch=6:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=06 loss=0.4266 valid_FITB=0.6320 lr=1.00e-03

OR train context_aware_description seed=3 epoch=7:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=07 loss=0.3449 valid_FITB=0.6273 lr=1.00e-03

OR train context_aware_description seed=3 epoch=8:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=08 loss=0.2803 valid_FITB=0.6160 lr=5.00e-04

OR train context_aware_description seed=3 epoch=9:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=09 loss=0.1867 valid_FITB=0.6207 lr=5.00e-04

OR train context_aware_description seed=3 epoch=10:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=10 loss=0.1420 valid_FITB=0.6177 lr=5.00e-04

OR train context_aware_description seed=3 epoch=11:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=11 loss=0.1154 valid_FITB=0.6233 lr=2.50e-04

OR train context_aware_description seed=3 epoch=12:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=12 loss=0.0924 valid_FITB=0.6170 lr=2.50e-04

OR train context_aware_description seed=3 epoch=13:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=13 loss=0.0789 valid_FITB=0.6203 lr=2.50e-04

OR train context_aware_description seed=3 epoch=14:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=14 loss=0.0702 valid_FITB=0.6210 lr=1.25e-04

OR train context_aware_description seed=3 epoch=15:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=15 loss=0.0608 valid_FITB=0.6150 lr=1.25e-04

OR train context_aware_description seed=3 epoch=16:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=16 loss=0.0568 valid_FITB=0.6187 lr=1.25e-04

OR train context_aware_description seed=3 epoch=17:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=17 loss=0.0532 valid_FITB=0.6127 lr=6.25e-05

OR train context_aware_description seed=3 epoch=18:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=18 loss=0.0498 valid_FITB=0.6153 lr=6.25e-05

OR train context_aware_description seed=3 epoch=19:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=19 loss=0.0493 valid_FITB=0.6150 lr=6.25e-05

OR train context_aware_description seed=3 epoch=20:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=20 loss=0.0485 valid_FITB=0.6160 lr=3.13e-05

OR train context_aware_description seed=3 epoch=21:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=21 loss=0.0462 valid_FITB=0.6183 lr=3.13e-05

OR train context_aware_description seed=3 epoch=22:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=22 loss=0.0440 valid_FITB=0.6187 lr=3.13e-05

OR train context_aware_description seed=3 epoch=23:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=23 loss=0.0430 valid_FITB=0.6180 lr=1.56e-05

OR train context_aware_description seed=3 epoch=24:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=24 loss=0.0450 valid_FITB=0.6170 lr=1.56e-05

OR train context_aware_description seed=3 epoch=25:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=25 loss=0.0436 valid_FITB=0.6170 lr=1.56e-05

OR train context_aware_description seed=3 epoch=26:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=26 loss=0.0435 valid_FITB=0.6177 lr=7.81e-06

OR train context_aware_description seed=3 epoch=27:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=27 loss=0.0427 valid_FITB=0.6177 lr=7.81e-06

OR train context_aware_description seed=3 epoch=28:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=28 loss=0.0432 valid_FITB=0.6187 lr=7.81e-06

OR train context_aware_description seed=3 epoch=29:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=29 loss=0.0422 valid_FITB=0.6187 lr=3.91e-06

OR train context_aware_description seed=3 epoch=30:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=30 loss=0.0428 valid_FITB=0.6180 lr=3.91e-06

OR train context_aware_description seed=3 epoch=31:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=31 loss=0.0430 valid_FITB=0.6170 lr=3.91e-06

OR train context_aware_description seed=3 epoch=32:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=32 loss=0.0410 valid_FITB=0.6177 lr=1.95e-06

OR train context_aware_description seed=3 epoch=33:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=33 loss=0.0411 valid_FITB=0.6177 lr=1.95e-06

OR train context_aware_description seed=3 epoch=34:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=34 loss=0.0411 valid_FITB=0.6180 lr=1.95e-06

OR train context_aware_description seed=3 epoch=35:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=35 loss=0.0410 valid_FITB=0.6187 lr=9.77e-07

OR train context_aware_description seed=3 epoch=36:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=36 loss=0.0424 valid_FITB=0.6183 lr=9.77e-07

OR train context_aware_description seed=3 epoch=37:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=37 loss=0.0422 valid_FITB=0.6180 lr=9.77e-07

OR train context_aware_description seed=3 epoch=38:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=38 loss=0.0427 valid_FITB=0.6180 lr=4.88e-07

OR train context_aware_description seed=3 epoch=39:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=39 loss=0.0404 valid_FITB=0.6180 lr=4.88e-07

OR train context_aware_description seed=3 epoch=40:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=40 loss=0.0426 valid_FITB=0.6183 lr=4.88e-07

OR train context_aware_description seed=3 epoch=41:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=41 loss=0.0423 valid_FITB=0.6183 lr=2.44e-07

OR train context_aware_description seed=3 epoch=42:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=42 loss=0.0424 valid_FITB=0.6187 lr=2.44e-07

OR train context_aware_description seed=3 epoch=43:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=43 loss=0.0419 valid_FITB=0.6187 lr=2.44e-07

OR train context_aware_description seed=3 epoch=44:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=44 loss=0.0420 valid_FITB=0.6187 lr=1.22e-07

OR train context_aware_description seed=3 epoch=45:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=45 loss=0.0415 valid_FITB=0.6187 lr=1.22e-07

OR train context_aware_description seed=3 epoch=46:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=46 loss=0.0410 valid_FITB=0.6187 lr=1.22e-07

OR train context_aware_description seed=3 epoch=47:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=47 loss=0.0405 valid_FITB=0.6187 lr=6.10e-08

OR train context_aware_description seed=3 epoch=48:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=48 loss=0.0416 valid_FITB=0.6187 lr=6.10e-08

OR train context_aware_description seed=3 epoch=49:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=49 loss=0.0416 valid_FITB=0.6187 lr=6.10e-08

OR train context_aware_description seed=3 epoch=50:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=50 loss=0.0426 valid_FITB=0.6183 lr=3.05e-08

OR train context_aware_description seed=3 epoch=51:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=51 loss=0.0421 valid_FITB=0.6187 lr=3.05e-08

OR train context_aware_description seed=3 epoch=52:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=52 loss=0.0408 valid_FITB=0.6187 lr=3.05e-08

OR train context_aware_description seed=3 epoch=53:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=53 loss=0.0405 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=54:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=54 loss=0.0410 valid_FITB=0.6180 lr=1.53e-08

OR train context_aware_description seed=3 epoch=55:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=55 loss=0.0418 valid_FITB=0.6180 lr=1.53e-08

OR train context_aware_description seed=3 epoch=56:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=56 loss=0.0406 valid_FITB=0.6180 lr=1.53e-08

OR train context_aware_description seed=3 epoch=57:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=57 loss=0.0416 valid_FITB=0.6180 lr=1.53e-08

OR train context_aware_description seed=3 epoch=58:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=58 loss=0.0415 valid_FITB=0.6180 lr=1.53e-08

OR train context_aware_description seed=3 epoch=59:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=59 loss=0.0410 valid_FITB=0.6180 lr=1.53e-08

OR train context_aware_description seed=3 epoch=60:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=60 loss=0.0424 valid_FITB=0.6180 lr=1.53e-08

OR train context_aware_description seed=3 epoch=61:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=61 loss=0.0415 valid_FITB=0.6180 lr=1.53e-08

OR train context_aware_description seed=3 epoch=62:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=62 loss=0.0404 valid_FITB=0.6180 lr=1.53e-08

OR train context_aware_description seed=3 epoch=63:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=63 loss=0.0410 valid_FITB=0.6180 lr=1.53e-08

OR train context_aware_description seed=3 epoch=64:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=64 loss=0.0427 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=65:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=65 loss=0.0414 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=66:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=66 loss=0.0425 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=67:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=67 loss=0.0409 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=68:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=68 loss=0.0405 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=69:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=69 loss=0.0413 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=70:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=70 loss=0.0416 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=71:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=71 loss=0.0419 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=72:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=72 loss=0.0428 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=73:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=73 loss=0.0417 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=74:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=74 loss=0.0415 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=75:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=75 loss=0.0422 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=76:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=76 loss=0.0414 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=77:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=77 loss=0.0404 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=78:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=78 loss=0.0409 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=79:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=79 loss=0.0425 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=80:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=80 loss=0.0417 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=81:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=81 loss=0.0414 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=82:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=82 loss=0.0419 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=83:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=83 loss=0.0408 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=84:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=84 loss=0.0415 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=85:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=85 loss=0.0419 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=86:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=86 loss=0.0412 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=87:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=87 loss=0.0422 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=88:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=88 loss=0.0435 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=89:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=89 loss=0.0411 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=90:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=90 loss=0.0422 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=91:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=91 loss=0.0421 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=92:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=92 loss=0.0423 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=93:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=93 loss=0.0411 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=94:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=94 loss=0.0405 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=95:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=95 loss=0.0412 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=96:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=96 loss=0.0419 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=97:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=97 loss=0.0403 valid_FITB=0.6187 lr=1.53e-08

OR train context_aware_description seed=3 epoch=98:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=98 loss=0.0411 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=99:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=99 loss=0.0403 valid_FITB=0.6183 lr=1.53e-08

OR train context_aware_description seed=3 epoch=100:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=100 loss=0.0412 valid_FITB=0.6183 lr=1.53e-08

encode candidate pools [context_aware_description seed=3]:   0%|          | 0/19 [00:00<?, ?it/s]

OR/CIR recall [context_aware_description seed=3]:   0%|          | 0/15145 [00:00<?, ?it/s]

[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/context_aware_description/seed_3/seed_summary.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/context_aware_description/seed_3/or_recall_rowlevel.csv

[CP 訓練] variant=context_aware_description, seed=4, train=33,990, valid=6,000

CP train context_aware_description seed=4 epoch=1:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=01 loss=0.5904 valid_AUC=0.8584 valid_FITB=0.4237 lr=1.00e-03

CP train context_aware_description seed=4 epoch=2:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=02 loss=0.4465 valid_AUC=0.8757 valid_FITB=0.4450 lr=1.00e-03

CP train context_aware_description seed=4 epoch=3:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=03 loss=0.3981 valid_AUC=0.8984 valid_FITB=0.4717 lr=1.00e-03

CP train context_aware_description seed=4 epoch=4:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=04 loss=0.3637 valid_AUC=0.9008 valid_FITB=0.5040 lr=1.00e-03

CP train context_aware_description seed=4 epoch=5:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=05 loss=0.3299 valid_AUC=0.9164 valid_FITB=0.5260 lr=1.00e-03

CP train context_aware_description seed=4 epoch=6:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=06 loss=0.2860 valid_AUC=0.9163 valid_FITB=0.5383 lr=1.00e-03

CP train context_aware_description seed=4 epoch=7:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=07 loss=0.2530 valid_AUC=0.9240 valid_FITB=0.5483 lr=1.00e-03

CP train context_aware_description seed=4 epoch=8:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=08 loss=0.2175 valid_AUC=0.9309 valid_FITB=0.5520 lr=1.00e-03

CP train context_aware_description seed=4 epoch=9:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=09 loss=0.1940 valid_AUC=0.9322 valid_FITB=0.5500 lr=1.00e-03

CP train context_aware_description seed=4 epoch=10:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=10 loss=0.1754 valid_AUC=0.9370 valid_FITB=0.5690 lr=1.00e-03

CP train context_aware_description seed=4 epoch=11:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=11 loss=0.1488 valid_AUC=0.9360 valid_FITB=0.5617 lr=1.00e-03

CP train context_aware_description seed=4 epoch=12:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=12 loss=0.1320 valid_AUC=0.9330 valid_FITB=0.5557 lr=1.00e-03

CP train context_aware_description seed=4 epoch=13:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=13 loss=0.1116 valid_AUC=0.9364 valid_FITB=0.5673 lr=5.00e-04

CP train context_aware_description seed=4 epoch=14:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=14 loss=0.0664 valid_AUC=0.9393 valid_FITB=0.5633 lr=5.00e-04

CP train context_aware_description seed=4 epoch=15:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=15 loss=0.0460 valid_AUC=0.9384 valid_FITB=0.5500 lr=5.00e-04

CP train context_aware_description seed=4 epoch=16:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=16 loss=0.0386 valid_AUC=0.9364 valid_FITB=0.5493 lr=2.50e-04

CP train context_aware_description seed=4 epoch=17:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=17 loss=0.0265 valid_AUC=0.9394 valid_FITB=0.5627 lr=2.50e-04

CP train context_aware_description seed=4 epoch=18:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=18 loss=0.0211 valid_AUC=0.9409 valid_FITB=0.5597 lr=2.50e-04

CP train context_aware_description seed=4 epoch=19:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=19 loss=0.0170 valid_AUC=0.9396 valid_FITB=0.5563 lr=1.25e-04

CP train context_aware_description seed=4 epoch=20:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=20 loss=0.0128 valid_AUC=0.9408 valid_FITB=0.5577 lr=1.25e-04

CP train context_aware_description seed=4 epoch=21:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=21 loss=0.0117 valid_AUC=0.9404 valid_FITB=0.5563 lr=1.25e-04

CP train context_aware_description seed=4 epoch=22:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=22 loss=0.0109 valid_AUC=0.9403 valid_FITB=0.5597 lr=6.25e-05

CP train context_aware_description seed=4 epoch=23:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=23 loss=0.0093 valid_AUC=0.9408 valid_FITB=0.5613 lr=6.25e-05

CP train context_aware_description seed=4 epoch=24:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=24 loss=0.0079 valid_AUC=0.9405 valid_FITB=0.5577 lr=6.25e-05

CP train context_aware_description seed=4 epoch=25:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=25 loss=0.0078 valid_AUC=0.9407 valid_FITB=0.5570 lr=3.13e-05

CP train context_aware_description seed=4 epoch=26:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=26 loss=0.0078 valid_AUC=0.9408 valid_FITB=0.5593 lr=3.13e-05

CP train context_aware_description seed=4 epoch=27:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=27 loss=0.0073 valid_AUC=0.9409 valid_FITB=0.5560 lr=3.13e-05

CP train context_aware_description seed=4 epoch=28:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=28 loss=0.0075 valid_AUC=0.9410 valid_FITB=0.5557 lr=1.56e-05

CP train context_aware_description seed=4 epoch=29:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=29 loss=0.0072 valid_AUC=0.9409 valid_FITB=0.5557 lr=1.56e-05

CP train context_aware_description seed=4 epoch=30:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=30 loss=0.0073 valid_AUC=0.9409 valid_FITB=0.5573 lr=1.56e-05

CP train context_aware_description seed=4 epoch=31:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=31 loss=0.0064 valid_AUC=0.9409 valid_FITB=0.5567 lr=7.81e-06

CP train context_aware_description seed=4 epoch=32:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=32 loss=0.0069 valid_AUC=0.9409 valid_FITB=0.5577 lr=7.81e-06

CP train context_aware_description seed=4 epoch=33:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=33 loss=0.0059 valid_AUC=0.9409 valid_FITB=0.5580 lr=7.81e-06

CP train context_aware_description seed=4 epoch=34:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=34 loss=0.0065 valid_AUC=0.9410 valid_FITB=0.5567 lr=3.91e-06

CP train context_aware_description seed=4 epoch=35:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=35 loss=0.0065 valid_AUC=0.9410 valid_FITB=0.5580 lr=3.91e-06

CP train context_aware_description seed=4 epoch=36:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=36 loss=0.0061 valid_AUC=0.9410 valid_FITB=0.5580 lr=3.91e-06

CP train context_aware_description seed=4 epoch=37:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=37 loss=0.0063 valid_AUC=0.9410 valid_FITB=0.5583 lr=1.95e-06

CP train context_aware_description seed=4 epoch=38:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=38 loss=0.0066 valid_AUC=0.9410 valid_FITB=0.5577 lr=1.95e-06

CP train context_aware_description seed=4 epoch=39:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=39 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5580 lr=1.95e-06

CP train context_aware_description seed=4 epoch=40:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=40 loss=0.0064 valid_AUC=0.9409 valid_FITB=0.5583 lr=9.77e-07

CP train context_aware_description seed=4 epoch=41:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=41 loss=0.0063 valid_AUC=0.9410 valid_FITB=0.5573 lr=9.77e-07

CP train context_aware_description seed=4 epoch=42:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=42 loss=0.0061 valid_AUC=0.9410 valid_FITB=0.5570 lr=9.77e-07

CP train context_aware_description seed=4 epoch=43:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=43 loss=0.0063 valid_AUC=0.9410 valid_FITB=0.5570 lr=4.88e-07

CP train context_aware_description seed=4 epoch=44:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=44 loss=0.0059 valid_AUC=0.9410 valid_FITB=0.5570 lr=4.88e-07

CP train context_aware_description seed=4 epoch=45:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=45 loss=0.0060 valid_AUC=0.9410 valid_FITB=0.5570 lr=4.88e-07

CP train context_aware_description seed=4 epoch=46:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=46 loss=0.0063 valid_AUC=0.9410 valid_FITB=0.5573 lr=2.44e-07

CP train context_aware_description seed=4 epoch=47:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=47 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5570 lr=2.44e-07

CP train context_aware_description seed=4 epoch=48:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=48 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5573 lr=2.44e-07

CP train context_aware_description seed=4 epoch=49:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=49 loss=0.0061 valid_AUC=0.9410 valid_FITB=0.5570 lr=1.22e-07

CP train context_aware_description seed=4 epoch=50:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=50 loss=0.0065 valid_AUC=0.9410 valid_FITB=0.5570 lr=1.22e-07

CP train context_aware_description seed=4 epoch=51:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=51 loss=0.0063 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.22e-07

CP train context_aware_description seed=4 epoch=52:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=52 loss=0.0064 valid_AUC=0.9410 valid_FITB=0.5573 lr=6.10e-08

CP train context_aware_description seed=4 epoch=53:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=53 loss=0.0065 valid_AUC=0.9410 valid_FITB=0.5573 lr=6.10e-08

CP train context_aware_description seed=4 epoch=54:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=54 loss=0.0059 valid_AUC=0.9410 valid_FITB=0.5570 lr=6.10e-08

CP train context_aware_description seed=4 epoch=55:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=55 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5577 lr=3.05e-08

CP train context_aware_description seed=4 epoch=56:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=56 loss=0.0061 valid_AUC=0.9410 valid_FITB=0.5577 lr=3.05e-08

CP train context_aware_description seed=4 epoch=57:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=57 loss=0.0058 valid_AUC=0.9410 valid_FITB=0.5577 lr=3.05e-08

CP train context_aware_description seed=4 epoch=58:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=58 loss=0.0061 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=59:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=59 loss=0.0064 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=60:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=60 loss=0.0067 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=61:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=61 loss=0.0065 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=62:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=62 loss=0.0061 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=63:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=63 loss=0.0066 valid_AUC=0.9410 valid_FITB=0.5570 lr=1.53e-08

CP train context_aware_description seed=4 epoch=64:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=64 loss=0.0065 valid_AUC=0.9410 valid_FITB=0.5570 lr=1.53e-08

CP train context_aware_description seed=4 epoch=65:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=65 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5570 lr=1.53e-08

CP train context_aware_description seed=4 epoch=66:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=66 loss=0.0061 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=67:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=67 loss=0.0060 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=68:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=68 loss=0.0064 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=69:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=69 loss=0.0063 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=70:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=70 loss=0.0060 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=71:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=71 loss=0.0064 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=72:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=72 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=73:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=73 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=74:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=74 loss=0.0063 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=75:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=75 loss=0.0059 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=76:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=76 loss=0.0069 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=77:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=77 loss=0.0059 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=78:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=78 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=79:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=79 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=80:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=80 loss=0.0064 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=81:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=81 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=82:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=82 loss=0.0061 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=83:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=83 loss=0.0060 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=84:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=84 loss=0.0059 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=85:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=85 loss=0.0058 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=86:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=86 loss=0.0065 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=87:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=87 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=88:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=88 loss=0.0057 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=89:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=89 loss=0.0058 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=90:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=90 loss=0.0059 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=91:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=91 loss=0.0059 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=92:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=92 loss=0.0065 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=93:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=93 loss=0.0062 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=94:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=94 loss=0.0060 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=95:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=95 loss=0.0059 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=96:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=96 loss=0.0066 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=97:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=97 loss=0.0071 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=98:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=98 loss=0.0063 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=99:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=99 loss=0.0057 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP train context_aware_description seed=4 epoch=100:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=100 loss=0.0058 valid_AUC=0.9410 valid_FITB=0.5573 lr=1.53e-08

CP FITB:   0%|          | 0/15145 [00:00<?, ?it/s]

[OR 訓練] variant=context_aware_description, seed=4, train=16,995, valid=3,000

OR train context_aware_description seed=4 epoch=1:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=01 loss=0.9605 valid_FITB=0.6117 lr=1.00e-03

OR train context_aware_description seed=4 epoch=2:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=02 loss=0.8145 valid_FITB=0.6217 lr=1.00e-03

OR train context_aware_description seed=4 epoch=3:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=03 loss=0.7162 valid_FITB=0.6213 lr=1.00e-03

OR train context_aware_description seed=4 epoch=4:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=04 loss=0.6329 valid_FITB=0.6123 lr=1.00e-03

OR train context_aware_description seed=4 epoch=5:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=05 loss=0.5466 valid_FITB=0.6090 lr=5.00e-04

OR train context_aware_description seed=4 epoch=6:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=06 loss=0.4132 valid_FITB=0.6170 lr=5.00e-04

OR train context_aware_description seed=4 epoch=7:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=07 loss=0.3457 valid_FITB=0.6100 lr=5.00e-04

OR train context_aware_description seed=4 epoch=8:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=08 loss=0.2905 valid_FITB=0.6173 lr=2.50e-04

OR train context_aware_description seed=4 epoch=9:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=09 loss=0.2261 valid_FITB=0.6140 lr=2.50e-04

OR train context_aware_description seed=4 epoch=10:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=10 loss=0.1966 valid_FITB=0.6137 lr=2.50e-04

OR train context_aware_description seed=4 epoch=11:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=11 loss=0.1764 valid_FITB=0.6130 lr=1.25e-04

OR train context_aware_description seed=4 epoch=12:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=12 loss=0.1511 valid_FITB=0.6103 lr=1.25e-04

OR train context_aware_description seed=4 epoch=13:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=13 loss=0.1376 valid_FITB=0.6077 lr=1.25e-04

OR train context_aware_description seed=4 epoch=14:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=14 loss=0.1310 valid_FITB=0.6033 lr=6.25e-05

OR train context_aware_description seed=4 epoch=15:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=15 loss=0.1212 valid_FITB=0.6080 lr=6.25e-05

OR train context_aware_description seed=4 epoch=16:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=16 loss=0.1151 valid_FITB=0.6100 lr=6.25e-05

OR train context_aware_description seed=4 epoch=17:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=17 loss=0.1118 valid_FITB=0.6087 lr=3.13e-05

OR train context_aware_description seed=4 epoch=18:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=18 loss=0.1108 valid_FITB=0.6090 lr=3.13e-05

OR train context_aware_description seed=4 epoch=19:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=19 loss=0.1058 valid_FITB=0.6113 lr=3.13e-05

OR train context_aware_description seed=4 epoch=20:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=20 loss=0.1041 valid_FITB=0.6070 lr=1.56e-05

OR train context_aware_description seed=4 epoch=21:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=21 loss=0.1026 valid_FITB=0.6070 lr=1.56e-05

OR train context_aware_description seed=4 epoch=22:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=22 loss=0.1003 valid_FITB=0.6063 lr=1.56e-05

OR train context_aware_description seed=4 epoch=23:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=23 loss=0.0997 valid_FITB=0.6077 lr=7.81e-06

OR train context_aware_description seed=4 epoch=24:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=24 loss=0.0997 valid_FITB=0.6050 lr=7.81e-06

OR train context_aware_description seed=4 epoch=25:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=25 loss=0.0994 valid_FITB=0.6053 lr=7.81e-06

OR train context_aware_description seed=4 epoch=26:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=26 loss=0.0980 valid_FITB=0.6070 lr=3.91e-06

OR train context_aware_description seed=4 epoch=27:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=27 loss=0.0976 valid_FITB=0.6063 lr=3.91e-06

OR train context_aware_description seed=4 epoch=28:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=28 loss=0.0977 valid_FITB=0.6063 lr=3.91e-06

OR train context_aware_description seed=4 epoch=29:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=29 loss=0.0981 valid_FITB=0.6077 lr=1.95e-06

OR train context_aware_description seed=4 epoch=30:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=30 loss=0.0967 valid_FITB=0.6083 lr=1.95e-06

OR train context_aware_description seed=4 epoch=31:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=31 loss=0.0974 valid_FITB=0.6073 lr=1.95e-06

OR train context_aware_description seed=4 epoch=32:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=32 loss=0.1000 valid_FITB=0.6067 lr=9.77e-07

OR train context_aware_description seed=4 epoch=33:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=33 loss=0.0956 valid_FITB=0.6070 lr=9.77e-07

OR train context_aware_description seed=4 epoch=34:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=34 loss=0.0972 valid_FITB=0.6067 lr=9.77e-07

OR train context_aware_description seed=4 epoch=35:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=35 loss=0.0961 valid_FITB=0.6070 lr=4.88e-07

OR train context_aware_description seed=4 epoch=36:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=36 loss=0.0970 valid_FITB=0.6070 lr=4.88e-07

OR train context_aware_description seed=4 epoch=37:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=37 loss=0.0958 valid_FITB=0.6070 lr=4.88e-07

OR train context_aware_description seed=4 epoch=38:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=38 loss=0.0963 valid_FITB=0.6067 lr=2.44e-07

OR train context_aware_description seed=4 epoch=39:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=39 loss=0.0965 valid_FITB=0.6067 lr=2.44e-07

OR train context_aware_description seed=4 epoch=40:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=40 loss=0.0955 valid_FITB=0.6067 lr=2.44e-07

OR train context_aware_description seed=4 epoch=41:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=41 loss=0.0951 valid_FITB=0.6067 lr=1.22e-07

OR train context_aware_description seed=4 epoch=42:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=42 loss=0.0958 valid_FITB=0.6067 lr=1.22e-07

OR train context_aware_description seed=4 epoch=43:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=43 loss=0.0977 valid_FITB=0.6067 lr=1.22e-07

OR train context_aware_description seed=4 epoch=44:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=44 loss=0.0943 valid_FITB=0.6067 lr=6.10e-08

OR train context_aware_description seed=4 epoch=45:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=45 loss=0.0983 valid_FITB=0.6067 lr=6.10e-08

OR train context_aware_description seed=4 epoch=46:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=46 loss=0.0967 valid_FITB=0.6067 lr=6.10e-08

OR train context_aware_description seed=4 epoch=47:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=47 loss=0.0958 valid_FITB=0.6067 lr=3.05e-08

OR train context_aware_description seed=4 epoch=48:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=48 loss=0.0965 valid_FITB=0.6067 lr=3.05e-08

OR train context_aware_description seed=4 epoch=49:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=49 loss=0.0957 valid_FITB=0.6067 lr=3.05e-08

OR train context_aware_description seed=4 epoch=50:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=50 loss=0.0966 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=51:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=51 loss=0.0969 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=52:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=52 loss=0.0956 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=53:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=53 loss=0.0961 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=54:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=54 loss=0.0969 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=55:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=55 loss=0.0952 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=56:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=56 loss=0.0980 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=57:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=57 loss=0.0976 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=58:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=58 loss=0.0966 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=59:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=59 loss=0.0968 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=60:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=60 loss=0.0961 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=61:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=61 loss=0.0960 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=62:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=62 loss=0.0983 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=63:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=63 loss=0.0953 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=64:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=64 loss=0.0995 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=65:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=65 loss=0.0956 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=66:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=66 loss=0.0957 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=67:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=67 loss=0.0946 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=68:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=68 loss=0.0970 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=69:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=69 loss=0.0975 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=70:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=70 loss=0.0976 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=71:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=71 loss=0.0961 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=72:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=72 loss=0.0974 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=73:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=73 loss=0.0973 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=74:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=74 loss=0.0981 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=75:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=75 loss=0.0969 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=76:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=76 loss=0.0947 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=77:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=77 loss=0.0970 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=78:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=78 loss=0.0959 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=79:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=79 loss=0.0959 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=80:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=80 loss=0.0966 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=81:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=81 loss=0.0964 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=82:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=82 loss=0.0977 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=83:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=83 loss=0.0963 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=84:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=84 loss=0.0972 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=85:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=85 loss=0.0953 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=86:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=86 loss=0.0980 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=87:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=87 loss=0.0967 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=88:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=88 loss=0.0971 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=89:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=89 loss=0.0959 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=90:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=90 loss=0.0961 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=91:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=91 loss=0.0947 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=92:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=92 loss=0.0982 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=93:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=93 loss=0.0965 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=94:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=94 loss=0.0952 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=95:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=95 loss=0.0961 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=96:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=96 loss=0.0958 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=97:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=97 loss=0.0957 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=98:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=98 loss=0.0969 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=99:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=99 loss=0.0970 valid_FITB=0.6067 lr=1.53e-08

OR train context_aware_description seed=4 epoch=100:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=100 loss=0.0939 valid_FITB=0.6067 lr=1.53e-08

encode candidate pools [context_aware_description seed=4]:   0%|          | 0/19 [00:00<?, ?it/s]

OR/CIR recall [context_aware_description seed=4]:   0%|          | 0/15145 [00:00<?, ?it/s]

[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/context_aware_description/seed_4/seed_summary.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/context_aware_description/seed_4/or_recall_rowlevel.csv

[CP 訓練] variant=context_aware_description, seed=5, train=33,990, valid=6,000

CP train context_aware_description seed=5 epoch=1:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=01 loss=0.6071 valid_AUC=0.8243 valid_FITB=0.4203 lr=1.00e-03

CP train context_aware_description seed=5 epoch=2:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=02 loss=0.4572 valid_AUC=0.8838 valid_FITB=0.4547 lr=1.00e-03

CP train context_aware_description seed=5 epoch=3:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=03 loss=0.3943 valid_AUC=0.9030 valid_FITB=0.4890 lr=1.00e-03

CP train context_aware_description seed=5 epoch=4:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=04 loss=0.3537 valid_AUC=0.9101 valid_FITB=0.5187 lr=1.00e-03

CP train context_aware_description seed=5 epoch=5:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=05 loss=0.3180 valid_AUC=0.9204 valid_FITB=0.5243 lr=1.00e-03

CP train context_aware_description seed=5 epoch=6:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=06 loss=0.2785 valid_AUC=0.9267 valid_FITB=0.5430 lr=1.00e-03

CP train context_aware_description seed=5 epoch=7:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=07 loss=0.2485 valid_AUC=0.9277 valid_FITB=0.5573 lr=1.00e-03

CP train context_aware_description seed=5 epoch=8:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=08 loss=0.2176 valid_AUC=0.9349 valid_FITB=0.5547 lr=1.00e-03

CP train context_aware_description seed=5 epoch=9:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=09 loss=0.1888 valid_AUC=0.9284 valid_FITB=0.5367 lr=1.00e-03

CP train context_aware_description seed=5 epoch=10:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=10 loss=0.1687 valid_AUC=0.9345 valid_FITB=0.5537 lr=5.00e-04

CP train context_aware_description seed=5 epoch=11:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=11 loss=0.1075 valid_AUC=0.9412 valid_FITB=0.5623 lr=5.00e-04

CP train context_aware_description seed=5 epoch=12:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=12 loss=0.0854 valid_AUC=0.9386 valid_FITB=0.5610 lr=5.00e-04

CP train context_aware_description seed=5 epoch=13:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=13 loss=0.0710 valid_AUC=0.9374 valid_FITB=0.5620 lr=5.00e-04

CP train context_aware_description seed=5 epoch=14:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=14 loss=0.0622 valid_AUC=0.9393 valid_FITB=0.5510 lr=2.50e-04

CP train context_aware_description seed=5 epoch=15:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=15 loss=0.0365 valid_AUC=0.9410 valid_FITB=0.5517 lr=2.50e-04

CP train context_aware_description seed=5 epoch=16:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=16 loss=0.0288 valid_AUC=0.9407 valid_FITB=0.5510 lr=2.50e-04

CP train context_aware_description seed=5 epoch=17:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=17 loss=0.0261 valid_AUC=0.9404 valid_FITB=0.5550 lr=1.25e-04

CP train context_aware_description seed=5 epoch=18:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=18 loss=0.0201 valid_AUC=0.9420 valid_FITB=0.5537 lr=1.25e-04

CP train context_aware_description seed=5 epoch=19:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=19 loss=0.0175 valid_AUC=0.9408 valid_FITB=0.5560 lr=1.25e-04

CP train context_aware_description seed=5 epoch=20:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=20 loss=0.0156 valid_AUC=0.9416 valid_FITB=0.5527 lr=6.25e-05

CP train context_aware_description seed=5 epoch=21:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=21 loss=0.0123 valid_AUC=0.9415 valid_FITB=0.5560 lr=6.25e-05

CP train context_aware_description seed=5 epoch=22:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=22 loss=0.0121 valid_AUC=0.9412 valid_FITB=0.5530 lr=6.25e-05

CP train context_aware_description seed=5 epoch=23:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=23 loss=0.0117 valid_AUC=0.9413 valid_FITB=0.5523 lr=3.13e-05

CP train context_aware_description seed=5 epoch=24:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=24 loss=0.0105 valid_AUC=0.9411 valid_FITB=0.5517 lr=3.13e-05

CP train context_aware_description seed=5 epoch=25:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=25 loss=0.0102 valid_AUC=0.9417 valid_FITB=0.5510 lr=3.13e-05

CP train context_aware_description seed=5 epoch=26:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=26 loss=0.0104 valid_AUC=0.9415 valid_FITB=0.5527 lr=1.56e-05

CP train context_aware_description seed=5 epoch=27:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=27 loss=0.0097 valid_AUC=0.9416 valid_FITB=0.5523 lr=1.56e-05

CP train context_aware_description seed=5 epoch=28:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=28 loss=0.0095 valid_AUC=0.9418 valid_FITB=0.5547 lr=1.56e-05

CP train context_aware_description seed=5 epoch=29:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=29 loss=0.0094 valid_AUC=0.9415 valid_FITB=0.5560 lr=7.81e-06

CP train context_aware_description seed=5 epoch=30:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=30 loss=0.0086 valid_AUC=0.9416 valid_FITB=0.5537 lr=7.81e-06

CP train context_aware_description seed=5 epoch=31:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=31 loss=0.0087 valid_AUC=0.9416 valid_FITB=0.5530 lr=7.81e-06

CP train context_aware_description seed=5 epoch=32:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=32 loss=0.0082 valid_AUC=0.9415 valid_FITB=0.5527 lr=3.91e-06

CP train context_aware_description seed=5 epoch=33:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=33 loss=0.0094 valid_AUC=0.9415 valid_FITB=0.5537 lr=3.91e-06

CP train context_aware_description seed=5 epoch=34:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=34 loss=0.0088 valid_AUC=0.9416 valid_FITB=0.5530 lr=3.91e-06

CP train context_aware_description seed=5 epoch=35:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=35 loss=0.0079 valid_AUC=0.9416 valid_FITB=0.5510 lr=1.95e-06

CP train context_aware_description seed=5 epoch=36:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=36 loss=0.0089 valid_AUC=0.9416 valid_FITB=0.5517 lr=1.95e-06

CP train context_aware_description seed=5 epoch=37:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=37 loss=0.0086 valid_AUC=0.9416 valid_FITB=0.5530 lr=1.95e-06

CP train context_aware_description seed=5 epoch=38:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=38 loss=0.0086 valid_AUC=0.9415 valid_FITB=0.5537 lr=9.77e-07

CP train context_aware_description seed=5 epoch=39:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=39 loss=0.0079 valid_AUC=0.9416 valid_FITB=0.5543 lr=9.77e-07

CP train context_aware_description seed=5 epoch=40:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=40 loss=0.0086 valid_AUC=0.9415 valid_FITB=0.5537 lr=9.77e-07

CP train context_aware_description seed=5 epoch=41:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=41 loss=0.0084 valid_AUC=0.9416 valid_FITB=0.5537 lr=4.88e-07

CP train context_aware_description seed=5 epoch=42:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=42 loss=0.0088 valid_AUC=0.9416 valid_FITB=0.5530 lr=4.88e-07

CP train context_aware_description seed=5 epoch=43:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=43 loss=0.0083 valid_AUC=0.9415 valid_FITB=0.5533 lr=4.88e-07

CP train context_aware_description seed=5 epoch=44:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=44 loss=0.0081 valid_AUC=0.9415 valid_FITB=0.5530 lr=2.44e-07

CP train context_aware_description seed=5 epoch=45:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=45 loss=0.0086 valid_AUC=0.9415 valid_FITB=0.5530 lr=2.44e-07

CP train context_aware_description seed=5 epoch=46:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=46 loss=0.0082 valid_AUC=0.9415 valid_FITB=0.5537 lr=2.44e-07

CP train context_aware_description seed=5 epoch=47:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=47 loss=0.0084 valid_AUC=0.9415 valid_FITB=0.5537 lr=1.22e-07

CP train context_aware_description seed=5 epoch=48:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=48 loss=0.0081 valid_AUC=0.9415 valid_FITB=0.5537 lr=1.22e-07

CP train context_aware_description seed=5 epoch=49:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=49 loss=0.0080 valid_AUC=0.9415 valid_FITB=0.5537 lr=1.22e-07

CP train context_aware_description seed=5 epoch=50:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=50 loss=0.0081 valid_AUC=0.9415 valid_FITB=0.5540 lr=6.10e-08

CP train context_aware_description seed=5 epoch=51:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=51 loss=0.0084 valid_AUC=0.9415 valid_FITB=0.5540 lr=6.10e-08

CP train context_aware_description seed=5 epoch=52:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=52 loss=0.0083 valid_AUC=0.9415 valid_FITB=0.5540 lr=6.10e-08

CP train context_aware_description seed=5 epoch=53:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=53 loss=0.0086 valid_AUC=0.9415 valid_FITB=0.5543 lr=3.05e-08

CP train context_aware_description seed=5 epoch=54:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=54 loss=0.0085 valid_AUC=0.9415 valid_FITB=0.5543 lr=3.05e-08

CP train context_aware_description seed=5 epoch=55:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=55 loss=0.0086 valid_AUC=0.9415 valid_FITB=0.5543 lr=3.05e-08

CP train context_aware_description seed=5 epoch=56:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=56 loss=0.0087 valid_AUC=0.9415 valid_FITB=0.5543 lr=1.53e-08

CP train context_aware_description seed=5 epoch=57:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=57 loss=0.0087 valid_AUC=0.9415 valid_FITB=0.5543 lr=1.53e-08

CP train context_aware_description seed=5 epoch=58:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=58 loss=0.0087 valid_AUC=0.9415 valid_FITB=0.5543 lr=1.53e-08

CP train context_aware_description seed=5 epoch=59:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=59 loss=0.0087 valid_AUC=0.9415 valid_FITB=0.5543 lr=1.53e-08

CP train context_aware_description seed=5 epoch=60:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=60 loss=0.0085 valid_AUC=0.9415 valid_FITB=0.5543 lr=1.53e-08

CP train context_aware_description seed=5 epoch=61:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=61 loss=0.0086 valid_AUC=0.9415 valid_FITB=0.5543 lr=1.53e-08

CP train context_aware_description seed=5 epoch=62:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=62 loss=0.0087 valid_AUC=0.9415 valid_FITB=0.5543 lr=1.53e-08

CP train context_aware_description seed=5 epoch=63:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=63 loss=0.0083 valid_AUC=0.9415 valid_FITB=0.5543 lr=1.53e-08

CP train context_aware_description seed=5 epoch=64:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=64 loss=0.0084 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=65:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=65 loss=0.0086 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=66:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=66 loss=0.0087 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=67:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=67 loss=0.0080 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=68:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=68 loss=0.0080 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=69:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=69 loss=0.0083 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=70:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=70 loss=0.0080 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=71:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=71 loss=0.0085 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=72:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=72 loss=0.0084 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=73:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=73 loss=0.0086 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=74:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=74 loss=0.0087 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=75:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=75 loss=0.0089 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=76:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=76 loss=0.0085 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=77:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=77 loss=0.0091 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=78:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=78 loss=0.0087 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=79:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=79 loss=0.0084 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=80:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=80 loss=0.0082 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=81:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=81 loss=0.0085 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=82:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=82 loss=0.0087 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=83:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=83 loss=0.0086 valid_AUC=0.9415 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=5 epoch=84:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=84 loss=0.0081 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=85:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=85 loss=0.0083 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=86:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=86 loss=0.0088 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=87:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=87 loss=0.0080 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=88:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=88 loss=0.0084 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=89:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=89 loss=0.0088 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=90:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=90 loss=0.0080 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=91:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=91 loss=0.0080 valid_AUC=0.9415 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=5 epoch=92:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=92 loss=0.0083 valid_AUC=0.9415 valid_FITB=0.5537 lr=1.53e-08

CP train context_aware_description seed=5 epoch=93:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=93 loss=0.0083 valid_AUC=0.9415 valid_FITB=0.5533 lr=1.53e-08

CP train context_aware_description seed=5 epoch=94:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=94 loss=0.0084 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=95:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=95 loss=0.0082 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=96:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=96 loss=0.0084 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=97:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=97 loss=0.0085 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=98:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=98 loss=0.0087 valid_AUC=0.9415 valid_FITB=0.5540 lr=1.53e-08

CP train context_aware_description seed=5 epoch=99:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=99 loss=0.0083 valid_AUC=0.9415 valid_FITB=0.5533 lr=1.53e-08

CP train context_aware_description seed=5 epoch=100:   0%|          | 0/133 [00:00<?, ?it/s]

CP FITB:   0%|          | 0/3000 [00:00<?, ?it/s]

CP epoch=100 loss=0.0088 valid_AUC=0.9415 valid_FITB=0.5537 lr=1.53e-08

CP FITB:   0%|          | 0/15145 [00:00<?, ?it/s]

[OR 訓練] variant=context_aware_description, seed=5, train=16,995, valid=3,000

OR train context_aware_description seed=5 epoch=1:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=01 loss=0.9353 valid_FITB=0.6113 lr=1.00e-03

OR train context_aware_description seed=5 epoch=2:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=02 loss=0.7909 valid_FITB=0.6283 lr=1.00e-03

OR train context_aware_description seed=5 epoch=3:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=03 loss=0.7062 valid_FITB=0.6307 lr=1.00e-03

OR train context_aware_description seed=5 epoch=4:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=04 loss=0.6156 valid_FITB=0.6307 lr=1.00e-03

OR train context_aware_description seed=5 epoch=5:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=05 loss=0.5285 valid_FITB=0.6203 lr=1.00e-03

OR train context_aware_description seed=5 epoch=6:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=06 loss=0.4408 valid_FITB=0.6187 lr=5.00e-04

OR train context_aware_description seed=5 epoch=7:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=07 loss=0.3166 valid_FITB=0.6310 lr=5.00e-04

OR train context_aware_description seed=5 epoch=8:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=08 loss=0.2561 valid_FITB=0.6233 lr=5.00e-04

OR train context_aware_description seed=5 epoch=9:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=09 loss=0.2093 valid_FITB=0.6137 lr=5.00e-04

OR train context_aware_description seed=5 epoch=10:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=10 loss=0.1785 valid_FITB=0.6177 lr=2.50e-04

OR train context_aware_description seed=5 epoch=11:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=11 loss=0.1342 valid_FITB=0.6210 lr=2.50e-04

OR train context_aware_description seed=5 epoch=12:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=12 loss=0.1168 valid_FITB=0.6147 lr=2.50e-04

OR train context_aware_description seed=5 epoch=13:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=13 loss=0.1033 valid_FITB=0.6183 lr=1.25e-04

OR train context_aware_description seed=5 epoch=14:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=14 loss=0.0891 valid_FITB=0.6193 lr=1.25e-04

OR train context_aware_description seed=5 epoch=15:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=15 loss=0.0805 valid_FITB=0.6213 lr=1.25e-04

OR train context_aware_description seed=5 epoch=16:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=16 loss=0.0771 valid_FITB=0.6147 lr=6.25e-05

OR train context_aware_description seed=5 epoch=17:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=17 loss=0.0714 valid_FITB=0.6157 lr=6.25e-05

OR train context_aware_description seed=5 epoch=18:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=18 loss=0.0683 valid_FITB=0.6180 lr=6.25e-05

OR train context_aware_description seed=5 epoch=19:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=19 loss=0.0667 valid_FITB=0.6120 lr=3.13e-05

OR train context_aware_description seed=5 epoch=20:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=20 loss=0.0633 valid_FITB=0.6147 lr=3.13e-05

OR train context_aware_description seed=5 epoch=21:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=21 loss=0.0627 valid_FITB=0.6150 lr=3.13e-05

OR train context_aware_description seed=5 epoch=22:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=22 loss=0.0632 valid_FITB=0.6167 lr=1.56e-05

OR train context_aware_description seed=5 epoch=23:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=23 loss=0.0620 valid_FITB=0.6150 lr=1.56e-05

OR train context_aware_description seed=5 epoch=24:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=24 loss=0.0589 valid_FITB=0.6150 lr=1.56e-05

OR train context_aware_description seed=5 epoch=25:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=25 loss=0.0600 valid_FITB=0.6150 lr=7.81e-06

OR train context_aware_description seed=5 epoch=26:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=26 loss=0.0591 valid_FITB=0.6137 lr=7.81e-06

OR train context_aware_description seed=5 epoch=27:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=27 loss=0.0582 valid_FITB=0.6137 lr=7.81e-06

OR train context_aware_description seed=5 epoch=28:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=28 loss=0.0583 valid_FITB=0.6160 lr=3.91e-06

OR train context_aware_description seed=5 epoch=29:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=29 loss=0.0588 valid_FITB=0.6150 lr=3.91e-06

OR train context_aware_description seed=5 epoch=30:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=30 loss=0.0588 valid_FITB=0.6150 lr=3.91e-06

OR train context_aware_description seed=5 epoch=31:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=31 loss=0.0561 valid_FITB=0.6147 lr=1.95e-06

OR train context_aware_description seed=5 epoch=32:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=32 loss=0.0576 valid_FITB=0.6150 lr=1.95e-06

OR train context_aware_description seed=5 epoch=33:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=33 loss=0.0578 valid_FITB=0.6143 lr=1.95e-06

OR train context_aware_description seed=5 epoch=34:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=34 loss=0.0582 valid_FITB=0.6143 lr=9.77e-07

OR train context_aware_description seed=5 epoch=35:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=35 loss=0.0581 valid_FITB=0.6147 lr=9.77e-07

OR train context_aware_description seed=5 epoch=36:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=36 loss=0.0576 valid_FITB=0.6150 lr=9.77e-07

OR train context_aware_description seed=5 epoch=37:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=37 loss=0.0569 valid_FITB=0.6150 lr=4.88e-07

OR train context_aware_description seed=5 epoch=38:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=38 loss=0.0578 valid_FITB=0.6150 lr=4.88e-07

OR train context_aware_description seed=5 epoch=39:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=39 loss=0.0567 valid_FITB=0.6150 lr=4.88e-07

OR train context_aware_description seed=5 epoch=40:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=40 loss=0.0562 valid_FITB=0.6147 lr=2.44e-07

OR train context_aware_description seed=5 epoch=41:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=41 loss=0.0567 valid_FITB=0.6143 lr=2.44e-07

OR train context_aware_description seed=5 epoch=42:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=42 loss=0.0577 valid_FITB=0.6143 lr=2.44e-07

OR train context_aware_description seed=5 epoch=43:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=43 loss=0.0570 valid_FITB=0.6143 lr=1.22e-07

OR train context_aware_description seed=5 epoch=44:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=44 loss=0.0572 valid_FITB=0.6143 lr=1.22e-07

OR train context_aware_description seed=5 epoch=45:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=45 loss=0.0577 valid_FITB=0.6143 lr=1.22e-07

OR train context_aware_description seed=5 epoch=46:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=46 loss=0.0575 valid_FITB=0.6143 lr=6.10e-08

OR train context_aware_description seed=5 epoch=47:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=47 loss=0.0573 valid_FITB=0.6143 lr=6.10e-08

OR train context_aware_description seed=5 epoch=48:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=48 loss=0.0558 valid_FITB=0.6143 lr=6.10e-08

OR train context_aware_description seed=5 epoch=49:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=49 loss=0.0590 valid_FITB=0.6143 lr=3.05e-08

OR train context_aware_description seed=5 epoch=50:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=50 loss=0.0581 valid_FITB=0.6143 lr=3.05e-08

OR train context_aware_description seed=5 epoch=51:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=51 loss=0.0554 valid_FITB=0.6143 lr=3.05e-08

OR train context_aware_description seed=5 epoch=52:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=52 loss=0.0571 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=53:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=53 loss=0.0566 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=54:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=54 loss=0.0568 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=55:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=55 loss=0.0582 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=56:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=56 loss=0.0564 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=57:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=57 loss=0.0566 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=58:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=58 loss=0.0567 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=59:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=59 loss=0.0570 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=60:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=60 loss=0.0564 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=61:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=61 loss=0.0571 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=62:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=62 loss=0.0559 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=63:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=63 loss=0.0574 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=64:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=64 loss=0.0578 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=65:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=65 loss=0.0572 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=66:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=66 loss=0.0566 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=67:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=67 loss=0.0572 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=68:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=68 loss=0.0578 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=69:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=69 loss=0.0584 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=70:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=70 loss=0.0566 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=71:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=71 loss=0.0578 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=72:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=72 loss=0.0582 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=73:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=73 loss=0.0572 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=74:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=74 loss=0.0562 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=75:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=75 loss=0.0562 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=76:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=76 loss=0.0572 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=77:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=77 loss=0.0574 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=78:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=78 loss=0.0579 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=79:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=79 loss=0.0567 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=80:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=80 loss=0.0567 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=81:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=81 loss=0.0569 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=82:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=82 loss=0.0570 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=83:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=83 loss=0.0570 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=84:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=84 loss=0.0560 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=85:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=85 loss=0.0572 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=86:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=86 loss=0.0579 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=87:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=87 loss=0.0579 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=88:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=88 loss=0.0582 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=89:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=89 loss=0.0583 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=90:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=90 loss=0.0574 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=91:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=91 loss=0.0568 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=92:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=92 loss=0.0561 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=93:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=93 loss=0.0580 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=94:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=94 loss=0.0568 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=95:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=95 loss=0.0573 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=96:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=96 loss=0.0563 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=97:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=97 loss=0.0565 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=98:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=98 loss=0.0573 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=99:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=99 loss=0.0581 valid_FITB=0.6143 lr=1.53e-08

OR train context_aware_description seed=5 epoch=100:   0%|          | 0/67 [00:00<?, ?it/s]

OR epoch=100 loss=0.0567 valid_FITB=0.6143 lr=1.53e-08

encode candidate pools [context_aware_description seed=5]:   0%|          | 0/19 [00:00<?, ?it/s]

OR/CIR recall [context_aware_description seed=5]:   0%|          | 0/15145 [00:00<?, ?it/s]

[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/context_aware_description/seed_5/seed_summary.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/context_aware_description/seed_5/or_recall_rowlevel.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/A30_second_model_two_tower_seed_summary.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/A31_second_model_two_tower_or_rowlevel.csv

[完成] CP→OR seed-level summary
{
  "variant": "original_text",
  "seed": 1,
  "cp_best_epoch": 13,
  "cp_best_valid_fitb_acc": 0.5806666666666667,
  "cp_valid_auc_at_best_fitb": 0.9130273333333334,
  "cp_test_auc": 0.8780349697613288,
  "cp_test_fitb_acc": 0.5422251568174314,
  "or_best_epoch": 1,
  "or_best_valid_fitb_acc": 0.6156666666666667,
  "or_test_fitb_acc": 0.5917464509739188,
  "cp_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/original_text/seed_1/cp_best_model.pt",
  "or_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/original_text/seed_1/best_model.pt",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "or_recall_skipped_questions": 5834,
  "mean_rank": 596.9967780045108,
  "median_rank": 358.0,
  "recall@1": 0.003866394587047578,
  "recall@3": 0.012458382558264418,
  "recall@5": 0.019976372033079153,
  "recall@10": 0.03801954677263452,
  "recall@30": 0.09461926753302545,
  "recall@50": 0.14284180002147998
}
{
  "variant": "original_text",
  "seed": 2,
  "cp_best_epoch": 12,
  "cp_best_valid_fitb_acc": 0.5773333333333334,
  "cp_valid_auc_at_best_fitb": 0.9137965555555556,
  "cp_test_auc": 0.8810136873216659,
  "cp_test_fitb_acc": 0.5473093430174976,
  "or_best_epoch": 2,
  "or_best_valid_fitb_acc": 0.613,
  "or_test_fitb_acc": 0.5875866622647739,
  "cp_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/original_text/seed_2/cp_best_model.pt",
  "or_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/original_text/seed_2/best_model.pt",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "or_recall_skipped_questions": 5834,
  "mean_rank": 601.6036945548276,
  "median_rank": 358.0,
  "recall@1": 0.006229191279132209,
  "recall@3": 0.013961980453227366,
  "recall@5": 0.02158736977768231,
  "recall@10": 0.03844914617119536,
  "recall@30": 0.09751906347331114,
  "recall@50": 0.14531199656320481
}
{
  "variant": "original_text",
  "seed": 3,
  "cp_best_epoch": 28,
  "cp_best_valid_fitb_acc": 0.573,
  "cp_valid_auc_at_best_fitb": 0.9131775555555556,
  "cp_test_auc": 0.8795972355270244,
  "cp_test_fitb_acc": 0.5425552987784747,
  "or_best_epoch": 2,
  "or_best_valid_fitb_acc": 0.6073333333333333,
  "or_test_fitb_acc": 0.5927368768570486,
  "cp_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/original_text/seed_3/cp_best_model.pt",
  "or_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/original_text/seed_3/best_model.pt",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "or_recall_skipped_questions": 5834,
  "mean_rank": 598.7540543443239,
  "median_rank": 357.0,
  "recall@1": 0.004618193534529052,
  "recall@3": 0.012350982708624208,
  "recall@5": 0.02115777037912147,
  "recall@10": 0.03662334872731178,
  "recall@30": 0.09343786918698314,
  "recall@50": 0.13983460423155408
}
{
  "variant": "original_text",
  "seed": 4,
  "cp_best_epoch": 11,
  "cp_best_valid_fitb_acc": 0.5703333333333334,
  "cp_valid_auc_at_best_fitb": 0.9083866666666667,
  "cp_test_auc": 0.8758849008936503,
  "cp_test_fitb_acc": 0.5434136678771871,
  "or_best_epoch": 3,
  "or_best_valid_fitb_acc": 0.612,
  "or_test_fitb_acc": 0.5908220534829977,
  "cp_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/original_text/seed_4/cp_best_model.pt",
  "or_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/original_text/seed_4/best_model.pt",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "or_recall_skipped_questions": 5834,
  "mean_rank": 613.3673074857695,
  "median_rank": 372.0,
  "recall@1": 0.004403393835248631,
  "recall@3": 0.012243582858983998,
  "recall@5": 0.01911717323595747,
  "recall@10": 0.03737514767479325,
  "recall@30": 0.09354526903662334,
  "recall@50": 0.13886800558479218
}
{
  "variant": "original_text",
  "seed": 5,
  "cp_best_epoch": 11,
  "cp_best_valid_fitb_acc": 0.5886666666666667,
  "cp_valid_auc_at_best_fitb": 0.9188226666666666,
  "cp_test_auc": 0.8835092379257581,
  "cp_test_fitb_acc": 0.5543083525916144,
  "or_best_epoch": 1,
  "or_best_valid_fitb_acc": 0.62,
  "or_test_fitb_acc": 0.5908880818752064,
  "cp_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/original_text/seed_5/cp_best_model.pt",
  "or_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/original_text/seed_5/best_model.pt",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "or_recall_skipped_questions": 5834,
  "mean_rank": 596.072817098056,
  "median_rank": 361.0,
  "recall@1": 0.004940393083449683,
  "recall@3": 0.012028783159703576,
  "recall@5": 0.020298571581999787,
  "recall@10": 0.03834174632155515,
  "recall@30": 0.09590806572870798,
  "recall@50": 0.14262700032219955
}
{
  "variant": "context_aware_description",
  "seed": 1,
  "cp_best_epoch": 21,
  "cp_best_valid_fitb_acc": 0.5676666666666667,
  "cp_valid_auc_at_best_fitb": 0.9414951111111112,
  "cp_test_auc": 0.9207126924597386,
  "cp_test_fitb_acc": 0.5441399801914824,
  "or_best_epoch": 5,
  "or_best_valid_fitb_acc": 0.6376666666666667,
  "or_test_fitb_acc": 0.6068669527896996,
  "cp_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/context_aware_description/seed_1/cp_best_model.pt",
  "or_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/context_aware_description/seed_1/best_model.pt",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "or_recall_skipped_questions": 5834,
  "mean_rank": 567.1305982171625,
  "median_rank": 331.0,
  "recall@1": 0.006014391579851788,
  "recall@3": 0.016432176994952207,
  "recall@5": 0.026312963161851572,
  "recall@10": 0.04736333369133283,
  "recall@30": 0.10965524648265493,
  "recall@50": 0.15819997852003007
}
{
  "variant": "context_aware_description",
  "seed": 2,
  "cp_best_epoch": 20,
  "cp_best_valid_fitb_acc": 0.5636666666666666,
  "cp_valid_auc_at_best_fitb": 0.9432805555555555,
  "cp_test_auc": 0.9202698597174599,
  "cp_test_fitb_acc": 0.5396500495212941,
  "or_best_epoch": 3,
  "or_best_valid_fitb_acc": 0.6293333333333333,
  "or_test_fitb_acc": 0.6136018487949818,
  "cp_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/context_aware_description/seed_2/cp_best_model.pt",
  "or_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/context_aware_description/seed_2/best_model.pt",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "or_recall_skipped_questions": 5834,
  "mean_rank": 557.9240683063043,
  "median_rank": 314.0,
  "recall@1": 0.00859198797121684,
  "recall@3": 0.01911717323595747,
  "recall@5": 0.02985715819997852,
  "recall@10": 0.05047792933089894,
  "recall@30": 0.11212544302437977,
  "recall@50": 0.16442916979916228
}
{
  "variant": "context_aware_description",
  "seed": 3,
  "cp_best_epoch": 21,
  "cp_best_valid_fitb_acc": 0.547,
  "cp_valid_auc_at_best_fitb": 0.9370046666666667,
  "cp_test_auc": 0.9164340918823553,
  "cp_test_fitb_acc": 0.5315945856718389,
  "or_best_epoch": 5,
  "or_best_valid_fitb_acc": 0.6356666666666667,
  "or_test_fitb_acc": 0.5989435457246616,
  "cp_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/context_aware_description/seed_3/cp_best_model.pt",
  "or_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/context_aware_description/seed_3/best_model.pt",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "or_recall_skipped_questions": 5834,
  "mean_rank": 586.1518633873912,
  "median_rank": 340.0,
  "recall@1": 0.005262592632370315,
  "recall@3": 0.016646976694232627,
  "recall@5": 0.026849962410052625,
  "recall@10": 0.04575233594672967,
  "recall@30": 0.10976264633229514,
  "recall@50": 0.15712598002362796
}
{
  "variant": "context_aware_description",
  "seed": 4,
  "cp_best_epoch": 10,
  "cp_best_valid_fitb_acc": 0.569,
  "cp_valid_auc_at_best_fitb": 0.9369627777777777,
  "cp_test_auc": 0.9124450004092715,
  "cp_test_fitb_acc": 0.5410366457576758,
  "or_best_epoch": 2,
  "or_best_valid_fitb_acc": 0.6216666666666667,
  "or_test_fitb_acc": 0.6029052492571806,
  "cp_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/context_aware_description/seed_4/cp_best_model.pt",
  "or_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/context_aware_description/seed_4/best_model.pt",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "or_recall_skipped_questions": 5834,
  "mean_rank": 574.7405219632692,
  "median_rank": 335.0,
  "recall@1": 0.006658790677693051,
  "recall@3": 0.01686177639351305,
  "recall@5": 0.02727956180861347,
  "recall@10": 0.04822253248845452,
  "recall@30": 0.10600365159488777,
  "recall@50": 0.1525077864890989
}
{
  "variant": "context_aware_description",
  "seed": 5,
  "cp_best_epoch": 11,
  "cp_best_valid_fitb_acc": 0.5623333333333334,
  "cp_valid_auc_at_best_fitb": 0.9411688888888888,
  "cp_test_auc": 0.9172816117467322,
  "cp_test_fitb_acc": 0.534763948497854,
  "or_best_epoch": 7,
  "or_best_valid_fitb_acc": 0.631,
  "or_test_fitb_acc": 0.6099702872235061,
  "cp_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/context_aware_description/seed_5/cp_best_model.pt",
  "or_checkpoint": "/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/context_aware_description/seed_5/best_model.pt",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "or_recall_skipped_questions": 5834,
  "mean_rank": 576.3920094511868,
  "median_rank": 329.0,
  "recall@1": 0.006980990226613683,
  "recall@3": 0.017613575340994524,
  "recall@5": 0.026205563312211362,
  "recall@10": 0.047900332939533885,
  "recall@30": 0.11395124046826334,
  "recall@50": 0.16206637310707764
}

In [13]:
# ------------------------------------------------------------
# 5 seeds mean/std 彙整
# ------------------------------------------------------------
if all_seed_rows:
    metrics = [
        'cp_best_valid_fitb_acc',
        'cp_valid_auc_at_best_fitb',
        'cp_test_auc',
        'cp_test_fitb_acc',
        'or_best_valid_fitb_acc',
        'or_test_fitb_acc',
        'mean_rank',
        'median_rank',
    ] + [f'recall@{k}' for k in K_LIST]

    aggregate_rows = []
    for variant_key in TEXT_VARIANTS.keys():
        rows = [row for row in all_seed_rows if row['variant'] == variant_key]
        out = {
            'variant': variant_key,
            'n_seeds': len(rows),
            'seeds': ','.join(str(row['seed']) for row in rows),
            'test_fitb_questions': rows[0]['test_fitb_questions'] if rows else '',
            'or_recall_evaluable_pairs': rows[0]['or_recall_evaluable_pairs'] if rows else '',
        }
        for metric in metrics:
            values = [float(row[metric]) for row in rows]
            out[f'{metric}_mean'] = float(np.mean(values)) if values else float('nan')
            out[f'{metric}_std'] = float(np.std(values, ddof=1)) if len(values) > 1 else 0.0
            out[f'{metric}_mean±std'] = mean_std_text(values)
        aggregate_rows.append(out)

    aggregate_path = RESULT_ROOT / 'A32_second_model_two_tower_mean_std.csv'
    write_csv(aggregate_path, aggregate_rows)

    interpretation_lines = [
        'P15 第二模型補充驗證說明',
        '',
        '本實驗將第二模型改為 CP→OR 兩階段流程，並與主模型設定對齊為最多訓練 100 epochs。',
        '第一階段使用 compatibility_train.txt 訓練 binary compatibility prediction model；每個 epoch 監控 validation AUC，但以 validation FITB Accuracy 更新 cp_best_model.pt。',
        'CP 最佳 checkpoint 於 compatibility_test.txt 回報 AUC，並於 fill_in_blank_test.json 回報 FITB Accuracy。',
        '第二階段將 CP model 的 item encoder 與 outfit text encoder 遷移至 OR retrieval model，再以 validation FITB Accuracy 更新最佳 OR checkpoint，並於 OR/CIR candidate pool 回報 Recall@K。',
        'original_text 與 context_aware_description 兩組條件分開訓練，checkpoint 與結果皆儲存在 second_model_runs/fashionclip_two_tower_fitb_or。',
        '',
        f'CP test pairs：{len(compat_examples_by_split["test"]):,}',
        f'FITB test questions：{len(fitb_examples_by_split["test"]):,}',
        f'OR/CIR Recall evaluable query-target pairs：{aggregate_rows[0]["or_recall_evaluable_pairs"]:,}' if aggregate_rows else '',
        '',
        '論文定位：此模型作為跨架構補充驗證，用來檢查情境感知描述的改善趨勢是否仍存在於另一個 CP→OR 訓練流程中；主結果仍以 Hybrid Attention Layer 為準。',
    ]
    interpretation_path = RESULT_ROOT / 'A33_second_model_two_tower_interpretation.txt'
    interpretation_path.write_text('\n'.join(interpretation_lines), encoding='utf-8')
    print(f'[寫入] {interpretation_path}')

    print('\n[彙整結果]')
    for row in aggregate_rows:
        print(json.dumps(row, ensure_ascii=False, indent=2))
else:
    print('沒有可彙整的 seed 結果。')

[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/A32_second_model_two_tower_mean_std.csv
[寫入] /home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/A33_second_model_two_tower_interpretation.txt

[彙整結果]
{
  "variant": "original_text",
  "n_seeds": 5,
  "seeds": "1,2,3,4,5",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "cp_best_valid_fitb_acc_mean": 0.578,
  "cp_best_valid_fitb_acc_std": 0.00716085035298028,
  "cp_best_valid_fitb_acc_mean?std": "0.5780 ± 0.0072",
  "cp_valid_auc_at_best_fitb_mean": 0.9134421555555555,
  "cp_valid_auc_at_best_fitb_std": 0.0037039019195477256,
  "cp_valid_auc_at_best_fitb_mean?std": "0.9134 ± 0.0037",
  "cp_test_auc_mean": 0.8796080062858855,
  "cp_test_auc_std": 0.0028953247296642694,
  "cp_test_auc_mean?std": "0.8796 ± 0.0029",
  "cp_test_fitb_acc_mean": 0.545962363816441,
  "cp_test_fitb_acc_std": 0.005087743628578046,
  "cp_test_fitb_acc_mean?std": "0.5460 ± 0.0051",
  "or_best_valid_fitb_acc_mean": 0.6136,
  "or_best_valid_fitb_acc_std": 0.004674992572780811,
  "or_best_valid_fitb_acc_mean?std": "0.6136 ± 0.0047",
  "or_test_fitb_acc_mean": 0.5907560250907891,
  "or_test_fitb_acc_std": 0.0019346431593243528,
  "or_test_fitb_acc_mean?std": "0.5908 ± 0.0019",
  "mean_rank_mean": 601.3589302974976,
  "mean_rank_std": 7.035939460253665,
  "mean_rank_mean?std": "601.3589 ± 7.0359",
  "median_rank_mean": 361.2,
  "median_rank_std": 6.220932405998316,
  "median_rank_mean?std": "361.2000 ± 6.2209",
  "recall@1_mean": 0.0048115132638814305,
  "recall@1_std": 0.0008836860672634179,
  "recall@1_mean?std": "0.0048 ± 0.0009",
  "recall@3_mean": 0.012608742347760712,
  "recall@3_std": 0.0007729805269228476,
  "recall@3_mean?std": "0.0126 ± 0.0008",
  "recall@5_mean": 0.020427451401568035,
  "recall@5_std": 0.0009766892960489442,
  "recall@5_mean?std": "0.0204 ± 0.0010",
  "recall@10_mean": 0.037761787133498016,
  "recall@10_std": 0.0007617065074212073,
  "recall@10_mean?std": "0.0378 ± 0.0008",
  "recall@30_mean": 0.09500590699173021,
  "recall@30_std": 0.001722755188038906,
  "recall@30_mean?std": "0.0950 ± 0.0017",
  "recall@50_mean": 0.14189668134464611,
  "recall@50_std": 0.0025746860023631206,
  "recall@50_mean?std": "0.1419 ± 0.0026"
}
{
  "variant": "context_aware_description",
  "n_seeds": 5,
  "seeds": "1,2,3,4,5",
  "test_fitb_questions": 15145,
  "or_recall_evaluable_pairs": 9311,
  "cp_best_valid_fitb_acc_mean": 0.5619333333333334,
  "cp_best_valid_fitb_acc_std": 0.0087888818654277,
  "cp_best_valid_fitb_acc_mean?std": "0.5619 ± 0.0088",
  "cp_valid_auc_at_best_fitb_mean": 0.9399823999999999,
  "cp_valid_auc_at_best_fitb_std": 0.002853020111529189,
  "cp_valid_auc_at_best_fitb_mean?std": "0.9400 ± 0.0029",
  "cp_test_auc_mean": 0.9174286512431115,
  "cp_test_auc_std": 0.0033430875278854457,
  "cp_test_auc_mean?std": "0.9174 ± 0.0033",
  "cp_test_fitb_acc_mean": 0.538237041928029,
  "cp_test_fitb_acc_std": 0.005021544963800064,
  "cp_test_fitb_acc_mean?std": "0.5382 ± 0.0050",
  "or_best_valid_fitb_acc_mean": 0.6310666666666667,
  "or_best_valid_fitb_acc_std": 0.006246776946731999,
  "or_best_valid_fitb_acc_mean?std": "0.6311 ± 0.0062",
  "or_test_fitb_acc_mean": 0.6064575767580058,
  "or_test_fitb_acc_std": 0.005758190677879147,
  "or_test_fitb_acc_mean?std": "0.6065 ± 0.0058",
  "mean_rank_mean": 572.4678122650628,
  "mean_rank_std": 10.580927773326772,
  "mean_rank_mean?std": "572.4678 ± 10.5809",
  "median_rank_mean": 329.8,
  "median_rank_std": 9.78263768111648,
  "median_rank_mean?std": "329.8000 ± 9.7826",
  "recall@1_mean": 0.006701750617549136,
  "recall@1_std": 0.0012446340548442174,
  "recall@1_mean?std": "0.0067 ± 0.0012",
  "recall@3_mean": 0.017334335731929974,
  "recall@3_std": 0.0010915756371837108,
  "recall@3_mean?std": "0.0173 ± 0.0011",
  "recall@5_mean": 0.027301041778541507,
  "recall@5_std": 0.001492819276459591,
  "recall@5_mean?std": "0.0273 ± 0.0015",
  "recall@10_mean": 0.04794329287938997,
  "recall@10_std": 0.0017059342892975869,
  "recall@10_mean?std": "0.0479 ± 0.0017",
  "recall@30_mean": 0.11029964558049618,
  "recall@30_std": 0.002992777315668084,
  "recall@30_mean?std": "0.1103 ± 0.0030",
  "recall@50_mean": 0.15886585758779936,
  "recall@50_std": 0.004612195228889687,
  "recall@50_mean?std": "0.1589 ± 0.0046"
}

In [14]:
# ------------------------------------------------------------
# 輸出位置確認
# ------------------------------------------------------------
print('CP checkpoint：')
print(MODEL_ROOT / '<variant>' / '<seed>' / 'cp_best_model.pt')
print('\nOR checkpoint：')
print(MODEL_ROOT / '<variant>' / '<seed>' / 'best_model.pt')
print('\n主要輸出檔案：')
for path in [
    RESULT_ROOT / 'A30_second_model_two_tower_seed_summary.csv',
    RESULT_ROOT / 'A31_second_model_two_tower_or_rowlevel.csv',
    RESULT_ROOT / 'A32_second_model_two_tower_mean_std.csv',
    RESULT_ROOT / 'A33_second_model_two_tower_interpretation.txt',
]:
    print(path)

CP checkpoint：
/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/<variant>/<seed>/cp_best_model.pt

OR checkpoint：
/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/models/<variant>/<seed>/best_model.pt

主要輸出檔案：
/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/A30_second_model_two_tower_seed_summary.csv
/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/A31_second_model_two_tower_or_rowlevel.csv
/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/A32_second_model_two_tower_mean_std.csv
/home/ester/valid_description/experiment data/journal_figures_tables_20260629/second_model_runs/fashionclip_two_tower_fitb_or/results/A33_second_model_two_tower_interpretation.txt

In [15]:
from pathlib import Path
import numpy as np
import pandas as pd
from IPython.display import display

# ------------------------------------------------------------
# 1. 讀取既有結果
# ------------------------------------------------------------

ROOT = Path("/home/ester/valid_description")
JOURNAL_DIR = ROOT / "experiment data" / "journal_figures_tables_20260629"

MAIN_PATH = JOURNAL_DIR / "derived_audits" / "A14_statistical_rigor_ci_adjusted_p_effect_sizes.csv"

SECOND_RESULT_DIR = (
    JOURNAL_DIR
    / "second_model_runs"
    / "fashionclip_two_tower_fitb_or"
    / "results"
)

SECOND_MEAN_PATH = SECOND_RESULT_DIR / "A32_second_model_two_tower_mean_std.csv"
SECOND_SEED_PATH = SECOND_RESULT_DIR / "A30_second_model_two_tower_seed_summary.csv"

main_df = pd.read_csv(MAIN_PATH)
second_mean_df = pd.read_csv(SECOND_MEAN_PATH)
second_seed_df = pd.read_csv(SECOND_SEED_PATH)

# ------------------------------------------------------------
# 2. 格式工具
# ------------------------------------------------------------

def mean_std(mean, std, digits=4):
    return f"{float(mean):.{digits}f} ± {float(std):.{digits}f}"

def signed(x, digits=4):
    return f"{float(x):+.{digits}f}"

def ci_text(low, high, digits=4):
    return f"[{float(low):.{digits}f}, {float(high):.{digits}f}]"

def paired_ci_second(metric):
    pivot = second_seed_df.pivot(
        index="seed",
        columns="variant",
        values=metric
    )

    diff = pivot["context_aware_description"] - pivot["original_text"]
    n = len(diff)

    # df=4 時 95% CI 的 t critical 約為 2.776；若目前只跑 seed1，CI 會以 ±0 呈現。
    if n <= 1:
        mean_diff = diff.mean()
        return mean_diff, mean_diff, mean_diff

    t_crit = 2.776
    mean_diff = diff.mean()
    se = diff.std(ddof=1) / np.sqrt(n)

    return mean_diff, mean_diff - t_crit * se, mean_diff + t_crit * se

# ------------------------------------------------------------
# 3. 第二模型欄位自動對應
# ------------------------------------------------------------

old = second_mean_df[second_mean_df["variant"] == "original_text"].iloc[0]
new = second_mean_df[second_mean_df["variant"] == "context_aware_description"].iloc[0]

# 新版 CP→OR 第二模型欄位
SECOND_CP_AUC = "cp_test_auc"
SECOND_CP_FITB = "cp_test_fitb_acc"
SECOND_OR_FITB = "or_test_fitb_acc"

# ------------------------------------------------------------
# 4. 表 1：CP / FITB 任務比較
# ------------------------------------------------------------

cp_rows = []

# 主模型：CP AUC / FITB
for metric_key, metric_name in [
    ("auc", "AUC"),
    ("fitb_acc", "FITB Accuracy"),
]:
    r = main_df[
        (main_df["task"] == "CP") &
        (main_df["metric"] == metric_key)
    ].iloc[0]

    cp_rows.append({
        "Model": "Hybrid Attention",
        "Metric": metric_name,
        "Original text": mean_std(r["baseline_mean"], r["baseline_std"]),
        "Context-aware": mean_std(r["proposed_mean"], r["proposed_std"]),
        "Δ": signed(r["mean_difference"]),
        "95% CI": ci_text(r["ci95_low"], r["ci95_high"]),
    })

# 第二模型：CP AUC / CP FITB
for metric_key, metric_name in [
    (SECOND_CP_AUC, "AUC"),
    (SECOND_CP_FITB, "FITB Accuracy"),
]:
    diff, low, high = paired_ci_second(metric_key)

    cp_rows.append({
        "Model": "Two-Tower",
        "Metric": metric_name,
        "Original text": mean_std(
            old[f"{metric_key}_mean"],
            old[f"{metric_key}_std"],
        ),
        "Context-aware": mean_std(
            new[f"{metric_key}_mean"],
            new[f"{metric_key}_std"],
        ),
        "Δ": signed(diff),
        "95% CI": ci_text(low, high),
    })

cp_table = pd.DataFrame(cp_rows)

print("Table. CP / FITB task comparison")
display(cp_table)

# ------------------------------------------------------------
# 5. 表 2：OR / CIR 任務比較
# ------------------------------------------------------------

or_rows = []

# 主模型：CIR Recall
for metric_key, metric_name in [
    ("recall_at_10", "Recall@10"),
    ("recall_at_30", "Recall@30"),
    ("recall_at_50", "Recall@50"),
]:
    r = main_df[
        (main_df["task"] == "CIR") &
        (main_df["metric"] == metric_key)
    ].iloc[0]

    or_rows.append({
        "Model": "Hybrid Attention",
        "Metric": metric_name,
        "Original text": mean_std(r["baseline_mean"], r["baseline_std"]),
        "Context-aware": mean_std(r["proposed_mean"], r["proposed_std"]),
        "Δ": signed(r["mean_difference"]),
        "95% CI": ci_text(r["ci95_low"], r["ci95_high"]),
    })

# 第二模型：OR Recall
for metric_key, metric_name in [
    ("recall@10", "Recall@10"),
    ("recall@30", "Recall@30"),
    ("recall@50", "Recall@50"),
]:
    diff, low, high = paired_ci_second(metric_key)

    or_rows.append({
        "Model": "Two-Tower",
        "Metric": metric_name,
        "Original text": mean_std(
            old[f"{metric_key}_mean"],
            old[f"{metric_key}_std"],
        ),
        "Context-aware": mean_std(
            new[f"{metric_key}_mean"],
            new[f"{metric_key}_std"],
        ),
        "Δ": signed(diff),
        "95% CI": ci_text(low, high),
    })

or_table = pd.DataFrame(or_rows)

print("Table. OR / CIR task comparison")
display(or_table)

Table. CP / FITB task comparison

,Model,Metric,Original text,Context-aware,Δ,95% CI
0,Hybrid Attention,AUC,0.9292 ± 0.0013,0.9454 ± 0.0013,+0.0162,"[0.0157, 0.0167]"
1,Hybrid Attention,FITB Accuracy,0.6374 ± 0.0037,0.6478 ± 0.0021,+0.0103,"[0.0054, 0.0153]"
2,Two-Tower,AUC,0.8796 ± 0.0029,0.9174 ± 0.0033,+0.0378,"[0.0337, 0.0420]"
3,Two-Tower,FITB Accuracy,0.5460 ± 0.0051,0.5382 ± 0.0050,-0.0077,"[-0.0180, 0.0025]"

Table. OR / CIR task comparison

,Model,Metric,Original text,Context-aware,Δ,95% CI
0,Hybrid Attention,Recall@10,0.0780 ± 0.0010,0.0921 ± 0.0035,+0.0141,"[0.0101, 0.0182]"
1,Hybrid Attention,Recall@30,0.1677 ± 0.0045,0.1874 ± 0.0038,+0.0197,"[0.0153, 0.0241]"
2,Hybrid Attention,Recall@50,0.2303 ± 0.0035,0.2518 ± 0.0038,+0.0215,"[0.0161, 0.0269]"
3,Two-Tower,Recall@10,0.0378 ± 0.0008,0.0479 ± 0.0017,+0.0102,"[0.0087, 0.0117]"
4,Two-Tower,Recall@30,0.0950 ± 0.0017,0.1103 ± 0.0030,+0.0153,"[0.0127, 0.0179]"
5,Two-Tower,Recall@50,0.1419 ± 0.0026,0.1589 ± 0.0046,+0.0170,"[0.0139, 0.0200]"